// Generated by implement-phase-5-0.sh
import { describe, expect, it } from "vitest";

import {
  AUTHORING_TEST_ROUND,
  createAuthoringTestGame,
  createAuthoringTestTribute,
  withAuthoringTestItem,
} from "~/game/events/authoring/testing/authoring-test-fixtures";
import { createForcedStandardTruceSeparationEvents } from "~/game/truces/forced-truce-separation";
import { createTruceInstance } from "~/game/truces/truce-engine";
import type { GameState, GameTribute, RoundReference, Truce } from "~/game/types/game-state";

const CREATED_ROUND = {
  day: 1,
  period: "day",
} as const satisfies RoundReference;

const COMPATIBILITY_EXPIRY = {
  day: 99,
  period: "day",
} as const satisfies RoundReference;

function createTributes(count: number): GameTribute[] {
  return Array.from({ length: count }, (_, index) =>
    createAuthoringTestTribute({
      id: `tribute-${index + 1}`,
      name: `Tribute ${index + 1}`,
    }),
  );
}

function createStandardTruce(
  eventId: string,
  tributeIds: readonly string[],
  createdRound: RoundReference = CREATED_ROUND,
): Truce {
  return createTruceInstance(eventId, tributeIds, createdRound, COMPATIBILITY_EXPIRY);
}

function createState(
  tributes: readonly GameTribute[],
  truces: readonly Truce[],
  seed = "forced-truce-separation-test",
): GameState {
  return {
    ...createAuthoringTestGame(tributes),
    seed,
    currentRound: AUTHORING_TEST_ROUND,
    truces: [...truces],
  };
}

describe("forced standard-truce separation", () => {
  it("creates deterministic events in stable truce order", () => {
    const tributes = createTributes(12);
    const alphabeticallySecond = createStandardTruce(
      "forced-truce-b",
      tributes.slice(4, 8).map((tribute) => tribute.id),
    );
    const alphabeticallyFirst = createStandardTruce(
      "forced-truce-a",
      tributes.slice(0, 4).map((tribute) => tribute.id),
    );
    const state = createState(
      tributes,
      [alphabeticallySecond, alphabeticallyFirst],
      "forced-order",
    );

    const first = createForcedStandardTruceSeparationEvents(state, AUTHORING_TEST_ROUND);
    const repeated = createForcedStandardTruceSeparationEvents(state, AUTHORING_TEST_ROUND);

    expect(repeated).toEqual(first);
    expect(first.map((event) => event.id)).toEqual([
      "day-2-0-forced-oversized-truce-separation-4",
      "day-2-1-forced-oversized-truce-separation-4",
    ]);
    expect(first.map((event) => event.participantTributeIds)).toEqual([
      alphabeticallyFirst.tributeIds,
      alphabeticallySecond.tributeIds,
    ]);
    expect(first[0]?.changes).toContainEqual({
      type: "break-truce",
      truceId: alphabeticallyFirst.id,
      reason: "amicable",
    });
    expect(first[1]?.changes).toContainEqual({
      type: "break-truce",
      truceId: alphabeticallySecond.id,
      reason: "amicable",
    });
  });

  it("uses only living members for presentation and redistribution", () => {
    const baseTributes = createTributes(6);
    let stockedMember = withAuthoringTestItem(baseTributes[0]!, "knife");
    stockedMember = withAuthoringTestItem(stockedMember, "bow");
    stockedMember = withAuthoringTestItem(stockedMember, "blanket");

    const deadMember: GameTribute = {
      ...baseTributes[2]!,
      isAlive: false,
    };
    const tributes = [stockedMember, baseTributes[1]!, deadMember, ...baseTributes.slice(3)];
    const truce = createStandardTruce(
      "partially-living-truce",
      tributes.slice(0, 3).map((tribute) => tribute.id),
    );
    const state = createState(tributes, [truce], "living-members-only");

    const events = createForcedStandardTruceSeparationEvents(state, AUTHORING_TEST_ROUND);

    expect(events).toHaveLength(1);

    const event = events[0];

    expect(event?.definitionId).toBe("forced-oversized-truce-separation-2");
    expect(event?.participantTributeIds).toEqual([stockedMember.id, tributes[1]!.id]);
    expect(event?.participantTributeIds).not.toContain(deadMember.id);
    expect(event?.changes).toContainEqual({
      type: "break-truce",
      truceId: truce.id,
      reason: "amicable",
    });

    const transferChanges =
      event?.changes.filter((change) => change.type === "transfer-item") ?? [];

    expect(transferChanges.length).toBeGreaterThan(0);

    for (const change of transferChanges) {
      expect(change.reason).toBe("forced-oversized-truce-separation");
      expect(change.fromTributeId).not.toBe(deadMember.id);
      expect(change.toTributeId).not.toBe(deadMember.id);
    }
  });

  it("ignores legal-sized standard truces and romantic truces", () => {
    const tributes = createTributes(10);
    const legalStandardTruce = createStandardTruce(
      "legal-standard-truce",
      tributes.slice(0, 3).map((tribute) => tribute.id),
    );
    const romanticTruce = createTruceInstance(
      "romantic-truce",
      tributes.slice(3, 5).map((tribute) => tribute.id),
      CREATED_ROUND,
      null,
      "romantic",
    );
    const state = createState(tributes, [legalStandardTruce, romanticTruce], "no-forced-events");

    expect(createForcedStandardTruceSeparationEvents(state, AUTHORING_TEST_ROUND)).toEqual([]);
  });
});
