// Generated by implement-phase-5-0.sh
import { describe, expect, it } from "vitest";

import { createInitialGameState } from "~/game/engine/create-initial-game-state";
import {
  MAX_CONSECUTIVE_NON_ELIMINATION_ROUNDS,
  sequenceRoundEvents,
} from "~/game/engine/event-sequencer";
import { getRoundEventTargetCount } from "~/game/engine/stat-formulas";
import { createInventoryItemInstance } from "~/game/items/inventory-engine";
import { createTruceInstance } from "~/game/truces/truce-engine";
import { DEFAULT_TRIBUTES } from "~/game/tributes/default-tributes";
import { createRandomTributeDrafts } from "~/game/tributes/tribute-drafts";
import { createDefaultGameConfig } from "~/game/types/game-config";
import type { GameChange, GameState, ResolvedEvent } from "~/game/types/game-state";

const FIRST_ROUND = {
  day: 1,
  period: "night",
} as const;

const NEXT_ROUND = {
  day: 2,
  period: "day",
} as const;

interface ForcedSafetyFixture {
  seed: string;
  state: GameState;
  events: ResolvedEvent[];
}

function createTestGame(seed: string): GameState {
  const config = {
    ...createDefaultGameConfig(),
    districtCount: 6 as const,
  };
  let nextId = 0;

  return createInitialGameState(
    config,
    createRandomTributeDrafts(6, DEFAULT_TRIBUTES, () => 0.5),
    "random",
    {
      createId: () => {
        nextId += 1;
        return `${seed}-id-${nextId}`;
      },
      seed,
      now: "2026-07-22T12:00:00.000Z",
    },
  );
}

function createForcedSafetyGame(seed: string): GameState {
  const game = createTestGame(seed);
  const equippedTributes = game.tributes.map((tribute, index) => {
    const knife = createInventoryItemInstance(
      `forced-safety-knife:${tribute.id}`,
      tribute.id,
      "knife",
      FIRST_ROUND,
    );
    const extraItems =
      index === 0
        ? [
            createInventoryItemInstance(
              `forced-safety-bow:${tribute.id}`,
              tribute.id,
              "bow",
              FIRST_ROUND,
            ),
            createInventoryItemInstance(
              `forced-safety-blanket:${tribute.id}`,
              tribute.id,
              "blanket",
              FIRST_ROUND,
            ),
          ]
        : [];

    return {
      ...tribute,
      inventory: [...tribute.inventory, knife, ...extraItems],
    };
  });
  const oversizedTruce = createTruceInstance(
    "forced-safety-truce",
    equippedTributes.slice(0, 4).map((tribute) => tribute.id),
    FIRST_ROUND,
    {
      day: 99,
      period: "day",
    },
  );

  return {
    ...game,
    seed,
    currentRound: NEXT_ROUND,
    tributes: equippedTributes,
    truces: [oversizedTruce],
    engine: {
      ...game.engine,
      consecutiveNonEliminationRounds: MAX_CONSECUTIVE_NON_ELIMINATION_ROUNDS,
    },
  };
}

function getCommittedItemInstanceIds(changes: readonly GameChange[]): string[] {
  return changes.flatMap((change) => {
    switch (change.type) {
      case "acquire-item":
        return [change.item.id];

      case "use-item":
      case "consume-item":
      case "transfer-item":
        return [change.itemInstanceId];

      default:
        return [];
    }
  });
}

function findForcedSafetyFixture(): ForcedSafetyFixture {
  for (let index = 0; index < 1_000; index += 1) {
    const seed = `forced-safety-resolution-${index}`;
    const state = createForcedSafetyGame(seed);
    const events = sequenceRoundEvents(state, NEXT_ROUND);
    const forcedEvent = events[0];
    const firstOrdinaryEvent = events[1];
    const forcedTransferCount =
      forcedEvent?.changes.filter((change) => change.type === "transfer-item").length ?? 0;
    const safetyEliminationCount =
      firstOrdinaryEvent?.changes.filter((change) => change.type === "eliminate-tribute").length ??
      0;

    if (
      forcedEvent?.definitionId === "forced-oversized-truce-separation-4" &&
      forcedTransferCount > 0 &&
      firstOrdinaryEvent?.resolutionMode === "safety" &&
      safetyEliminationCount > 0 &&
      events.length === getRoundEventTargetCount(state.tributes.length)
    ) {
      return {
        seed,
        state,
        events,
      };
    }
  }

  throw new Error("No deterministic seed produced the forced-separation safety fixture.");
}

describe("forced truce separation sequencing", () => {
  it("preserves the first ordinary safety resolution and round coverage", () => {
    const fixture = findForcedSafetyFixture();
    const forcedEvent = fixture.events[0];
    const firstOrdinaryEvent = fixture.events[1];

    expect(forcedEvent?.definitionId).toBe("forced-oversized-truce-separation-4");
    expect(forcedEvent?.resolutionMode).toBe("standard");
    expect(firstOrdinaryEvent?.resolutionMode).toBe("safety");
    expect(firstOrdinaryEvent?.changes.some((change) => change.type === "eliminate-tribute")).toBe(
      true,
    );

    /*
     * Forced events count toward the ordinary round target. They extend the
     * target only when the number of structurally required events is larger.
     */
    expect(fixture.events).toHaveLength(getRoundEventTargetCount(fixture.state.tributes.length));

    const forcedParticipantIds = new Set(forcedEvent?.participantTributeIds ?? []);

    for (const event of fixture.events.slice(1)) {
      for (const tributeId of event.participantTributeIds) {
        expect(forcedParticipantIds.has(tributeId)).toBe(false);
      }
    }

    const forcedItemInstanceIds = new Set(getCommittedItemInstanceIds(forcedEvent?.changes ?? []));

    expect(forcedItemInstanceIds.size).toBeGreaterThan(0);

    const laterItemInstanceIds = new Set(
      fixture.events.slice(1).flatMap((event) => getCommittedItemInstanceIds(event.changes)),
    );

    for (const itemInstanceId of forcedItemInstanceIds) {
      expect(laterItemInstanceIds.has(itemInstanceId)).toBe(false);
    }

    expect(sequenceRoundEvents(createForcedSafetyGame(fixture.seed), NEXT_ROUND)).toEqual(
      fixture.events,
    );
  }, 60_000);
});
