// Generated by implement-phase-5-5.sh
import { describe, expect, it } from "vitest";

import {
  sequenceRoundEvents,
  type SequenceRoundEventsOptions,
} from "~/game/engine/event-sequencer";
import { createSeededRandom } from "~/game/engine/random";
import { createRoundSeed } from "~/game/engine/rounds";
import {
  createSelectorTestContext,
  createSelectorTestDefinition,
  createSelectorTestTributes,
} from "~/game/events/authoring/testing/selector-test-fixtures";
import type { EventDefinition, EventRecoveryTarget } from "~/game/events/event-schema";
import { createStatusEffectInstance } from "~/game/statuses/status-engine";
import type { StatusEffectId } from "~/game/statuses/status-schema";
import type {
  GameState,
  GameTribute,
  ResolvedEvent,
  RoundReference,
  Truce,
} from "~/game/types/game-state";

const DAY_TWO = {
  day: 2,
  period: "day",
} as const satisfies RoundReference;

interface ControlledRoundOptions {
  definitions: readonly EventDefinition[];
  targetEventCount: number;
}

function sequenceControlledRound(
  state: GameState,
  { definitions, targetEventCount }: ControlledRoundOptions,
): ResolvedEvent[] {
  const options: SequenceRoundEventsOptions = {
    definitions,
    targetEventCount,
  };

  return sequenceRoundEvents(state, DAY_TWO, new Set<string>(), options);
}

function createControlledState({
  seed,
  tributeCount = 6,
  tributes,
  stateOverrides = {},
}: {
  seed: string;
  tributeCount?: number;
  tributes?: readonly GameTribute[];
  stateOverrides?: Partial<GameState>;
}): GameState {
  return createSelectorTestContext({
    seed,
    tributeCount,
    ...(tributes ? { tributes } : {}),
    round: DAY_TWO,
    stateOverrides,
  }).state;
}

function createSoloDefinition(
  id: string,
  options: Partial<Parameters<typeof createSelectorTestDefinition>[0]> = {},
): EventDefinition {
  return createSelectorTestDefinition({
    id,
    participantCount: 1,
    ...options,
  });
}

function createPairDefinition(
  id: string,
  options: Partial<Parameters<typeof createSelectorTestDefinition>[0]> = {},
): EventDefinition {
  return createSelectorTestDefinition({
    id,
    participantCount: 2,
    ...options,
  });
}

function createRecoveryDefinition(id: string, target: EventRecoveryTarget): EventDefinition {
  return createSoloDefinition(id, {
    recoveryProfile: {
      targets: [target],
    },
  });
}

function withStatus(
  tribute: GameTribute,
  statusId: StatusEffectId,
  severity: 1 | 2 | 3,
  sourceId: string,
): GameTribute {
  return {
    ...tribute,
    statuses: [
      ...tribute.statuses,
      createStatusEffectInstance(sourceId, tribute.id, statusId, severity, DAY_TWO),
    ],
  };
}

function createHistoryEvent({
  definitionId,
  round,
  eventIndex,
}: {
  definitionId: string;
  round: RoundReference;
  eventIndex: number;
}): ResolvedEvent {
  return {
    id: [round.period, round.day, eventIndex, definitionId].join("-"),
    definitionId,
    kind: "primary",
    resolutionMode: "standard",
    round: { ...round },
    participantTributeIds: [],
    text: `${definitionId} occurred previously.`,
    changes: [],
  };
}

describe("Phase 5.5 later-Day interaction preference", () => {
  it("applies the moderate pair bonus through the full ordinary sequencer", () => {
    const seed = "phase-5-5-pair-10";
    const draw = createSeededRandom(createRoundSeed(seed, DAY_TWO))();
    const soloBoundaryWithShapeWeights = 0.8 / (0.8 + 1.1);

    /*
     * This draw would select the first definition under equal 1:1 weights,
     * but falls beyond the later-Day solo boundary once the pair bonus applies.
     */
    expect(draw).toBeGreaterThan(soloBoundaryWithShapeWeights);
    expect(draw).toBeLessThan(0.5);

    const solo = createSoloDefinition("later-day-weighted-solo");
    const pair = createPairDefinition("later-day-weighted-pair");
    const state = createControlledState({
      seed,
      tributeCount: 4,
    });

    const events = sequenceControlledRound(state, {
      definitions: [solo, pair],
      targetEventCount: 1,
    });

    expect(events).toHaveLength(1);
    expect(events[0]?.definitionId).toBe(pair.id);
    expect(events[0]?.participantTributeIds).toHaveLength(2);
  });

  it("lets urgent solo recovery override the moderate pair preference", () => {
    const seed = "phase-5-5-recovery-9";
    const draw = createSeededRandom(createRoundSeed(seed, DAY_TWO))();
    const soloBoundaryWithoutRecovery = 0.8 / (0.8 + 1.1);
    const urgentSoloBoundary = 4.8 / (4.8 + 1.1);

    expect(draw).toBeGreaterThan(soloBoundaryWithoutRecovery);
    expect(draw).toBeLessThan(urgentSoloBoundary);

    const tributes = createSelectorTestTributes(4).map((tribute) =>
      withStatus(tribute, "injured", 3, "phase-5-5-urgent-injury"),
    );
    const urgentSolo = createRecoveryDefinition("urgent-solo-treatment", {
      kind: "status",
      roleId: "participants",
      statusIds: ["injured"],
    });
    const genericPair = createPairDefinition("generic-pair-interaction");
    const state = createControlledState({
      seed,
      tributes,
    });

    const events = sequenceControlledRound(state, {
      definitions: [urgentSolo, genericPair],
      targetEventCount: 1,
    });

    expect(events[0]?.definitionId).toBe(urgentSolo.id);
    expect(events[0]?.participantTributeIds).toHaveLength(1);
  });

  it("prioritizes water recovery while thirst is active", () => {
    const tributes = createSelectorTestTributes(4).map((tribute) =>
      withStatus(tribute, "thirsty", 3, "phase-5-5-active-thirst"),
    );
    const inactiveTreatment = createRecoveryDefinition("inactive-injury-treatment", {
      kind: "status",
      roleId: "participants",
      statusIds: ["injured"],
    });
    const activeWaterRecovery = createRecoveryDefinition("active-water-recovery", {
      kind: "survival-need",
      roleId: "participants",
      need: "water",
    });
    const state = createControlledState({
      seed: "phase-5-5-recovery-9",
      tributes,
    });

    const events = sequenceControlledRound(state, {
      definitions: [inactiveTreatment, activeWaterRecovery],
      targetEventCount: 1,
    });

    expect(events[0]?.definitionId).toBe(activeWaterRecovery.id);
  });

  it("prioritizes injury treatment while injury is active", () => {
    const tributes = createSelectorTestTributes(4).map((tribute) =>
      withStatus(tribute, "injured", 3, "phase-5-5-active-injury"),
    );
    const inactiveWaterRecovery = createRecoveryDefinition("inactive-water-recovery", {
      kind: "survival-need",
      roleId: "participants",
      need: "water",
    });
    const activeTreatment = createRecoveryDefinition("active-injury-treatment", {
      kind: "status",
      roleId: "participants",
      statusIds: ["injured"],
    });
    const state = createControlledState({
      seed: "phase-5-5-recovery-9",
      tributes,
    });

    const events = sequenceControlledRound(state, {
      definitions: [inactiveWaterRecovery, activeTreatment],
      targetEventCount: 1,
    });

    expect(events[0]?.definitionId).toBe(activeTreatment.id);
  });
});

describe("Phase 5.5 coverage and low-population completion", () => {
  it("completes a solo-only round without repeating definitions", () => {
    const definitions = [
      createSoloDefinition("solo-only-a"),
      createSoloDefinition("solo-only-b"),
      createSoloDefinition("solo-only-c"),
    ];
    const state = createControlledState({
      seed: "phase-5-5-solo-only",
      tributeCount: 3,
    });

    const events = sequenceControlledRound(state, {
      definitions,
      targetEventCount: 3,
    });

    expect(events).toHaveLength(3);
    expect(new Set(events.map((event) => event.definitionId))).toEqual(
      new Set(definitions.map((definition) => definition.id)),
    );
    expect(new Set(events.flatMap((event) => event.participantTributeIds)).size).toBe(3);
  });

  it("rejects a high-weight group event that would consume later slots", () => {
    const unsafeGroup = createSelectorTestDefinition({
      id: "coverage-unsafe-group",
      participantCount: 4,
      baseWeight: 100,
    });
    const safePair = createPairDefinition("coverage-safe-pair");
    const safeSolo = createSoloDefinition("coverage-safe-solo");
    const state = createControlledState({
      seed: "phase-5-5-pair-10",
      tributeCount: 4,
    });

    const events = sequenceControlledRound(state, {
      definitions: [unsafeGroup, safePair, safeSolo],
      targetEventCount: 2,
    });

    expect(events).toHaveLength(2);
    expect(events[0]?.definitionId).toBe(safePair.id);
    expect(events.some((event) => event.definitionId === unsafeGroup.id)).toBe(false);
  });

  it("falls back to the feasible pool when no event can preserve every slot", () => {
    const unavoidablePair = createPairDefinition("low-population-unavoidable-pair");
    const state = createControlledState({
      seed: "phase-5-5-low-population",
      tributeCount: 2,
    });

    const events = sequenceControlledRound(state, {
      definitions: [unavoidablePair],
      targetEventCount: 2,
    });

    expect(events).toHaveLength(1);
    expect(events[0]?.definitionId).toBe(unavoidablePair.id);
    expect(events[0]?.participantTributeIds).toHaveLength(2);
  });
});

describe("Phase 5.5 repetition-cycle integration", () => {
  it("uses distinct definitions while unused options remain", () => {
    const first = createSoloDefinition("round-unique-a");
    const second = createSoloDefinition("round-unique-b");
    const state = createControlledState({
      seed: "phase-5-5-round-uniqueness",
      tributeCount: 2,
    });

    const events = sequenceControlledRound(state, {
      definitions: [first, second],
      targetEventCount: 2,
    });

    expect(events).toHaveLength(2);
    expect(new Set(events.map((event) => event.definitionId))).toEqual(
      new Set([first.id, second.id]),
    );
  });

  it("resets the cycle when every selectable definition was already used", () => {
    const first = createSoloDefinition("cycle-reset-a");
    const second = createSoloDefinition("cycle-reset-b");
    const history = [
      createHistoryEvent({
        definitionId: first.id,
        round: {
          day: 1,
          period: "night",
        },
        eventIndex: 0,
      }),
      createHistoryEvent({
        definitionId: second.id,
        round: DAY_TWO,
        eventIndex: 0,
      }),
    ];
    const state = createControlledState({
      seed: "phase-5-5-cycle-reset",
      tributeCount: 2,
      stateOverrides: {
        eventHistory: history,
      },
    });

    const events = sequenceControlledRound(state, {
      definitions: [first, second],
      targetEventCount: 2,
    });

    expect(events).toHaveLength(2);
    expect(new Set(events.map((event) => event.definitionId))).toEqual(
      new Set([first.id, second.id]),
    );
  });

  it("reconstructs the active cycle from canonical planning order", () => {
    const first = createSoloDefinition("cycle-history-a");
    const second = createSoloDefinition("cycle-history-b");

    /*
     * Canonical order is A, B, A even though presentation order is shuffled.
     * The repeated A begins a fresh cycle, so B must be the unused candidate.
     */
    const oldestA = createHistoryEvent({
      definitionId: first.id,
      round: {
        day: 1,
        period: "night",
      },
      eventIndex: 0,
    });
    const middleB = createHistoryEvent({
      definitionId: second.id,
      round: DAY_TWO,
      eventIndex: 0,
    });
    const newestA = createHistoryEvent({
      definitionId: first.id,
      round: DAY_TWO,
      eventIndex: 1,
    });
    const state = createControlledState({
      seed: "phase-5-5-cycle-reconstruction",
      tributeCount: 2,
      stateOverrides: {
        eventHistory: [newestA, oldestA, middleB],
      },
    });

    const events = sequenceControlledRound(state, {
      definitions: [first, second],
      targetEventCount: 1,
    });

    expect(events[0]?.definitionId).toBe(second.id);
  });
});

describe("Phase 5.5 lifecycle and determinism integration", () => {
  it("keeps forced truce separation before an ordinary controlled event", () => {
    const tributes = createSelectorTestTributes(6);
    const oversizedTruce: Truce = {
      id: "phase-5-5-oversized-truce",
      kind: "standard",
      tributeIds: tributes.slice(0, 2).map((tribute) => tribute.id),
      createdRound: {
        day: 1,
        period: "night",
      },
      expiresAfterRound: null,
    };
    const ordinary = createSoloDefinition("ordinary-after-forced-separation");
    const state = createControlledState({
      seed: "phase-5-5-forced-truce",
      tributes,
      stateOverrides: {
        truces: [oversizedTruce],
      },
    });

    const events = sequenceControlledRound(state, {
      definitions: [ordinary],
      targetEventCount: 2,
    });

    expect(events).toHaveLength(2);
    expect(events[0]?.definitionId).toBe("forced-oversized-truce-separation-2");
    expect(events[1]?.definitionId).toBe(ordinary.id);

    const separatedTributeIds = new Set(oversizedTruce.tributeIds);

    expect(
      events[1]?.participantTributeIds.every((tributeId) => !separatedTributeIds.has(tributeId)),
    ).toBe(true);
  });

  it("reproduces selected definitions, participants, and order for one seed", () => {
    const definitions = [
      createSoloDefinition("deterministic-solo"),
      createPairDefinition("deterministic-pair"),
      createSelectorTestDefinition({
        id: "deterministic-trio",
        participantCount: 3,
      }),
    ];
    const state = createControlledState({
      seed: "phase-5-5-deterministic-round",
      tributeCount: 6,
    });

    const first = sequenceControlledRound(state, {
      definitions,
      targetEventCount: 3,
    });
    const repeated = sequenceControlledRound(state, {
      definitions,
      targetEventCount: 3,
    });

    expect(repeated).toEqual(first);
    expect(first.map((event) => event.definitionId)).toEqual(
      repeated.map((event) => event.definitionId),
    );
    expect(first.map((event) => event.participantTributeIds)).toEqual(
      repeated.map((event) => event.participantTributeIds),
    );
  });

  it("rejects invalid controlled target counts", () => {
    const state = createControlledState({
      seed: "phase-5-5-invalid-target",
      tributeCount: 2,
    });

    expect(() =>
      sequenceRoundEvents(state, DAY_TWO, new Set<string>(), {
        definitions: [createSoloDefinition("invalid-target-solo")],
        targetEventCount: 0,
      }),
    ).toThrow(/positive integer/i);
  });
});
