// Generated by implement-phase-6.sh
import { describe, expect, it } from "vitest";

import {
  collectEventDistributionMetrics,
  type EventDistributionMetrics,
  type EventDistributionPoolId,
  type EventParticipantShape,
} from "~/game/simulation/event-distribution-metrics";
import { PHASE_6_DISTRIBUTION_BASELINE } from "~/game/simulation/distribution-regression-baseline";
import {
  collectDistributionExperienceMetrics,
  createDistributionRegressionThresholds,
  evaluateDistributionRegressionGuardrails,
  formatDistributionGuardrailFailures,
  PHASE_6_DISTRIBUTION_BATCH,
  type DistributionExperienceMetrics,
} from "~/game/simulation/distribution-regression";
import { simulateGameBatch, type SimulationRun } from "~/game/simulation/simulation-runner";

interface MutableShapeMetric {
  selections: number;
  share: number;
}

interface MutableEventMetric {
  appearanceRate: number;
  participantShapes: Record<EventParticipantShape, number>;
}

interface MutableDefinitionDiagnostics {
  feasible: number;
  selected: number;
}

interface MutablePoolView {
  nonSoloShare: number;
  totalSelections: number;
  participantShapes: Record<EventParticipantShape, MutableShapeMetric>;
  concentration: {
    topFiveSelectionShare: number;
  };
  consecutiveGameOverlap: {
    average: number;
  };
  events: MutableEventMetric[];
  selectionDiagnostics: {
    opportunities: number;
    feasibleByShape: Record<EventParticipantShape, number>;
    definitions: MutableDefinitionDiagnostics[];
  };
}

let cachedRuns: readonly SimulationRun[] | null = null;
let cachedMetrics: EventDistributionMetrics | null = null;
let cachedExperience: DistributionExperienceMetrics | null = null;

function getRuns(): readonly SimulationRun[] {
  cachedRuns ??= simulateGameBatch(PHASE_6_DISTRIBUTION_BATCH);

  return cachedRuns;
}

function getMetrics(): EventDistributionMetrics {
  cachedMetrics ??= collectEventDistributionMetrics(getRuns());

  return cachedMetrics;
}

function getExperience(): DistributionExperienceMetrics {
  cachedExperience ??= collectDistributionExperienceMetrics(getRuns());

  return cachedExperience;
}

function cloneMetrics(): EventDistributionMetrics {
  return structuredClone(getMetrics());
}

function getMutablePool(
  metrics: EventDistributionMetrics,
  gameSize: "half-game" | "full-game",
  poolId: EventDistributionPoolId,
): MutablePoolView {
  return metrics.gameSizes[gameSize].pools[poolId] as unknown as MutablePoolView;
}

function getFailureIds(
  metrics: EventDistributionMetrics,
  experience = getExperience(),
): readonly string[] {
  return evaluateDistributionRegressionGuardrails({
    metrics,
    experience,
    baseline: PHASE_6_DISTRIBUTION_BASELINE,
  })
    .filter((result) => !result.passed)
    .map((result) => result.id);
}

describe("Phase 6 distribution regression safeguards", () => {
  it("keeps the deterministic event experience inside its tolerant guardrails", () => {
    const results = evaluateDistributionRegressionGuardrails({
      metrics: getMetrics(),
      experience: getExperience(),
      baseline: PHASE_6_DISTRIBUTION_BASELINE,
    });
    const failures = results.filter((result) => !result.passed);

    if (failures.length > 0) {
      throw new Error(formatDistributionGuardrailFailures(failures));
    }

    expect(failures).toEqual([]);
  }, 120_000);

  it("fails when Cornucopia selection regresses to solo events", () => {
    const metrics = cloneMetrics();

    for (const gameSize of ["half-game", "full-game"] as const) {
      const pool = getMutablePool(metrics, gameSize, "bloodbath-cornucopia");

      pool.nonSoloShare = 0;
      pool.participantShapes.solo.selections = pool.totalSelections;
      pool.participantShapes.solo.share = 1;

      for (const shape of ["pair", "trio", "group-four-plus"] as const) {
        pool.participantShapes[shape].selections = 0;
        pool.participantShapes[shape].share = 0;
      }
    }

    expect(getFailureIds(metrics)).toEqual(
      expect.arrayContaining(["half-game:cornucopia:non-solo", "full-game:cornucopia:non-solo"]),
    );
  });

  it("fails when a small Cornucopia set dominates", () => {
    const metrics = cloneMetrics();
    const pool = getMutablePool(metrics, "full-game", "bloodbath-cornucopia");

    pool.concentration.topFiveSelectionShare = 1;

    if (pool.events[0]) {
      pool.events[0].appearanceRate = 1;
    }

    expect(getFailureIds(metrics)).toEqual(
      expect.arrayContaining([
        "full-game:cornucopia:definition-appearance",
        "full-game:cornucopia:top-five-concentration",
      ]),
    );
  });

  it("fails when expanded fleeing participant shapes disappear", () => {
    const metrics = cloneMetrics();
    const pool = getMutablePool(metrics, "half-game", "bloodbath-flee");

    for (const shape of ["pair", "trio", "group-four-plus"] as const) {
      pool.participantShapes[shape].selections = 0;
      pool.selectionDiagnostics.feasibleByShape[shape] = pool.selectionDiagnostics.opportunities;
    }

    expect(getFailureIds(metrics)).toEqual(
      expect.arrayContaining([
        "half-game:flee:pair",
        "half-game:flee:trio",
        "half-game:flee:group-four-plus",
      ]),
    );
  });

  it("treats a rarely feasible fleeing shape as informational", () => {
    const metrics = cloneMetrics();
    const pool = getMutablePool(metrics, "half-game", "bloodbath-flee");

    pool.participantShapes["group-four-plus"].selections = 0;
    pool.selectionDiagnostics.feasibleByShape["group-four-plus"] = 0;

    expect(getFailureIds(metrics)).not.toContain("half-game:flee:group-four-plus");
  });

  it("fails when a frequently feasible definition is never selected", () => {
    const metrics = cloneMetrics();
    const pool = getMutablePool(metrics, "half-game", "bloodbath-cornucopia");

    expect(pool.selectionDiagnostics.definitions.length).toBeGreaterThan(0);

    for (const definition of pool.selectionDiagnostics.definitions) {
      definition.feasible = Math.max(20, pool.selectionDiagnostics.opportunities);
      definition.selected = 0;
    }

    expect(getFailureIds(metrics)).toContain("half-game:cornucopia:feasible-not-ignored");
  });

  it("tolerates movement that remains inside the derived ranges", () => {
    const metrics = cloneMetrics();
    const thresholds = createDistributionRegressionThresholds(PHASE_6_DISTRIBUTION_BASELINE);
    const baseline =
      PHASE_6_DISTRIBUTION_BASELINE.gameSizes["full-game"].pools["bloodbath-cornucopia"];
    const allowed = thresholds.gameSizes["full-game"].pools["bloodbath-cornucopia"];
    const pool = getMutablePool(metrics, "full-game", "bloodbath-cornucopia");

    pool.nonSoloShare = (baseline.nonSoloShare + allowed.minimumNonSoloShare) / 2;
    pool.concentration.topFiveSelectionShare =
      (baseline.topFiveSelectionShare + allowed.maximumTopFiveSelectionShare) / 2;
    pool.consecutiveGameOverlap.average =
      (baseline.consecutiveOverlapAverage + allowed.maximumConsecutiveOverlapAverage) / 2;

    expect(getFailureIds(metrics).filter((id) => id.startsWith("full-game:cornucopia:"))).toEqual(
      [],
    );
  });

  it("prints actionable diagnostics for a failed balance check", () => {
    const metrics = cloneMetrics();
    const pool = getMutablePool(metrics, "half-game", "bloodbath-cornucopia");

    pool.nonSoloShare = 0;

    const failures = evaluateDistributionRegressionGuardrails({
      metrics,
      experience: getExperience(),
      baseline: PHASE_6_DISTRIBUTION_BASELINE,
    }).filter((result) => !result.passed);
    const output = formatDistributionGuardrailFailures(failures);

    expect(output).toContain("Game size: half-game");
    expect(output).toContain("Event pool: bloodbath-cornucopia");
    expect(output).toContain("Participant shape:");
    expect(output).toContain("Actual value:");
    expect(output).toContain("Expected range:");
    expect(output).toContain("Most selected definitions:");
    expect(output).toContain("Most frequently feasible but rejected definitions:");
    expect(output).toContain("Common rejection reasons:");
  });
});
