// Generated by implement-phase-6.sh
import { EVENT_CATALOGUE } from "~/game/events/catalogue";
import { ENVIRONMENTAL_EVENTS } from "~/game/events/catalogue/encounters/environmental-events";
import type {
  EventDistributionGameSizeId,
  EventDistributionMetrics,
  EventDistributionPoolId,
  EventDistributionPoolMetric,
  EventParticipantShape,
} from "~/game/simulation/event-distribution-metrics";
import type { SimulationBatchDefinition, SimulationRun } from "~/game/simulation/simulation-runner";

export const PHASE_6_DISTRIBUTION_BATCH = [
  {
    seedPrefix: "phase-6-distribution-half",
    count: 30,
    districtCount: 6,
    captureSelectionDiagnostics: true,
  },
  {
    seedPrefix: "phase-6-distribution-full",
    count: 20,
    districtCount: 12,
    captureSelectionDiagnostics: true,
  },
] as const satisfies readonly SimulationBatchDefinition[];

export interface DistributionExperiencePoolMetric {
  totalSelections: number;
  fatalSelections: number;
  recoverySelections: number;
  statusResolutionSelections: number;
  environmentalFatalSelections: number;
  environmentalFatalSelectionsByDefinition: Readonly<Record<string, number>>;
}

export interface DistributionExperienceGameSizeMetric {
  fleeing: DistributionExperiencePoolMetric;
  laterDay: DistributionExperiencePoolMetric;
}

export interface DistributionExperienceMetrics {
  gameSizes: Readonly<Record<EventDistributionGameSizeId, DistributionExperienceGameSizeMetric>>;
}

export interface DistributionPoolBaseline {
  nonSoloShare: number;
  pairShare: number;
  participantShapeSelections: Readonly<Record<EventParticipantShape, number>>;
  topFiveSelectionShare: number;
  consecutiveOverlapAverage: number;
  averageSelectionsPerGame: number;
  maximumDefinitionAppearanceRate: number;
  maximumSoloDefinitionShare: number;
  frequentlyFeasibleUnselectedShare: number;
}

export interface DistributionExperienceBaseline {
  fleeingFatalSelectionShare: number;
  laterDayRecoverySelectionRate: number;
  laterDayStatusResolutionSelectionRate: number;
  laterDayMaximumEnvironmentalFatalShare: number;
}

export interface DistributionRegressionGameSizeBaseline {
  pools: Readonly<Record<EventDistributionPoolId, DistributionPoolBaseline>>;
  experience: DistributionExperienceBaseline;
}

export interface DistributionRegressionBaseline {
  sample: {
    halfGames: number;
    fullGames: number;
  };
  gameSizes: Readonly<Record<EventDistributionGameSizeId, DistributionRegressionGameSizeBaseline>>;
}

export interface DistributionPoolThresholds {
  minimumNonSoloShare: number;
  minimumPairShare: number;
  maximumTopFiveSelectionShare: number;
  maximumConsecutiveOverlapAverage: number;
  maximumDefinitionAppearanceRate: number;
  maximumSoloDefinitionShare: number;
  maximumFrequentlyFeasibleUnselectedShare: number;
}

export interface DistributionExperienceThresholds {
  minimumFleeingFatalSelectionShare: number;
  maximumFleeingFatalSelectionShare: number;
  minimumLaterDayRecoverySelectionRate: number;
  minimumLaterDayStatusResolutionSelectionRate: number;
  maximumLaterDayEnvironmentalFatalShare: number;
}

export interface DistributionRegressionGameSizeThresholds {
  pools: Readonly<Record<EventDistributionPoolId, DistributionPoolThresholds>>;
  experience: DistributionExperienceThresholds;
}

export interface DistributionRegressionThresholds {
  gameSizes: Readonly<
    Record<EventDistributionGameSizeId, DistributionRegressionGameSizeThresholds>
  >;
}

export interface DistributionGuardrailDiagnostics {
  mostSelectedDefinitions: readonly string[];
  frequentlyFeasibleButRejectedDefinitions: readonly string[];
  commonRejectionReasons: readonly string[];
}

export interface DistributionGuardrailResult {
  id: string;
  label: string;
  passed: boolean;
  gameSize: EventDistributionGameSizeId;
  poolId: EventDistributionPoolId;
  participantShape: EventParticipantShape | "all";
  actual: string;
  expected: string;
  diagnostics: DistributionGuardrailDiagnostics;
}

const ENVIRONMENTAL_EVENT_IDS = new Set([
  ...ENVIRONMENTAL_EVENTS.map((definition) => definition.id),
  ...EVENT_CATALOGUE.filter((definition) =>
    (definition.tags as readonly string[]).includes("environment"),
  ).map((definition) => definition.id),
]);

const TESTED_POOL_IDS = [
  "bloodbath-cornucopia",
  "bloodbath-flee",
  "later-day",
] as const satisfies readonly EventDistributionPoolId[];

function divide(numerator: number, denominator: number): number {
  return denominator === 0 ? 0 : numerator / denominator;
}

function formatRate(value: number): string {
  return `${(value * 100).toFixed(1)}%`;
}

function createEmptyExperiencePool(): DistributionExperiencePoolMetric {
  return {
    totalSelections: 0,
    fatalSelections: 0,
    recoverySelections: 0,
    statusResolutionSelections: 0,
    environmentalFatalSelections: 0,
    environmentalFatalSelectionsByDefinition: {},
  };
}

function getGameSizeId(run: SimulationRun): EventDistributionGameSizeId {
  return run.districtCount === 6 ? "half-game" : "full-game";
}

function hasElimination(event: SimulationRun["state"]["eventHistory"][number]): boolean {
  return event.changes.some((change) => change.type === "eliminate-tribute");
}

function incrementDefinitionCount(counts: Record<string, number>, definitionId: string): void {
  counts[definitionId] = (counts[definitionId] ?? 0) + 1;
}

export function collectDistributionExperienceMetrics(
  runs: readonly SimulationRun[],
): DistributionExperienceMetrics {
  const mutable = {
    "half-game": {
      fleeing: createEmptyExperiencePool(),
      laterDay: createEmptyExperiencePool(),
    },
    "full-game": {
      fleeing: createEmptyExperiencePool(),
      laterDay: createEmptyExperiencePool(),
    },
  } satisfies Record<EventDistributionGameSizeId, DistributionExperienceGameSizeMetric>;

  for (const run of runs) {
    const gameSize = mutable[getGameSizeId(run)];

    for (const event of run.state.eventHistory) {
      if (event.kind !== "primary") {
        continue;
      }

      if (event.feedGroup === "bloodbath-flee") {
        gameSize.fleeing.totalSelections += 1;

        if (hasElimination(event)) {
          gameSize.fleeing.fatalSelections += 1;
        }

        continue;
      }

      if (event.round.day < 2 || event.round.period !== "day") {
        continue;
      }

      gameSize.laterDay.totalSelections += 1;

      const resolvesNeed = event.changes.some((change) => change.type === "satisfy-survival-need");
      const resolvesStatus = event.changes.some((change) => change.type === "remove-status");

      if (resolvesNeed || resolvesStatus) {
        gameSize.laterDay.recoverySelections += 1;
      }

      if (resolvesStatus) {
        gameSize.laterDay.statusResolutionSelections += 1;
      }

      if (ENVIRONMENTAL_EVENT_IDS.has(event.definitionId) && hasElimination(event)) {
        gameSize.laterDay.environmentalFatalSelections += 1;
        incrementDefinitionCount(
          gameSize.laterDay.environmentalFatalSelectionsByDefinition as Record<string, number>,
          event.definitionId,
        );
      }
    }
  }

  return {
    gameSizes: mutable,
  };
}

function getMaximumDefinitionAppearanceRate(pool: EventDistributionPoolMetric): number {
  return Math.max(0, ...pool.events.map((event) => event.appearanceRate));
}

function getMaximumSoloDefinitionShare(pool: EventDistributionPoolMetric): number {
  const soloSelections = pool.participantShapes.solo.selections;

  return Math.max(
    0,
    ...pool.events.map((event) => divide(event.participantShapes.solo, soloSelections)),
  );
}

function createPoolBaseline(pool: EventDistributionPoolMetric): DistributionPoolBaseline {
  return {
    nonSoloShare: pool.nonSoloShare,
    pairShare: divide(pool.participantShapes.pair.selections, pool.totalSelections),
    participantShapeSelections: {
      solo: pool.participantShapes.solo.selections,
      pair: pool.participantShapes.pair.selections,
      trio: pool.participantShapes.trio.selections,
      "group-four-plus": pool.participantShapes["group-four-plus"].selections,
    },
    topFiveSelectionShare: pool.concentration.topFiveSelectionShare,
    consecutiveOverlapAverage: pool.consecutiveGameOverlap.average,
    averageSelectionsPerGame: pool.averageSelectionsPerGame,
    maximumDefinitionAppearanceRate: getMaximumDefinitionAppearanceRate(pool),
    maximumSoloDefinitionShare: getMaximumSoloDefinitionShare(pool),
    frequentlyFeasibleUnselectedShare: getFrequentlyFeasibleUnselectedShare(pool),
  };
}

function getMaximumEnvironmentalFatalShare(experience: DistributionExperiencePoolMetric): number {
  return divide(
    Math.max(0, ...Object.values(experience.environmentalFatalSelectionsByDefinition)),
    experience.environmentalFatalSelections,
  );
}

function createGameSizeBaseline(
  metrics: EventDistributionMetrics,
  experience: DistributionExperienceMetrics,
  gameSizeId: EventDistributionGameSizeId,
): DistributionRegressionGameSizeBaseline {
  const pools = metrics.gameSizes[gameSizeId].pools;
  const experienceForSize = experience.gameSizes[gameSizeId];

  return {
    pools: {
      "bloodbath-cornucopia": createPoolBaseline(pools["bloodbath-cornucopia"]),
      "bloodbath-flee": createPoolBaseline(pools["bloodbath-flee"]),
      "later-day": createPoolBaseline(pools["later-day"]),
      night: createPoolBaseline(pools.night),
    },
    experience: {
      fleeingFatalSelectionShare: divide(
        experienceForSize.fleeing.fatalSelections,
        experienceForSize.fleeing.totalSelections,
      ),
      laterDayRecoverySelectionRate: divide(
        experienceForSize.laterDay.recoverySelections,
        experienceForSize.laterDay.totalSelections,
      ),
      laterDayStatusResolutionSelectionRate: divide(
        experienceForSize.laterDay.statusResolutionSelections,
        experienceForSize.laterDay.totalSelections,
      ),
      laterDayMaximumEnvironmentalFatalShare: getMaximumEnvironmentalFatalShare(
        experienceForSize.laterDay,
      ),
    },
  };
}

export function createDistributionRegressionBaseline(
  metrics: EventDistributionMetrics,
  experience: DistributionExperienceMetrics,
): DistributionRegressionBaseline {
  return {
    sample: {
      halfGames: metrics.sample.halfGames,
      fullGames: metrics.sample.fullGames,
    },
    gameSizes: {
      "half-game": createGameSizeBaseline(metrics, experience, "half-game"),
      "full-game": createGameSizeBaseline(metrics, experience, "full-game"),
    },
  };
}

function createPoolThresholds({
  baseline,
  gameSizeId,
  poolId,
}: {
  baseline: DistributionPoolBaseline;
  gameSizeId: EventDistributionGameSizeId;
  poolId: EventDistributionPoolId;
}): DistributionPoolThresholds {
  const minimumNonSoloFloor =
    poolId === "bloodbath-cornucopia"
      ? gameSizeId === "half-game"
        ? 0.5
        : 0.55
      : poolId === "bloodbath-flee"
        ? gameSizeId === "half-game"
          ? 0.45
          : 0.5
        : poolId === "later-day"
          ? 0.2
          : 0;

  const minimumPairFloor = poolId === "later-day" ? 0.1 : 0;

  return {
    minimumNonSoloShare: Math.max(minimumNonSoloFloor, baseline.nonSoloShare - 0.1),
    minimumPairShare: Math.max(minimumPairFloor, baseline.pairShare - 0.075),
    maximumTopFiveSelectionShare: Math.min(0.9, baseline.topFiveSelectionShare + 0.1),
    maximumConsecutiveOverlapAverage: Math.max(
      baseline.consecutiveOverlapAverage + 0.75,
      Math.min(baseline.averageSelectionsPerGame * 0.98, baseline.consecutiveOverlapAverage + 1.5),
    ),
    maximumDefinitionAppearanceRate: Math.min(0.9, baseline.maximumDefinitionAppearanceRate + 0.1),
    maximumSoloDefinitionShare: Math.min(0.6, baseline.maximumSoloDefinitionShare + 0.15),
    maximumFrequentlyFeasibleUnselectedShare: Math.min(
      0.5,
      Math.max(0.2, baseline.frequentlyFeasibleUnselectedShare + 0.1),
    ),
  };
}

function createGameSizeThresholds(
  baseline: DistributionRegressionGameSizeBaseline,
  gameSizeId: EventDistributionGameSizeId,
): DistributionRegressionGameSizeThresholds {
  const fleeingFatalBaseline = baseline.experience.fleeingFatalSelectionShare;

  return {
    pools: {
      "bloodbath-cornucopia": createPoolThresholds({
        baseline: baseline.pools["bloodbath-cornucopia"],
        gameSizeId,
        poolId: "bloodbath-cornucopia",
      }),
      "bloodbath-flee": createPoolThresholds({
        baseline: baseline.pools["bloodbath-flee"],
        gameSizeId,
        poolId: "bloodbath-flee",
      }),
      "later-day": createPoolThresholds({
        baseline: baseline.pools["later-day"],
        gameSizeId,
        poolId: "later-day",
      }),
      night: createPoolThresholds({
        baseline: baseline.pools.night,
        gameSizeId,
        poolId: "night",
      }),
    },
    experience: {
      minimumFleeingFatalSelectionShare: Math.max(0, fleeingFatalBaseline - 0.1),
      maximumFleeingFatalSelectionShare: Math.min(0.35, Math.max(0.1, fleeingFatalBaseline + 0.1)),
      minimumLaterDayRecoverySelectionRate: Math.max(
        0.02,
        baseline.experience.laterDayRecoverySelectionRate * 0.5,
      ),
      minimumLaterDayStatusResolutionSelectionRate: Math.max(
        0.0025,
        baseline.experience.laterDayStatusResolutionSelectionRate * 0.4,
      ),
      maximumLaterDayEnvironmentalFatalShare: Math.min(
        0.7,
        baseline.experience.laterDayMaximumEnvironmentalFatalShare + 0.15,
      ),
    },
  };
}

export function createDistributionRegressionThresholds(
  baseline: DistributionRegressionBaseline,
): DistributionRegressionThresholds {
  return {
    gameSizes: {
      "half-game": createGameSizeThresholds(baseline.gameSizes["half-game"], "half-game"),
      "full-game": createGameSizeThresholds(baseline.gameSizes["full-game"], "full-game"),
    },
  };
}

function getFrequentFeasibilityMinimum(pool: EventDistributionPoolMetric): number {
  return Math.max(10, Math.ceil(pool.selectionDiagnostics.opportunities * 0.15));
}
function getShapeCoverageMinimum(pool: EventDistributionPoolMetric): number {
  return Math.max(20, Math.ceil(pool.selectionDiagnostics.opportunities * 0.25));
}

function getFrequentlyFeasibleDefinitions(pool: EventDistributionPoolMetric) {
  const minimumFeasible = getFrequentFeasibilityMinimum(pool);

  return pool.selectionDiagnostics.definitions.filter(
    (definition) => definition.feasible >= minimumFeasible,
  );
}

function getFrequentlyFeasibleUnselectedDefinitions(
  pool: EventDistributionPoolMetric,
): readonly string[] {
  return getFrequentlyFeasibleDefinitions(pool)
    .filter((definition) => definition.selected === 0)
    .map((definition) => definition.definitionId)
    .sort();
}

function getFrequentlyFeasibleUnselectedShare(pool: EventDistributionPoolMetric): number {
  const frequentlyFeasible = getFrequentlyFeasibleDefinitions(pool);

  return divide(
    frequentlyFeasible.filter((definition) => definition.selected === 0).length,
    frequentlyFeasible.length,
  );
}

function createDiagnostics(pool: EventDistributionPoolMetric): DistributionGuardrailDiagnostics {
  const mostSelectedDefinitions = pool.events
    .slice(0, 5)
    .map(
      (event) =>
        `${event.definitionId}: ${event.selections} selections ` +
        `(${formatRate(event.selectionShare)})`,
    );

  const frequentlyFeasibleButRejectedDefinitions = pool.selectionDiagnostics.definitions
    .filter((definition) => definition.feasible > 0)
    .sort(
      (first, second) =>
        second.feasible - second.selected - (first.feasible - first.selected) ||
        second.feasible - first.feasible ||
        first.definitionId.localeCompare(second.definitionId),
    )
    .slice(0, 5)
    .map(
      (definition) =>
        `${definition.definitionId}: ${definition.feasible} feasible / ` +
        `${definition.selected} selected`,
    );

  const rejectionCounts = new Map<string, number>();

  for (const definition of pool.selectionDiagnostics.definitions) {
    for (const [reason, count] of Object.entries(definition.rejectionCounts)) {
      rejectionCounts.set(reason, (rejectionCounts.get(reason) ?? 0) + count);
    }
  }

  const commonRejectionReasons = [...rejectionCounts.entries()]
    .filter(([, count]) => count > 0)
    .sort(
      ([firstReason, firstCount], [secondReason, secondCount]) =>
        secondCount - firstCount || firstReason.localeCompare(secondReason),
    )
    .slice(0, 5)
    .map(([reason, count]) => `${reason}: ${count}`);

  return {
    mostSelectedDefinitions,
    frequentlyFeasibleButRejectedDefinitions,
    commonRejectionReasons,
  };
}

function createResult({
  id,
  label,
  passed,
  gameSize,
  poolId,
  participantShape = "all",
  actual,
  expected,
  pool,
}: {
  id: string;
  label: string;
  passed: boolean;
  gameSize: EventDistributionGameSizeId;
  poolId: EventDistributionPoolId;
  participantShape?: EventParticipantShape | "all";
  actual: string;
  expected: string;
  pool: EventDistributionPoolMetric;
}): DistributionGuardrailResult {
  return {
    id,
    label,
    passed,
    gameSize,
    poolId,
    participantShape,
    actual,
    expected,
    diagnostics: createDiagnostics(pool),
  };
}

function evaluateCornucopia({
  gameSizeId,
  pool,
  thresholds,
}: {
  gameSizeId: EventDistributionGameSizeId;
  pool: EventDistributionPoolMetric;
  thresholds: DistributionPoolThresholds;
}): DistributionGuardrailResult[] {
  const frequentlyFeasible = getFrequentlyFeasibleDefinitions(pool);
  const frequentlyFeasibleUnselected = getFrequentlyFeasibleUnselectedDefinitions(pool);
  const frequentlyFeasibleUnselectedShare = getFrequentlyFeasibleUnselectedShare(pool);
  const maximumAppearanceRate = getMaximumDefinitionAppearanceRate(pool);

  return [
    createResult({
      id: `${gameSizeId}:cornucopia:non-solo`,
      label: "Cornucopia non-solo share",
      passed: pool.nonSoloShare >= thresholds.minimumNonSoloShare,
      gameSize: gameSizeId,
      poolId: "bloodbath-cornucopia",
      actual: formatRate(pool.nonSoloShare),
      expected: `at least ${formatRate(thresholds.minimumNonSoloShare)}`,
      pool,
    }),
    createResult({
      id: `${gameSizeId}:cornucopia:definition-appearance`,
      label: "Cornucopia definition appearance",
      passed: maximumAppearanceRate <= thresholds.maximumDefinitionAppearanceRate,
      gameSize: gameSizeId,
      poolId: "bloodbath-cornucopia",
      actual: formatRate(maximumAppearanceRate),
      expected: `no definition above ${formatRate(thresholds.maximumDefinitionAppearanceRate)}`,
      pool,
    }),
    createResult({
      id: `${gameSizeId}:cornucopia:top-five-concentration`,
      label: "Cornucopia top-five concentration",
      passed: pool.concentration.topFiveSelectionShare <= thresholds.maximumTopFiveSelectionShare,
      gameSize: gameSizeId,
      poolId: "bloodbath-cornucopia",
      actual: formatRate(pool.concentration.topFiveSelectionShare),
      expected: `no more than ${formatRate(thresholds.maximumTopFiveSelectionShare)}`,
      pool,
    }),
    createResult({
      id: `${gameSizeId}:cornucopia:consecutive-overlap`,
      label: "Cornucopia consecutive-game overlap",
      passed: pool.consecutiveGameOverlap.average <= thresholds.maximumConsecutiveOverlapAverage,
      gameSize: gameSizeId,
      poolId: "bloodbath-cornucopia",
      actual: pool.consecutiveGameOverlap.average.toFixed(2),
      expected: `no more than ${thresholds.maximumConsecutiveOverlapAverage.toFixed(2)}`,
      pool,
    }),
    createResult({
      id: `${gameSizeId}:cornucopia:feasible-not-ignored`,
      label: "Frequently feasible Cornucopia definitions are not broadly ignored",
      passed:
        frequentlyFeasibleUnselectedShare <= thresholds.maximumFrequentlyFeasibleUnselectedShare,
      gameSize: gameSizeId,
      poolId: "bloodbath-cornucopia",
      actual:
        `${formatRate(
          frequentlyFeasibleUnselectedShare,
        )} (${frequentlyFeasibleUnselected.length}/${frequentlyFeasible.length})` +
        (frequentlyFeasibleUnselected.length > 0
          ? `: ${frequentlyFeasibleUnselected.join(", ")}`
          : ""),
      expected: `no more than ${formatRate(
        thresholds.maximumFrequentlyFeasibleUnselectedShare,
      )} of frequently feasible definitions ignored`,
      pool,
    }),
  ];
}

function evaluateFleeing({
  gameSizeId,
  pool,
  experience,
  poolThresholds,
  experienceThresholds,
}: {
  gameSizeId: EventDistributionGameSizeId;
  pool: EventDistributionPoolMetric;
  experience: DistributionExperiencePoolMetric;
  poolThresholds: DistributionPoolThresholds;
  experienceThresholds: DistributionExperienceThresholds;
}): DistributionGuardrailResult[] {
  const fatalSelectionShare = divide(experience.fatalSelections, experience.totalSelections);
  const maximumSoloDefinitionShare = getMaximumSoloDefinitionShare(pool);

  return [
    createResult({
      id: `${gameSizeId}:flee:non-solo`,
      label: "Fleeing non-solo share",
      passed: pool.nonSoloShare >= poolThresholds.minimumNonSoloShare,
      gameSize: gameSizeId,
      poolId: "bloodbath-flee",
      actual: formatRate(pool.nonSoloShare),
      expected: `at least ${formatRate(poolThresholds.minimumNonSoloShare)}`,
      pool,
    }),
    ...(["pair", "trio", "group-four-plus"] as const).map((shape): DistributionGuardrailResult => {
      const currentSelections = pool.participantShapes[shape].selections;
      const feasibleOpportunities = pool.selectionDiagnostics.feasibleByShape[shape];
      const minimumFeasibleOpportunities = getShapeCoverageMinimum(pool);
      const selectionIsRequired = feasibleOpportunities >= minimumFeasibleOpportunities;

      return createResult({
        id: `${gameSizeId}:flee:${shape}`,
        label: `Fleeing ${shape} selections`,
        passed: !selectionIsRequired || currentSelections > 0,
        gameSize: gameSizeId,
        poolId: "bloodbath-flee",
        participantShape: shape,
        actual:
          `${currentSelections} selected / ` + `${feasibleOpportunities} feasible opportunities`,
        expected: selectionIsRequired
          ? "at least one selection"
          : `informational; fewer than ${minimumFeasibleOpportunities} feasible opportunities`,
        pool,
      });
    }),
    createResult({
      id: `${gameSizeId}:flee:solo-dominance`,
      label: "No solo fleeing definition dominates",
      passed: maximumSoloDefinitionShare <= poolThresholds.maximumSoloDefinitionShare,
      gameSize: gameSizeId,
      poolId: "bloodbath-flee",
      participantShape: "solo",
      actual: formatRate(maximumSoloDefinitionShare),
      expected: `no more than ${formatRate(
        poolThresholds.maximumSoloDefinitionShare,
      )} of solo fleeing selections`,
      pool,
    }),
    createResult({
      id: `${gameSizeId}:flee:lethality`,
      label: "Fleeing lethality",
      passed:
        fatalSelectionShare >= experienceThresholds.minimumFleeingFatalSelectionShare &&
        fatalSelectionShare <= experienceThresholds.maximumFleeingFatalSelectionShare,
      gameSize: gameSizeId,
      poolId: "bloodbath-flee",
      actual: formatRate(fatalSelectionShare),
      expected: `${formatRate(experienceThresholds.minimumFleeingFatalSelectionShare)}–${formatRate(
        experienceThresholds.maximumFleeingFatalSelectionShare,
      )}`,
      pool,
    }),
  ];
}

function evaluateLaterDay({
  gameSizeId,
  pool,
  experience,
  baseline,
  poolThresholds,
  experienceThresholds,
}: {
  gameSizeId: EventDistributionGameSizeId;
  pool: EventDistributionPoolMetric;
  experience: DistributionExperiencePoolMetric;
  baseline: DistributionPoolBaseline;
  poolThresholds: DistributionPoolThresholds;
  experienceThresholds: DistributionExperienceThresholds;
}): DistributionGuardrailResult[] {
  const pairShare = divide(pool.participantShapes.pair.selections, pool.totalSelections);
  const recoveryRate = divide(experience.recoverySelections, experience.totalSelections);
  const statusResolutionRate = divide(
    experience.statusResolutionSelections,
    experience.totalSelections,
  );
  const maximumEnvironmentalFatalShare = getMaximumEnvironmentalFatalShare(experience);
  const enoughEnvironmentalFatalitiesForConcentration =
    experience.environmentalFatalSelections >= 5;

  return [
    createResult({
      id: `${gameSizeId}:later-day:non-solo`,
      label: "Later-Day non-solo share",
      passed: pool.nonSoloShare >= poolThresholds.minimumNonSoloShare,
      gameSize: gameSizeId,
      poolId: "later-day",
      actual: formatRate(pool.nonSoloShare),
      expected: `at least ${formatRate(poolThresholds.minimumNonSoloShare)}`,
      pool,
    }),
    createResult({
      id: `${gameSizeId}:later-day:pair-share`,
      label: "Later-Day pair share",
      passed: pairShare >= poolThresholds.minimumPairShare,
      gameSize: gameSizeId,
      poolId: "later-day",
      participantShape: "pair",
      actual: formatRate(pairShare),
      expected: `at least ${formatRate(poolThresholds.minimumPairShare)}`,
      pool,
    }),
    ...(["trio", "group-four-plus"] as const).map((shape): DistributionGuardrailResult => {
      const baselineSelections = baseline.participantShapeSelections[shape];
      const currentSelections = pool.participantShapes[shape].selections;
      const feasibleOpportunities = pool.selectionDiagnostics.feasibleByShape[shape];
      const shapeIsEstablished = baselineSelections > 0;
      const minimumFeasibleOpportunities = getShapeCoverageMinimum(pool);
      const selectionIsRequired =
        shapeIsEstablished && feasibleOpportunities >= minimumFeasibleOpportunities;

      return createResult({
        id: `${gameSizeId}:later-day:${shape}`,
        label: `Later-Day ${shape} selections`,
        passed: !selectionIsRequired || currentSelections > 0,
        gameSize: gameSizeId,
        poolId: "later-day",
        participantShape: shape,
        actual:
          `${currentSelections} selected / ` + `${feasibleOpportunities} feasible opportunities`,
        expected: selectionIsRequired
          ? "at least one selection"
          : shapeIsEstablished
            ? `informational; fewer than ${minimumFeasibleOpportunities} feasible opportunities`
            : "informational; accepted baseline had no selections",
        pool,
      });
    }),
    createResult({
      id: `${gameSizeId}:later-day:recovery`,
      label: "Later-Day recovery frequency",
      passed: recoveryRate >= experienceThresholds.minimumLaterDayRecoverySelectionRate,
      gameSize: gameSizeId,
      poolId: "later-day",
      actual: formatRate(recoveryRate),
      expected: `at least ${formatRate(experienceThresholds.minimumLaterDayRecoverySelectionRate)}`,
      pool,
    }),
    createResult({
      id: `${gameSizeId}:later-day:status-resolution`,
      label: "Later-Day status-resolution frequency",
      passed:
        statusResolutionRate >= experienceThresholds.minimumLaterDayStatusResolutionSelectionRate,
      gameSize: gameSizeId,
      poolId: "later-day",
      actual: formatRate(statusResolutionRate),
      expected: `at least ${formatRate(
        experienceThresholds.minimumLaterDayStatusResolutionSelectionRate,
      )}`,
      pool,
    }),
    createResult({
      id: `${gameSizeId}:later-day:environmental-dominance`,
      label: "No environmental death dominates",
      passed:
        !enoughEnvironmentalFatalitiesForConcentration ||
        maximumEnvironmentalFatalShare <=
          experienceThresholds.maximumLaterDayEnvironmentalFatalShare,
      gameSize: gameSizeId,
      poolId: "later-day",
      actual:
        experience.environmentalFatalSelections === 0
          ? "no environmental fatalities"
          : `${formatRate(
              maximumEnvironmentalFatalShare,
            )} across ${experience.environmentalFatalSelections} environmental fatalities`,
      expected:
        experience.environmentalFatalSelections < 5
          ? "informational until at least five environmental fatalities"
          : `no definition above ${formatRate(
              experienceThresholds.maximumLaterDayEnvironmentalFatalShare,
            )}`,
      pool,
    }),
  ];
}

export function evaluateDistributionRegressionGuardrails({
  metrics,
  experience,
  baseline,
}: {
  metrics: EventDistributionMetrics;
  experience: DistributionExperienceMetrics;
  baseline: DistributionRegressionBaseline;
}): DistributionGuardrailResult[] {
  const thresholds = createDistributionRegressionThresholds(baseline);
  const results: DistributionGuardrailResult[] = [];

  for (const gameSizeId of [
    "half-game",
    "full-game",
  ] as const satisfies readonly EventDistributionGameSizeId[]) {
    const pools = metrics.gameSizes[gameSizeId].pools;
    const experienceForSize = experience.gameSizes[gameSizeId];
    const baselineForSize = baseline.gameSizes[gameSizeId];
    const thresholdsForSize = thresholds.gameSizes[gameSizeId];

    results.push(
      ...evaluateCornucopia({
        gameSizeId,
        pool: pools["bloodbath-cornucopia"],
        thresholds: thresholdsForSize.pools["bloodbath-cornucopia"],
      }),
      ...evaluateFleeing({
        gameSizeId,
        pool: pools["bloodbath-flee"],
        experience: experienceForSize.fleeing,
        poolThresholds: thresholdsForSize.pools["bloodbath-flee"],
        experienceThresholds: thresholdsForSize.experience,
      }),
      ...evaluateLaterDay({
        gameSizeId,
        pool: pools["later-day"],
        experience: experienceForSize.laterDay,
        baseline: baselineForSize.pools["later-day"],
        poolThresholds: thresholdsForSize.pools["later-day"],
        experienceThresholds: thresholdsForSize.experience,
      }),
    );
  }

  return results;
}

function formatDiagnosticValues(values: readonly string[]): string {
  return values.length > 0 ? values.join("; ") : "none";
}

export function formatDistributionGuardrailFailures(
  results: readonly DistributionGuardrailResult[],
): string {
  const failures = results.filter((result) => !result.passed);

  if (failures.length === 0) {
    return "All distribution regression guardrails passed.";
  }

  return [
    `Distribution regression failures: ${failures.length}`,
    ...failures.map((failure) =>
      [
        "",
        `[${failure.id}] ${failure.label}`,
        `Game size: ${failure.gameSize}`,
        `Event pool: ${failure.poolId}`,
        `Participant shape: ${failure.participantShape}`,
        `Actual value: ${failure.actual}`,
        `Expected range: ${failure.expected}`,
        `Most selected definitions: ${formatDiagnosticValues(
          failure.diagnostics.mostSelectedDefinitions,
        )}`,
        `Most frequently feasible but rejected definitions: ${formatDiagnosticValues(
          failure.diagnostics.frequentlyFeasibleButRejectedDefinitions,
        )}`,
        `Common rejection reasons: ${formatDiagnosticValues(
          failure.diagnostics.commonRejectionReasons,
        )}`,
      ].join("\n"),
    ),
  ].join("\n");
}

export function getTestedDistributionPoolIds(): readonly EventDistributionPoolId[] {
  return TESTED_POOL_IDS;
}
