// Generated by implement-phase-5-6.sh
import { describe, expect, it } from "vitest";

import {
  collectEventDistributionMetrics,
  EVENT_DISTRIBUTION_GAME_SIZE_IDS,
  EVENT_DISTRIBUTION_POOL_IDS,
  EVENT_PARTICIPANT_SHAPES,
  type EventDistributionGameSizeId,
  type EventDistributionPoolId,
  type EventParticipantShape,
} from "~/game/simulation/event-distribution-metrics";
import {
  simulateGame,
  simulateGameBatch,
  type SimulationRun,
} from "~/game/simulation/simulation-runner";
import type { ResolvedEvent, RoundReference } from "~/game/types/game-state";

const PHASE_5_BATCH = [
  {
    seedPrefix: "phase-5-6-half",
    count: 12,
    districtCount: 6,
    captureSelectionDiagnostics: true,
  },
  {
    seedPrefix: "phase-5-6-full",
    count: 8,
    districtCount: 12,
    captureSelectionDiagnostics: true,
  },
] as const;

const BLOODBATH_POOL_IDS = [
  "bloodbath-cornucopia",
  "bloodbath-flee",
] as const satisfies readonly EventDistributionPoolId[];

const ORDINARY_POOL_IDS = [
  "later-day",
  "night",
] as const satisfies readonly EventDistributionPoolId[];

let cachedRuns: readonly SimulationRun[] | null = null;

function getRuns(): readonly SimulationRun[] {
  cachedRuns ??= simulateGameBatch(PHASE_5_BATCH);

  return cachedRuns;
}

function getPrimaryEvents(run: SimulationRun): ResolvedEvent[] {
  return run.state.eventHistory.filter((event) => event.kind === "primary");
}

function isDayOneDaytime(round: RoundReference): boolean {
  return round.day === 1 && round.period === "day";
}

function getEliminatedTributeIds(events: readonly ResolvedEvent[]): string[] {
  return events.flatMap((event) =>
    event.changes.flatMap((change) =>
      change.type === "eliminate-tribute" ? [change.tributeId] : [],
    ),
  );
}

function getAverage(values: readonly number[]): number {
  if (values.length === 0) {
    throw new Error("Cannot average an empty Phase 5.6 sample.");
  }

  return values.reduce((total, value) => total + value, 0) / values.length;
}

function getRoundKey(round: RoundReference): string {
  return `${round.day}:${round.period}`;
}

function isForcedLifecycleDefinition(definitionId: string): boolean {
  return definitionId.startsWith("amicable-truce-separation-");
}

function createRunSignature(run: SimulationRun): string {
  return JSON.stringify({
    roundsCompleted: run.roundsCompleted,
    victoryOutcome: run.state.victoryOutcome,
    events: run.state.eventHistory.map((event) => ({
      definitionId: event.definitionId,
      kind: event.kind,
      resolutionMode: event.resolutionMode,
      feedGroup: event.feedGroup,
      round: event.round,
      participantTributeIds: event.participantTributeIds,
      eliminatedTributeIds: getEliminatedTributeIds([event]),
    })),
  });
}

function getShapeSelections(runs: readonly SimulationRun[], shape: EventParticipantShape): number {
  const metrics = collectEventDistributionMetrics(runs);

  return EVENT_DISTRIBUTION_GAME_SIZE_IDS.reduce(
    (gameSizeTotal, gameSizeId) =>
      gameSizeTotal +
      EVENT_DISTRIBUTION_POOL_IDS.reduce(
        (poolTotal, poolId) =>
          poolTotal +
          metrics.gameSizes[gameSizeId].pools[poolId].participantShapes[shape].selections,
        0,
      ),
    0,
  );
}

function getPoolDiagnosticTotal(
  runs: readonly SimulationRun[],
  poolId: EventDistributionPoolId,
  selector: (
    diagnostics: ReturnType<
      typeof collectEventDistributionMetrics
    >["gameSizes"][EventDistributionGameSizeId]["pools"][EventDistributionPoolId]["selectionDiagnostics"],
  ) => number,
): number {
  const metrics = collectEventDistributionMetrics(runs);

  return EVENT_DISTRIBUTION_GAME_SIZE_IDS.reduce(
    (total, gameSizeId) =>
      total + selector(metrics.gameSizes[gameSizeId].pools[poolId].selectionDiagnostics),
    0,
  );
}

function getRejectionTotal(
  runs: readonly SimulationRun[],
  poolIds: readonly EventDistributionPoolId[],
  reason: "already-used-definition" | "reservation-blocked" | "fatality-target-stranded",
): number {
  const metrics = collectEventDistributionMetrics(runs);

  return EVENT_DISTRIBUTION_GAME_SIZE_IDS.reduce(
    (gameSizeTotal, gameSizeId) =>
      gameSizeTotal +
      poolIds.reduce((poolTotal, poolId) => {
        const diagnostics = metrics.gameSizes[gameSizeId].pools[poolId].selectionDiagnostics;

        return (
          poolTotal +
          diagnostics.definitions.reduce(
            (definitionTotal, definition) => definitionTotal + definition.rejectionCounts[reason],
            0,
          )
        );
      }, 0),
    0,
  );
}

describe("Phase 5.6 complete-game Bloodbath guardrails", () => {
  it("keeps Cornucopia events before fleeing events and bounds supplemental survivor reuse", () => {
    for (const run of getRuns()) {
      const openingEvents = getPrimaryEvents(run).filter((event) => isDayOneDaytime(event.round));

      expect(openingEvents.length).toBeGreaterThan(0);

      let fleeingHasBegun = false;
      const appearanceCountByTributeId = new Map<string, number>();

      for (const event of openingEvents) {
        if (event.feedGroup === "bloodbath-flee") {
          fleeingHasBegun = true;
        }

        if (event.feedGroup === "bloodbath-cornucopia") {
          expect(fleeingHasBegun).toBe(false);
        }

        expect(["bloodbath-cornucopia", "bloodbath-flee"]).toContain(event.feedGroup);

        const uniqueParticipantTributeIds = [...new Set(event.participantTributeIds)];
        const repeatedParticipantTributeIds = uniqueParticipantTributeIds.filter(
          (tributeId) => (appearanceCountByTributeId.get(tributeId) ?? 0) > 0,
        );

        if (repeatedParticipantTributeIds.length > 0) {
          /*
           * Cornucopia survivors may receive one supplemental pair fatality
           * after every entrant has completed the unique-participant pass.
           * Supplemental events are deliberately stateless: exactly two
           * unique participants, one elimination, and statistic changes only.
           */
          expect(event.feedGroup).toBe("bloodbath-cornucopia");
          expect(uniqueParticipantTributeIds).toHaveLength(2);
          expect(repeatedParticipantTributeIds).toHaveLength(2);
          expect(
            event.changes.filter((change) => change.type === "eliminate-tribute"),
          ).toHaveLength(1);
          expect(
            event.changes.every(
              (change) =>
                change.type === "eliminate-tribute" || change.type === "increment-statistic",
            ),
          ).toBe(true);
        }

        for (const tributeId of uniqueParticipantTributeIds) {
          const nextAppearanceCount = (appearanceCountByTributeId.get(tributeId) ?? 0) + 1;

          expect(nextAppearanceCount).toBeLessThanOrEqual(2);
          appearanceCountByTributeId.set(tributeId, nextAppearanceCount);
        }
      }

      const expectedTributeIds = new Set(run.state.tributes.map((tribute) => tribute.id));

      expect(new Set(appearanceCountByTributeId.keys())).toEqual(expectedTributeIds);

      for (const event of openingEvents.filter(
        (candidate) => candidate.feedGroup === "bloodbath-flee",
      )) {
        for (const tributeId of new Set(event.participantTributeIds)) {
          expect(appearanceCountByTributeId.get(tributeId)).toBe(1);
        }
      }
    }
  }, 60_000);

  it("keeps opening lethality near the intended half-field direction", () => {
    const eliminationRates = getRuns().map((run) => {
      const openingEvents = getPrimaryEvents(run).filter((event) => isDayOneDaytime(event.round));
      const eliminatedTributeIds = new Set(getEliminatedTributeIds(openingEvents));

      expect(eliminatedTributeIds.size).toBeGreaterThan(0);
      expect(eliminatedTributeIds.size).toBeLessThan(run.state.tributes.length);

      return eliminatedTributeIds.size / run.state.tributes.length;
    });
    const averageRate = getAverage(eliminationRates);

    /*
     * This deliberately remains broader than the authored 45–50% aim.
     * It catches major regressions without turning one deterministic
     * corpus into an exact balancing contract.
     */
    expect(averageRate).toBeGreaterThanOrEqual(0.4);
    expect(averageRate).toBeLessThanOrEqual(0.6);
    expect(Math.max(...eliminationRates)).toBeLessThanOrEqual(0.65);
  });
});

describe("Phase 5.6 repetition and completion guardrails", () => {
  it("completes every seeded game with a victory outcome", () => {
    for (const run of getRuns()) {
      expect(run.state.phase).toBe("victory");
      expect(run.state.victoryOutcome).not.toBeNull();
      expect(run.roundsCompleted).toBeGreaterThan(1);
      expect(run.roundsCompleted).toBeLessThan(100);
    }
  });

  it("does not repeat an authored primary definition within one round", () => {
    for (const run of getRuns()) {
      const definitionsByRound = new Map<string, string[]>();

      for (const event of getPrimaryEvents(run)) {
        if (isForcedLifecycleDefinition(event.definitionId)) {
          continue;
        }

        const key = getRoundKey(event.round);
        const definitionIds = definitionsByRound.get(key) ?? [];

        definitionIds.push(event.definitionId);
        definitionsByRound.set(key, definitionIds);
      }

      for (const definitionIds of definitionsByRound.values()) {
        expect(new Set(definitionIds).size).toBe(definitionIds.length);
      }
    }
  });

  it("exercises repeat-cycle and reservation rejection paths", () => {
    expect(
      getRejectionTotal(getRuns(), ORDINARY_POOL_IDS, "already-used-definition"),
    ).toBeGreaterThan(0);

    expect(
      getRejectionTotal(getRuns(), EVENT_DISTRIBUTION_POOL_IDS, "reservation-blocked"),
    ).toBeGreaterThan(0);

    expect(
      getRejectionTotal(getRuns(), BLOODBATH_POOL_IDS, "fatality-target-stranded"),
    ).toBeGreaterThan(0);
  });
});

describe("Phase 5.6 participant-shape distribution guardrails", () => {
  it("captures every pool with deterministic selector diagnostics", () => {
    const metrics = collectEventDistributionMetrics(getRuns());

    expect(metrics.sample).toEqual({
      totalGames: 20,
      halfGames: 12,
      fullGames: 8,
    });
    expect(metrics.excludedHistoryEntries.unclassifiedPrimary).toBe(0);

    for (const gameSizeId of EVENT_DISTRIBUTION_GAME_SIZE_IDS) {
      const gameSize = metrics.gameSizes[gameSizeId];

      expect(gameSize.games).toBeGreaterThan(0);

      for (const poolId of EVENT_DISTRIBUTION_POOL_IDS) {
        const pool = gameSize.pools[poolId];

        expect(pool.totalSelections).toBeGreaterThan(0);
        expect(pool.events.length).toBeGreaterThan(1);
        expect(pool.selectionDiagnostics.capturedGames).toBe(gameSize.games);
        expect(pool.selectionDiagnostics.opportunities).toBeGreaterThan(0);
      }
    }
  });

  it("selects all four participant shapes across the complete corpus", () => {
    for (const shape of EVENT_PARTICIPANT_SHAPES) {
      expect(getShapeSelections(getRuns(), shape)).toBeGreaterThan(0);
    }
  });

  it("keeps the strong Bloodbath non-solo preference visible", () => {
    const metrics = collectEventDistributionMetrics(getRuns());

    for (const gameSizeId of EVENT_DISTRIBUTION_GAME_SIZE_IDS) {
      for (const poolId of BLOODBATH_POOL_IDS) {
        const pool = metrics.gameSizes[gameSizeId].pools[poolId];

        expect(pool.nonSoloShare).toBeGreaterThan(0.5);
        expect(pool.participantShapes.solo.selections).toBeGreaterThan(0);
      }
    }

    const selectedNonSoloWhenSoloWasFeasible = BLOODBATH_POOL_IDS.reduce(
      (total, poolId) =>
        total +
        getPoolDiagnosticTotal(
          getRuns(),
          poolId,
          (diagnostics) => diagnostics.selectedNonSoloWithSoloFeasible,
        ),
      0,
    );
    const selectedSoloWhenNonSoloWasFeasible = BLOODBATH_POOL_IDS.reduce(
      (total, poolId) =>
        total +
        getPoolDiagnosticTotal(
          getRuns(),
          poolId,
          (diagnostics) => diagnostics.selectedSoloWithNonSoloFeasible,
        ),
      0,
    );

    expect(selectedNonSoloWhenSoloWasFeasible).toBeGreaterThan(selectedSoloWhenNonSoloWasFeasible);
  });

  it("keeps later-Day and Night selection mixed rather than shape-exclusive", () => {
    const metrics = collectEventDistributionMetrics(getRuns());

    for (const gameSizeId of EVENT_DISTRIBUTION_GAME_SIZE_IDS) {
      for (const poolId of ORDINARY_POOL_IDS) {
        const pool = metrics.gameSizes[gameSizeId].pools[poolId];

        expect(pool.nonSoloShare).toBeGreaterThan(0);
        expect(pool.nonSoloShare).toBeLessThan(1);
        expect(pool.participantShapes.solo.selections).toBeGreaterThan(0);
      }
    }
  });

  it("avoids one tiny set of definitions dominating consecutive games", () => {
    const metrics = collectEventDistributionMetrics(getRuns());

    for (const gameSizeId of EVENT_DISTRIBUTION_GAME_SIZE_IDS) {
      for (const poolId of EVENT_DISTRIBUTION_POOL_IDS) {
        const pool = metrics.gameSizes[gameSizeId].pools[poolId];

        expect(pool.concentration.topFiveSelectionShare).toBeLessThan(1);

        if (pool.consecutiveGameOverlap.comparisons > 0) {
          expect(pool.consecutiveGameOverlap.average).toBeLessThan(pool.averageSelectionsPerGame);
        }
      }
    }
  });
});

describe("Phase 5.6 deterministic replay guardrails", () => {
  it("replays one seed identically, including selection diagnostics", () => {
    const options = {
      seed: "phase-5-6-replay",
      districtCount: 12 as const,
      captureSelectionDiagnostics: true,
    };
    const first = simulateGame(options);
    const repeated = simulateGame(options);

    expect(createRunSignature(repeated)).toBe(createRunSignature(first));
    expect(repeated.selectionDiagnostics).toEqual(first.selectionDiagnostics);
  });

  it("still allows different seeds to produce different games", () => {
    const first = simulateGame({
      seed: "phase-5-6-variation-a",
      districtCount: 12,
      captureSelectionDiagnostics: true,
    });
    const second = simulateGame({
      seed: "phase-5-6-variation-b",
      districtCount: 12,
      captureSelectionDiagnostics: true,
    });

    expect(createRunSignature(second)).not.toBe(createRunSignature(first));
  });
});
