// Generated by implement-phase-7.sh

/*
 * Historical Phase 1 event-distribution measurements.
 *
 * These values come from the original 200 Half Game / 100 Full Game
 * deterministic Phase 1 report. Phase 7 uses them for before/after
 * experience comparisons rather than exact snapshot equality.
 */
export const PHASE_1_EVENT_DISTRIBUTION_BASELINE = {
  "half-game": {
    cornucopiaNonSoloShare: 0.439,
    fleeingNonSoloShare: 0.052,
    laterDayNonSoloShare: 0.226,
    cornucopiaTopFiveSelectionShare: 0.592,
    cornucopiaTopTenSelectionShare: 0.817,
    cornucopiaMedianConsecutiveOverlap: 2,
  },
  "full-game": {
    cornucopiaNonSoloShare: 0.589,
    fleeingNonSoloShare: 0.073,
    laterDayNonSoloShare: 0.295,
    cornucopiaTopFiveSelectionShare: 0.495,
    cornucopiaTopTenSelectionShare: 0.683,
    cornucopiaMedianConsecutiveOverlap: 5,
  },
} as const;
