// Generated by implement-phase-5-2.sh
import { describe, expect, it } from "vitest";

import { getBloodbathFatalProfileWeight } from "~/game/bloodbath/bloodbath-fatal-planner";
import { getBloodbathFleeDefinitionWeight } from "~/game/bloodbath/bloodbath-flee-planner";
import { getBloodbathPostTargetDefinitionWeight } from "~/game/bloodbath/bloodbath-post-target-planner";
import {
  createEventCandidateSelectionSeed,
  createFeasibleEventCandidates,
} from "~/game/engine/event-candidate-selection";
import { getOrdinaryEventParticipantShapeMultiplier } from "~/game/engine/ordinary-event-selection-policy";
import { isEventDefinitionEligible } from "~/game/events/event-eligibility";
import { getEventParticipantShapeMultiplier } from "~/game/events/event-participant-shape";
import type { EventDefinition, EventSelectionContext } from "~/game/events/event-schema";
import { getEventDefinitionWeight } from "~/game/events/event-weighting";
import {
  createSelectorTestContext,
  createSelectorTestDefinition,
  createSelectorTestFatalProfile,
  createSelectorTestTributes,
} from "~/game/events/authoring/testing/selector-test-fixtures";
import { createStatusEffectInstance } from "~/game/statuses/status-engine";

function createCandidates(definitions: readonly EventDefinition[], context: EventSelectionContext) {
  return createFeasibleEventCandidates({
    definitions,
    context,
    unavailableTributeIds: new Set<string>(),
    unavailableItemInstanceIds: new Set<string>(),
    selectionSeed: createEventCandidateSelectionSeed(context.state.seed, context.round, 0),
  });
}

function getCandidateWeight(
  definitions: readonly EventDefinition[],
  context: EventSelectionContext,
  definitionId: string,
): number {
  const candidate = createCandidates(definitions, context).find(
    (entry) => entry.definition.id === definitionId,
  );

  if (!candidate) {
    throw new Error(`Expected controlled candidate "${definitionId}" to be feasible.`);
  }

  return candidate.effectiveWeight;
}

function createInjuredContext(severity: 1 | 2 | 3): EventSelectionContext {
  const round = {
    day: 2,
    period: "day",
  } as const;
  const tributes = createSelectorTestTributes(4).map((tribute) => ({
    ...tribute,
    statuses: [
      createStatusEffectInstance("phase-5-2-recovery", tribute.id, "injured", severity, round),
    ],
  }));

  return createSelectorTestContext({
    tributes,
    seed: `phase-5-2-injured-${severity}`,
    round,
  });
}

describe("Phase 5 effective-weight contracts", () => {
  it("gives an otherwise identical Bloodbath pair more weight than a solo", () => {
    const context = createSelectorTestContext({
      tributeCount: 6,
      seed: "bloodbath-shape-ratio",
      round: {
        day: 1,
        period: "day",
      },
    });
    const solo = createSelectorTestDefinition({
      id: "bloodbath-solo",
      participantCount: 1,
    });
    const pair = createSelectorTestDefinition({
      id: "bloodbath-pair",
      participantCount: 2,
    });
    const weightContext = {
      selectedEventCount: 0,
      selectedSoloEventCount: 0,
      hasNonSoloCandidate: false,
    };

    const soloWeight = getBloodbathPostTargetDefinitionWeight(solo, context, weightContext);
    const pairWeight = getBloodbathPostTargetDefinitionWeight(pair, context, weightContext);

    expect(soloWeight).toBeCloseTo(0.2);
    expect(pairWeight).toBeCloseTo(1);
    expect(pairWeight / soloWeight).toBeCloseTo(5);
  });

  it("keeps pair, trio, and four-plus Bloodbath shape treatment flat", () => {
    const context = createSelectorTestContext({
      tributeCount: 8,
      seed: "flat-bloodbath-non-solo",
      round: {
        day: 1,
        period: "day",
      },
    });
    const definitions = [2, 3, 4].map((participantCount) =>
      createSelectorTestDefinition({
        id: `bloodbath-${participantCount}`,
        participantCount,
      }),
    );
    const weightContext = {
      selectedEventCount: 0,
      selectedSoloEventCount: 0,
      hasNonSoloCandidate: true,
    };

    expect(
      definitions.map((definition) =>
        getEventParticipantShapeMultiplier("bloodbath-cornucopia", definition),
      ),
    ).toEqual([1, 1, 1]);

    expect(
      definitions.map((definition) =>
        getBloodbathPostTargetDefinitionWeight(definition, context, weightContext),
      ),
    ).toEqual([1, 1, 1]);

    expect(
      definitions.map((definition) => getBloodbathFleeDefinitionWeight(definition, context)),
    ).toEqual([1, 1, 1]);
  });

  it("tests fatal efficiency separately from participant shape", () => {
    const context = createSelectorTestContext({
      tributeCount: 8,
      seed: "fatal-efficiency-separation",
      round: {
        day: 1,
        period: "day",
      },
    });
    const shapeOnlyProfiles = [
      createSelectorTestFatalProfile({
        id: "shape-only-pair",
        participantCount: 2,
        selectionWeightMultiplier: 1,
      }),
      createSelectorTestFatalProfile({
        id: "shape-only-trio",
        participantCount: 3,
        selectionWeightMultiplier: 1,
      }),
      createSelectorTestFatalProfile({
        id: "shape-only-group",
        participantCount: 4,
        selectionWeightMultiplier: 1,
      }),
    ];

    expect(
      shapeOnlyProfiles.map((profile) => getBloodbathFatalProfileWeight(profile, context)),
    ).toEqual([1.5, 1.5, 1.5]);

    const oneDeathPair = createSelectorTestFatalProfile({
      id: "one-death-pair",
      participantCount: 2,
      minImmediateEliminations: 1,
      maxImmediateEliminations: 1,
    });
    const oneDeathTrio = createSelectorTestFatalProfile({
      id: "one-death-trio",
      participantCount: 3,
      minImmediateEliminations: 1,
      maxImmediateEliminations: 1,
    });
    const twoDeathTrio = createSelectorTestFatalProfile({
      id: "two-death-trio",
      participantCount: 3,
      minImmediateEliminations: 2,
      maxImmediateEliminations: 2,
    });

    expect(getBloodbathFatalProfileWeight(oneDeathPair, context)).toBeCloseTo(2.25);
    expect(getBloodbathFatalProfileWeight(oneDeathTrio, context)).toBeCloseTo(2.25);
    expect(getBloodbathFatalProfileWeight(twoDeathTrio, context)).toBeCloseTo(5.625);
  });

  it("uses smaller later-Day differences and keeps Night neutral", () => {
    const dayContext = createSelectorTestContext({
      tributeCount: 8,
      seed: "later-day-shape-weights",
      round: {
        day: 2,
        period: "day",
      },
    });
    const nightContext = createSelectorTestContext({
      tributeCount: 8,
      seed: "night-shape-weights",
      round: {
        day: 2,
        period: "night",
      },
    });
    const definitions = [1, 2, 3, 4].map((participantCount) =>
      createSelectorTestDefinition({
        id: `ordinary-${participantCount}`,
        participantCount,
        periods: ["day", "night"],
      }),
    );

    expect(
      definitions.map((definition) =>
        getOrdinaryEventParticipantShapeMultiplier(definition, dayContext.round),
      ),
    ).toEqual([0.8, 1.1, 1.15, 1.15]);

    expect(
      createCandidates(definitions, dayContext).map((candidate) => candidate.effectiveWeight),
    ).toEqual([0.8, 1.1, 1.15, 1.15]);

    expect(
      definitions.map((definition) =>
        getOrdinaryEventParticipantShapeMultiplier(definition, nightContext.round),
      ),
    ).toEqual([1, 1, 1, 1]);

    expect(
      createCandidates(definitions, nightContext).map((candidate) => candidate.effectiveWeight),
    ).toEqual([1, 1, 1, 1]);
  });

  it("preserves base weight and zero-weight disabling", () => {
    const context = createSelectorTestContext({
      tributeCount: 6,
      seed: "base-weight-contract",
    });
    const lighterPair = createSelectorTestDefinition({
      id: "lighter-pair",
      participantCount: 2,
      baseWeight: 2,
    });
    const heavierPair = createSelectorTestDefinition({
      id: "heavier-pair",
      participantCount: 2,
      baseWeight: 5,
    });
    const zeroBaseWeight = createSelectorTestDefinition({
      id: "zero-base-weight",
      baseWeight: 0,
    });
    const zeroContextWeight = createSelectorTestDefinition({
      id: "zero-context-weight",
      getWeightMultiplier: () => 0,
    });
    const disabledByEligibility = createSelectorTestDefinition({
      id: "disabled-by-eligibility",
      enabled: false,
    });
    const weightContext = {
      selectedEventCount: 0,
      selectedSoloEventCount: 0,
      hasNonSoloCandidate: true,
    };

    const lighterWeight = getBloodbathPostTargetDefinitionWeight(
      lighterPair,
      context,
      weightContext,
    );
    const heavierWeight = getBloodbathPostTargetDefinitionWeight(
      heavierPair,
      context,
      weightContext,
    );

    expect(heavierWeight / lighterWeight).toBeCloseTo(2.5);
    expect(getEventDefinitionWeight(zeroBaseWeight, context)).toBe(0);
    expect(getEventDefinitionWeight(zeroContextWeight, context)).toBe(0);
    expect(isEventDefinitionEligible(disabledByEligibility, context)).toBe(false);
  });

  it("preserves authored specificity through effective weighting", () => {
    const context = createSelectorTestContext({
      tributeCount: 4,
      seed: "specificity-weight-contract",
    });
    const genericSolo = createSelectorTestDefinition({
      id: "generic-solo",
    });
    const specificSolo = createSelectorTestDefinition({
      id: "specific-solo",
      selectionProfile: {
        specificityScore: 2,
        specificityReasons: ["custom-eligibility"],
      },
    });

    expect(
      getEventDefinitionWeight(specificSolo, context) /
        getEventDefinitionWeight(genericSolo, context),
    ).toBeCloseTo(2);

    expect(getCandidateWeight([genericSolo, specificSolo], context, "specific-solo")).toBeCloseTo(
      1.6,
    );
  });

  it("lets urgent solo recovery outweigh a generic pair", () => {
    const context = createInjuredContext(3);
    const urgentSolo = createSelectorTestDefinition({
      id: "urgent-solo-treatment",
      recoveryProfile: {
        targets: [
          {
            kind: "status",
            roleId: "participants",
            statusIds: ["injured"],
          },
        ],
      },
    });
    const genericPair = createSelectorTestDefinition({
      id: "generic-pair-interaction",
      participantCount: 2,
    });
    const definitions = [urgentSolo, genericPair];

    const urgentWeight = getCandidateWeight(definitions, context, urgentSolo.id);
    const genericPairWeight = getCandidateWeight(definitions, context, genericPair.id);

    expect(urgentWeight).toBeCloseTo(4.8);
    expect(genericPairWeight).toBeCloseTo(1.1);
    expect(urgentWeight).toBeGreaterThan(genericPairWeight);
  });

  it("lets a sufficiently specific solo outweigh a generic pair", () => {
    const context = createSelectorTestContext({
      tributeCount: 4,
      seed: "specific-solo-versus-pair",
    });
    const specificSolo = createSelectorTestDefinition({
      id: "specific-solo",
      selectionProfile: {
        specificityScore: 2,
        specificityReasons: ["custom-eligibility"],
      },
    });
    const genericPair = createSelectorTestDefinition({
      id: "generic-pair",
      participantCount: 2,
    });
    const definitions = [specificSolo, genericPair];

    expect(getCandidateWeight(definitions, context, specificSolo.id)).toBeCloseTo(1.6);
    expect(getCandidateWeight(definitions, context, genericPair.id)).toBeCloseTo(1.1);
  });

  it("combines base, contextual, specificity, shape, and recovery multipliers", () => {
    const context = createInjuredContext(2);
    const definition = createSelectorTestDefinition({
      id: "combined-weight-solo",
      baseWeight: 3,
      getWeightMultiplier: () => 0.5,
      selectionProfile: {
        specificityScore: 2,
        specificityReasons: ["status-requirement"],
      },
      recoveryProfile: {
        targets: [
          {
            kind: "status",
            roleId: "participants",
            statusIds: ["injured"],
          },
        ],
      },
    });

    /*
     * 3 base
     * x 0.5 contextual
     * x 2 specificity
     * x 0.8 later-Day solo shape
     * x 4 severity-two recovery
     * = 9.6
     */
    expect(getCandidateWeight([definition], context, definition.id)).toBeCloseTo(9.6);
  });
});
