// Generated by implement-phase-5-2.sh
import { describe, expect, it } from "vitest";

import {
  getEventParticipantCount,
  getEventParticipantShape,
  getParticipantShapeForCount,
  getParticipantShapeForTributeIds,
} from "~/game/events/event-participant-shape";
import type { EventDefinition } from "~/game/events/event-schema";
import {
  createSelectorTestDefinition,
  createSelectorTestFatalProfile,
} from "~/game/events/authoring/testing/selector-test-fixtures";
import { validateEventDefinition } from "~/game/events/validation/validate-event-definition";

describe("Phase 5 participant-shape contracts", () => {
  it("classifies solo, pair, trio, and four-plus participant counts", () => {
    const cases = [
      [1, "solo"],
      [2, "pair"],
      [3, "trio"],
      [4, "group-four-plus"],
      [8, "group-four-plus"],
    ] as const;

    for (const [participantCount, expectedShape] of cases) {
      expect(getParticipantShapeForCount(participantCount)).toBe(expectedShape);

      const definition = createSelectorTestDefinition({
        id: `shape-${participantCount}`,
        participantCount,
      });

      expect(getEventParticipantShape(definition)).toBe(expectedShape);
    }
  });

  it("classifies dynamic resolved casts by distinct tribute IDs", () => {
    const cases = [
      [["tribute-a"], "solo"],
      [["tribute-a", "tribute-b"], "pair"],
      [["tribute-a", "tribute-b", "tribute-c"], "trio"],
      [["tribute-a", "tribute-b", "tribute-c", "tribute-d"], "group-four-plus"],
      [["tribute-a", "tribute-b", "tribute-b"], "pair"],
    ] as const;

    for (const [tributeIds, expectedShape] of cases) {
      expect(getParticipantShapeForTributeIds(tributeIds)).toBe(expectedShape);
    }
  });

  it("sums multiple technical roles before inferring shape", () => {
    const definition = createSelectorTestDefinition({
      id: "multi-role-group",
      roles: [
        {
          id: "actor",
          count: 1,
        },
        {
          id: "targets",
          count: 2,
        },
        {
          id: "witness",
          count: 1,
        },
      ],
    });

    expect(getEventParticipantCount(definition)).toBe(4);
    expect(getEventParticipantShape(definition)).toBe("group-four-plus");
  });

  it("uses explicit shape metadata instead of technical role count", () => {
    const definition = createSelectorTestDefinition({
      id: "technical-trio-meaningful-pair",
      roles: [
        {
          id: "actor",
          count: 1,
        },
        {
          id: "target-and-flavour-role",
          count: 2,
        },
      ],
      participantShape: "pair",
    });

    expect(getEventParticipantCount(definition)).toBe(3);
    expect(getEventParticipantShape(definition)).toBe("pair");
  });

  it("keeps participant shape independent from elimination count", () => {
    const oneDeathTrio = createSelectorTestFatalProfile({
      id: "one-death-trio",
      participantCount: 3,
      minImmediateEliminations: 1,
      maxImmediateEliminations: 1,
    });
    const twoDeathTrio = createSelectorTestFatalProfile({
      id: "two-death-trio",
      participantCount: 3,
      minImmediateEliminations: 2,
      maxImmediateEliminations: 2,
    });
    const variableTrio = createSelectorTestFatalProfile({
      id: "variable-trio",
      participantCount: 3,
      minImmediateEliminations: 0,
      maxImmediateEliminations: 2,
      eliminationCount: 0,
    });

    expect(
      [oneDeathTrio, twoDeathTrio, variableTrio].map((profile) =>
        getEventParticipantShape(profile.definition),
      ),
    ).toEqual(["trio", "trio", "trio"]);
  });

  it("allows an explicit meaningful-cast override regardless of fatalities", () => {
    const profile = createSelectorTestFatalProfile({
      id: "technical-group-meaningful-solo",
      roles: [
        {
          id: "visible-tribute",
          count: 1,
        },
        {
          id: "technical-flavour-participants",
          count: 3,
        },
      ],
      participantShape: "solo",
      minImmediateEliminations: 1,
      maxImmediateEliminations: 1,
    });

    expect(getEventParticipantCount(profile.definition)).toBe(4);
    expect(getEventParticipantShape(profile.definition)).toBe("solo");
  });

  it("rejects invalid counts and invalid runtime metadata", () => {
    for (const invalidCount of [0, -1, 1.5]) {
      expect(() => getParticipantShapeForCount(invalidCount)).toThrow(/positive integer/i);
    }

    expect(() =>
      createSelectorTestDefinition({
        id: "zero-participant-definition",
        roles: [
          {
            id: "nobody",
            count: 0,
          },
        ],
      }),
    ).toThrow(/at least one participant/i);

    const invalidDefinition = {
      ...createSelectorTestDefinition({
        id: "invalid-shape-metadata",
      }),
      participantShape: "crowd",
    } as unknown as EventDefinition;

    expect(() => validateEventDefinition(invalidDefinition)).toThrow(
      /invalid participant-shape metadata/i,
    );
  });
});
