// Generated by implement-phase-5-1.sh
import { describe, expect, it } from "vitest";

import {
  createFixedRandomSource,
  createSelectorTestContext,
  createSelectorTestDefinition,
  createSelectorTestFatalProfile,
  createSelectorTestReservations,
  createSelectorTestSeeds,
  createSelectorTestTributes,
  createSequenceRandomSource,
  withSelectorTestItem,
} from "./selector-test-fixtures";

describe("selector test fixtures", () => {
  it("creates controlled definitions with dynamic roles and overrides", () => {
    const definition = createSelectorTestDefinition({
      id: "controlled-dynamic-event",
      roles: [
        {
          id: "actor",
          count: 1,
        },
        {
          id: "targets",
          count: 2,
        },
      ],
      participantShape: "pair",
      baseWeight: 7,
      selectionProfile: {
        specificityScore: 3,
        specificityReasons: ["custom-eligibility"],
      },
    });

    expect(definition.roles.map((role) => role.count)).toEqual([1, 2]);
    expect(definition.participantShape).toBe("pair");
    expect(definition.baseWeight).toBe(7);
    expect(definition.selectionProfile?.specificityScore).toBe(3);
  });

  it("creates fixed fatal profiles and real elimination changes", () => {
    const context = createSelectorTestContext({
      tributeCount: 2,
    });
    const profile = createSelectorTestFatalProfile({
      id: "controlled-fatal-pair",
      participantCount: 2,
      minImmediateEliminations: 1,
      maxImmediateEliminations: 1,
    });
    const resolution = profile.definition.resolve({
      ...context,
      eventId: "controlled-fatal-pair:event",
      random: createFixedRandomSource(),
      participantsByRole: {
        participants: context.livingTributes,
      },
    });

    expect(profile.minImmediateEliminations).toBe(1);
    expect(profile.maxImmediateEliminations).toBe(1);
    expect(resolution.changes.filter((change) => change.type === "eliminate-tribute")).toHaveLength(
      1,
    );
  });

  it("supports disabled and item-gated definitions", () => {
    const tribute = withSelectorTestItem(createSelectorTestTributes(1)[0]!, "knife");
    const context = createSelectorTestContext({
      tributes: [tribute],
    });
    const disabled = createSelectorTestDefinition({
      id: "disabled-event",
      enabled: false,
    });
    const itemGated = createSelectorTestDefinition({
      id: "item-gated-event",
      requiredItemDefinitionId: "knife",
    });

    expect(disabled.isEligible?.(context)).toBe(false);
    expect(itemGated.roles[0]?.requiredItemDefinitionIds).toEqual(["knife"]);
    expect(context.livingTributes[0]?.inventory).toHaveLength(1);
  });

  it("creates deterministic random sources, seeds, and reservations", () => {
    const fixed = createFixedRandomSource(0.25);
    const sequence = createSequenceRandomSource([0.1, 0.2], 0.3);
    const reservations = createSelectorTestReservations({
      tributeIds: ["tribute-a"],
      itemInstanceIds: ["item-a"],
    });

    expect([fixed(), fixed()]).toEqual([0.25, 0.25]);
    expect([sequence(), sequence(), sequence()]).toEqual([0.1, 0.2, 0.3]);
    expect(createSelectorTestSeeds("controlled", 3)).toEqual([
      "controlled-0",
      "controlled-1",
      "controlled-2",
    ]);
    expect(reservations.unavailableTributeIds).toEqual(new Set(["tribute-a"]));
    expect(reservations.unavailableItemInstanceIds).toEqual(new Set(["item-a"]));
  });
});
