// Generated by implement-phase-5-1.sh
import type { BloodbathFatalSelectionProfile } from "~/game/bloodbath/bloodbath-fatal-planner";
import type { RandomSource } from "~/game/engine/random";
import type {
  EventCategory,
  EventDefinition,
  EventParticipantShape,
  EventRecoveryProfile,
  EventSelectionContext,
  EventSelectionProfile,
  EventTag,
  ParticipantRoleDefinition,
} from "~/game/events/event-schema";
import type { ItemDefinitionId } from "~/game/items/item-schema";
import type { GameState, GameTribute, RoundReference } from "~/game/types/game-state";

import {
  createAuthoringTestGame,
  createAuthoringTestTribute,
  withAuthoringTestItem,
} from "./authoring-test-fixtures";

export const SELECTOR_TEST_ROUND = {
  day: 2,
  period: "day",
} as const satisfies RoundReference;

export interface SelectorTestDefinitionOptions {
  id: string;
  participantCount?: number;
  roles?: readonly ParticipantRoleDefinition[];
  participantShape?: EventParticipantShape;
  category?: EventCategory;
  periods?: readonly RoundReference["period"][];
  baseWeight?: number;
  tags?: readonly EventTag[];
  enabled?: boolean;
  isEligible?: EventDefinition["isEligible"];
  getWeightMultiplier?: EventDefinition["getWeightMultiplier"];
  selectionProfile?: EventSelectionProfile;
  recoveryProfile?: EventRecoveryProfile;
  requiredItemDefinitionId?: ItemDefinitionId;
  itemAccess?: "accessible" | "owned";
  eliminationCount?: number;
  resolve?: EventDefinition["resolve"];
}

function assertNonNegativeInteger(label: string, value: number): void {
  if (!Number.isInteger(value) || value < 0) {
    throw new Error(`${label} must be a non-negative integer.`);
  }
}

export function createSelectorTestDefinition({
  id,
  participantCount = 1,
  roles,
  participantShape,
  category = "survival",
  periods = ["day"],
  baseWeight = 1,
  tags = category === "fatal" ? ["fatal"] : ["survival"],
  enabled = true,
  isEligible,
  getWeightMultiplier,
  selectionProfile,
  recoveryProfile,
  requiredItemDefinitionId,
  itemAccess = "owned",
  eliminationCount = 0,
  resolve,
}: SelectorTestDefinitionOptions): EventDefinition {
  assertNonNegativeInteger("Selector test participant count", participantCount);
  assertNonNegativeInteger("Selector test elimination count", eliminationCount);

  const resolvedRoles: readonly ParticipantRoleDefinition[] = roles ?? [
    {
      id: "participants",
      count: participantCount,
      ...(requiredItemDefinitionId
        ? {
            requiredItemDefinitionIds: [requiredItemDefinitionId],
            itemAccess,
          }
        : {}),
    },
  ];
  const declaredParticipantCount = resolvedRoles.reduce((total, role) => total + role.count, 0);

  if (declaredParticipantCount < 1) {
    throw new Error("A selector test definition requires at least one participant.");
  }

  if (eliminationCount > declaredParticipantCount) {
    throw new Error(
      `Selector test definition "${id}" cannot eliminate more tributes than it declares.`,
    );
  }

  return {
    id,
    category,
    periods,
    baseWeight,
    tags,
    ...(participantShape ? { participantShape } : {}),
    ...(selectionProfile ? { selectionProfile } : {}),
    ...(recoveryProfile ? { recoveryProfile } : {}),
    roles: resolvedRoles,
    isEligible: enabled ? isEligible : () => false,
    ...(getWeightMultiplier ? { getWeightMultiplier } : {}),
    resolve:
      resolve ??
      (({ participantsByRole }) => {
        const participants = [
          ...new Map(
            Object.values(participantsByRole)
              .flat()
              .map((tribute) => [tribute.id, tribute]),
          ).values(),
        ];

        return {
          text: `${id} occurs.`,
          changes: participants.slice(0, eliminationCount).map((tribute) => ({
            type: "eliminate-tribute" as const,
            tributeId: tribute.id,
            causeId: id,
            causeLabel: id,
            summary: `${tribute.snapshot.name} is eliminated by ${id}.`,
            killerTributeIds: [],
          })),
        };
      }),
  };
}

export interface SelectorTestFatalProfileOptions extends SelectorTestDefinitionOptions {
  minImmediateEliminations?: number;
  maxImmediateEliminations?: number;
  selectionWeightMultiplier?: number;
}

export function createSelectorTestFatalProfile({
  minImmediateEliminations = 1,
  maxImmediateEliminations = minImmediateEliminations,
  selectionWeightMultiplier,
  ...definitionOptions
}: SelectorTestFatalProfileOptions): BloodbathFatalSelectionProfile {
  assertNonNegativeInteger(
    "Selector test minimum immediate eliminations",
    minImmediateEliminations,
  );
  assertNonNegativeInteger(
    "Selector test maximum immediate eliminations",
    maxImmediateEliminations,
  );

  if (maxImmediateEliminations < minImmediateEliminations) {
    throw new Error("Selector test maximum immediate eliminations cannot be below the minimum.");
  }

  return {
    definition: createSelectorTestDefinition({
      ...definitionOptions,
      category: definitionOptions.category ?? "fatal",
      tags: definitionOptions.tags ?? ["fatal"],
      eliminationCount: definitionOptions.eliminationCount ?? minImmediateEliminations,
    }),
    minImmediateEliminations,
    maxImmediateEliminations,
    ...(selectionWeightMultiplier === undefined ? {} : { selectionWeightMultiplier }),
  };
}

export function createSelectorTestTributes(
  count: number,
  customize?: (tribute: GameTribute, index: number) => GameTribute,
): GameTribute[] {
  assertNonNegativeInteger("Selector test tribute count", count);

  return Array.from({ length: count }, (_, index) => {
    const tribute = createAuthoringTestTribute({
      id: `selector-tribute-${index + 1}`,
      name: `Selector Tribute ${index + 1}`,
    });

    return customize?.(tribute, index) ?? tribute;
  });
}

export interface SelectorTestContextOptions {
  tributeCount?: number;
  tributes?: readonly GameTribute[];
  seed?: string;
  round?: RoundReference;
  stateOverrides?: Partial<GameState>;
}

export function createSelectorTestContext({
  tributeCount = 6,
  tributes,
  seed = "selector-test-seed",
  round = SELECTOR_TEST_ROUND,
  stateOverrides = {},
}: SelectorTestContextOptions = {}): EventSelectionContext {
  const selectedTributes = tributes ?? createSelectorTestTributes(tributeCount);
  const baseState = createAuthoringTestGame(selectedTributes);
  const state: GameState = {
    ...baseState,
    ...stateOverrides,
    seed,
    currentRound: round,
    tributes: stateOverrides.tributes ?? [...selectedTributes],
  };

  return {
    state,
    round,
    livingTributes: state.tributes.filter((tribute) => tribute.isAlive),
  };
}

export function withSelectorTestItem(
  tribute: GameTribute,
  itemDefinitionId: ItemDefinitionId,
): GameTribute {
  return withAuthoringTestItem(tribute, itemDefinitionId, {
    eventId: `selector-test-item:${tribute.id}:${itemDefinitionId}`,
    round: SELECTOR_TEST_ROUND,
  });
}

export interface SelectorTestReservations {
  unavailableTributeIds: Set<string>;
  unavailableItemInstanceIds: Set<string>;
}

export function createSelectorTestReservations({
  tributeIds = [],
  itemInstanceIds = [],
}: {
  tributeIds?: readonly string[];
  itemInstanceIds?: readonly string[];
} = {}): SelectorTestReservations {
  return {
    unavailableTributeIds: new Set(tributeIds),
    unavailableItemInstanceIds: new Set(itemInstanceIds),
  };
}

export function createFixedRandomSource(value = 0): RandomSource {
  if (!Number.isFinite(value) || value < 0 || value >= 1) {
    throw new Error("A fixed random value must be at least zero and below one.");
  }

  return () => value;
}

export function createSequenceRandomSource(values: readonly number[], fallback = 0): RandomSource {
  const sequence = [...values];
  const validate = (value: number): number => {
    if (!Number.isFinite(value) || value < 0 || value >= 1) {
      throw new Error("Random sequence values must be at least zero and below one.");
    }

    return value;
  };

  sequence.forEach(validate);
  validate(fallback);

  let index = 0;

  return () => {
    const value = sequence[index] ?? fallback;
    index += 1;
    return value;
  };
}

export function createSelectorTestSeeds(prefix: string, count: number): string[] {
  assertNonNegativeInteger("Selector test seed count", count);

  return Array.from({ length: count }, (_, index) => `${prefix}-${index}`);
}
