// Generated by implement-phase-5-3.sh
import { describe, expect, it } from "vitest";

import {
  canCompleteBloodbathFatalityTargetAfterProfile,
  canReachBloodbathFatalityTarget,
  getBestEffortBloodbathFatalProfiles,
  getMaximumReachablePostTargetReservation,
  type BloodbathFatalSelectionProfile,
} from "~/game/bloodbath/bloodbath-fatal-planner";
import {
  selectAuthoredFatalBloodbathEvent,
  type BloodbathAcquisitionSelection,
} from "~/game/bloodbath/bloodbath-sequencer";
import {
  createFixedRandomSource,
  createSelectorTestContext,
  createSelectorTestFatalProfile,
  createSelectorTestSeeds,
  createSelectorTestTributes,
  withSelectorTestItem,
} from "~/game/events/authoring/testing/selector-test-fixtures";
import { createSeededRandom, type RandomSource } from "~/game/engine/random";
import { getEventParticipantShape } from "~/game/events/event-participant-shape";
import type { GameTribute, RoundReference } from "~/game/types/game-state";

const BLOODBATH_ROUND = {
  day: 1,
  period: "day",
} as const satisfies RoundReference;

interface FatalSelectionOptions {
  profiles: readonly BloodbathFatalSelectionProfile[];
  tributeCount?: number;
  tributes?: readonly GameTribute[];
  remainingTributeIds?: readonly string[];
  fatalityDeficit: number;
  reservedPostTargetCount?: number;
  usedDefinitionIds?: readonly string[];
  random?: RandomSource;
  seed?: string;
}

interface FatalSelectionResult {
  selection: BloodbathAcquisitionSelection | null;
  startingRemainingTributeIds: readonly string[];
  remainingTributes: GameTribute[];
}

function selectControlledFatal({
  profiles,
  tributeCount = 6,
  tributes,
  remainingTributeIds,
  fatalityDeficit,
  reservedPostTargetCount = 0,
  usedDefinitionIds = [],
  random = createFixedRandomSource(),
  seed = "phase-5-3-controlled-fatal",
}: FatalSelectionOptions): FatalSelectionResult {
  const context = createSelectorTestContext({
    tributeCount,
    ...(tributes ? { tributes } : {}),
    seed,
    round: BLOODBATH_ROUND,
  });
  const allowedTributeIds = remainingTributeIds ? new Set(remainingTributeIds) : null;
  const remainingTributes = context.livingTributes.filter(
    (tribute) => !allowedTributeIds || allowedTributeIds.has(tribute.id),
  );
  const startingRemainingTributeIds = remainingTributes.map((tribute) => tribute.id);
  const selection = selectAuthoredFatalBloodbathEvent(
    context.state,
    BLOODBATH_ROUND,
    remainingTributes,
    fatalityDeficit,
    reservedPostTargetCount,
    new Set(usedDefinitionIds),
    random,
    profiles,
  );

  return {
    selection,
    startingRemainingTributeIds,
    remainingTributes,
  };
}

function createProfile(
  id: string,
  participantCount: number,
  eliminationCount: number,
  maximumEliminations = eliminationCount,
): BloodbathFatalSelectionProfile {
  return createSelectorTestFatalProfile({
    id,
    participantCount,
    minImmediateEliminations: eliminationCount,
    maxImmediateEliminations: maximumEliminations,
  });
}

describe("Phase 5.3 fatal-planning reachability", () => {
  it.each([
    {
      label: "solo plus pair",
      profiles: [createProfile("solo-one", 1, 1), createProfile("pair-one", 2, 1)],
      availableParticipantCount: 3,
      fatalityDeficit: 2,
      expected: true,
    },
    {
      label: "solo plus two-death trio",
      profiles: [createProfile("solo-one", 1, 1), createProfile("trio-two", 3, 2)],
      availableParticipantCount: 4,
      fatalityDeficit: 3,
      expected: true,
    },
    {
      label: "pair plus two-death trio",
      profiles: [createProfile("pair-one", 2, 1), createProfile("trio-two", 3, 2)],
      availableParticipantCount: 5,
      fatalityDeficit: 3,
      expected: true,
    },
    {
      label: "all participant shapes",
      profiles: [
        createProfile("solo-one", 1, 1),
        createProfile("pair-one", 2, 1),
        createProfile("trio-two", 3, 2),
        createProfile("group-two", 4, 2),
      ],
      availableParticipantCount: 10,
      fatalityDeficit: 5,
      expected: true,
    },
    {
      label: "only solo events",
      profiles: [
        createProfile("solo-a", 1, 1),
        createProfile("solo-b", 1, 1),
        createProfile("solo-c", 1, 1),
      ],
      availableParticipantCount: 3,
      fatalityDeficit: 3,
      expected: true,
    },
    {
      label: "only non-solo events",
      profiles: [createProfile("pair-one", 2, 1), createProfile("trio-two", 3, 2)],
      availableParticipantCount: 5,
      fatalityDeficit: 3,
      expected: true,
    },
    {
      label: "solo event required to avoid a stranded tribute",
      profiles: [createProfile("pair-one", 2, 1), createProfile("second-pair-one", 2, 1)],
      availableParticipantCount: 3,
      fatalityDeficit: 2,
      expected: false,
    },
    {
      label: "participant budget too small",
      profiles: [createProfile("trio-two", 3, 2)],
      availableParticipantCount: 2,
      fatalityDeficit: 2,
      expected: false,
    },
  ])(
    "evaluates $label without catalogue-order assumptions",
    ({ profiles, availableParticipantCount, fatalityDeficit, expected }) => {
      expect(
        canReachBloodbathFatalityTarget({
          profiles,
          availableParticipantCount,
          fatalityDeficit,
        }),
      ).toBe(expected);
    },
  );

  it("accepts the one-death soft overshoot but rejects larger overshoot", () => {
    const accepted = selectControlledFatal({
      profiles: [createProfile("two-death-trio", 3, 2)],
      tributeCount: 3,
      fatalityDeficit: 1,
    });
    const rejected = selectControlledFatal({
      profiles: [createProfile("three-death-group", 4, 3)],
      tributeCount: 4,
      fatalityDeficit: 1,
    });

    expect(accepted.selection?.definition.id).toBe("two-death-trio");
    expect(accepted.remainingTributes).toHaveLength(0);

    expect(rejected.selection).toBeNull();
    expect(rejected.remainingTributes.map((tribute) => tribute.id)).toEqual(
      rejected.startingRemainingTributeIds,
    );
  });

  it("keeps only candidates whose every authored outcome preserves completion", () => {
    const variablePair = createProfile("variable-pair", 2, 0, 1);
    const remainingSolo = createProfile("remaining-solo", 1, 1);

    expect(
      canCompleteBloodbathFatalityTargetAfterProfile({
        profile: variablePair,
        remainingProfiles: [remainingSolo],
        availableParticipantCount: 4,
        fatalityDeficit: 2,
      }),
    ).toBe(false);

    const result = selectControlledFatal({
      profiles: [variablePair, remainingSolo],
      tributeCount: 4,
      fatalityDeficit: 2,
      random: createFixedRandomSource(0),
    });

    expect(result.selection?.definition.id).toBe("remaining-solo");
  });

  it("allows a variable outcome when every branch retains a completion path", () => {
    const variablePair = createProfile("safe-variable-pair", 2, 0, 1);
    const firstSolo = createProfile("completion-solo-a", 1, 1);
    const secondSolo = createProfile("completion-solo-b", 1, 1);

    expect(
      canCompleteBloodbathFatalityTargetAfterProfile({
        profile: variablePair,
        remainingProfiles: [firstSolo, secondSolo],
        availableParticipantCount: 4,
        fatalityDeficit: 2,
      }),
    ).toBe(true);

    const result = selectControlledFatal({
      profiles: [variablePair, firstSolo, secondSolo],
      tributeCount: 4,
      fatalityDeficit: 2,
      random: createFixedRandomSource(0),
    });

    expect(result.selection?.definition.id).toBe("safe-variable-pair");
  });
});

describe("Phase 5.3 fatal selector feasibility", () => {
  it("uses a solo fatality when only solo events can complete the plan", () => {
    const profiles = [
      createProfile("solo-a", 1, 1),
      createProfile("solo-b", 1, 1),
      createProfile("solo-c", 1, 1),
    ];
    const first = selectControlledFatal({
      profiles,
      tributeCount: 3,
      fatalityDeficit: 2,
      random: createFixedRandomSource(0),
    });

    expect(first.selection?.definition.id).toBe("solo-a");
    expect(first.remainingTributes).toHaveLength(2);

    const secondContext = createSelectorTestContext({
      tributeCount: 3,
      seed: "phase-5-3-second-solo",
      round: BLOODBATH_ROUND,
    });
    const secondRemaining = secondContext.livingTributes.filter((tribute) =>
      first.remainingTributes.some((remainingTribute) => remainingTribute.id === tribute.id),
    );
    const second = selectAuthoredFatalBloodbathEvent(
      secondContext.state,
      BLOODBATH_ROUND,
      secondRemaining,
      1,
      0,
      new Set(["solo-a"]),
      createFixedRandomSource(0),
      profiles,
    );

    expect(second?.definition.id).toBe("solo-b");
    expect(secondRemaining).toHaveLength(1);
  });

  it("selects from an all-non-solo pool without requiring a solo fallback", () => {
    const result = selectControlledFatal({
      profiles: [createProfile("pair-one", 2, 1), createProfile("trio-two", 3, 2)],
      tributeCount: 5,
      fatalityDeficit: 3,
      random: createFixedRandomSource(0),
    });

    expect(result.selection?.definition.id).toBe("pair-one");
    expect(result.remainingTributes).toHaveLength(3);
  });

  it("excludes definitions already used in the Bloodbath", () => {
    const first = createProfile("already-used", 1, 1);
    const second = createProfile("unused", 1, 1);
    const result = selectControlledFatal({
      profiles: [first, second],
      tributeCount: 2,
      fatalityDeficit: 1,
      usedDefinitionIds: ["already-used"],
      random: createFixedRandomSource(0),
    });

    expect(result.selection?.definition.id).toBe("unused");
  });

  it("returns null when every otherwise valid definition was already used", () => {
    const result = selectControlledFatal({
      profiles: [createProfile("only-profile", 1, 1)],
      tributeCount: 2,
      fatalityDeficit: 1,
      usedDefinitionIds: ["only-profile"],
    });

    expect(result.selection).toBeNull();
    expect(result.remainingTributes.map((tribute) => tribute.id)).toEqual(
      result.startingRemainingTributeIds,
    );
  });

  it("cannot select a participant reserved outside the remaining pool", () => {
    const tributes = createSelectorTestTributes(3);
    const reservedTribute = tributes[0]!;
    const profile = createSelectorTestFatalProfile({
      id: "reserved-tribute-required",
      roles: [
        {
          id: "tribute",
          count: 1,
          isEligible: (tribute) => tribute.id === reservedTribute.id,
        },
      ],
      minImmediateEliminations: 1,
      maxImmediateEliminations: 1,
    });
    const result = selectControlledFatal({
      profiles: [profile],
      tributes,
      fatalityDeficit: 1,
      remainingTributeIds: tributes.slice(1).map((tribute) => tribute.id),
    });

    expect(result.selection).toBeNull();
    expect(result.remainingTributes).toHaveLength(2);
  });

  it("selects an owned-item event only while a usable owner remains available", () => {
    const baseTributes = createSelectorTestTributes(2);
    const armedTribute = withSelectorTestItem(baseTributes[0]!, "knife");
    const tributes = [armedTribute, baseTributes[1]!];
    const profile = createSelectorTestFatalProfile({
      id: "owned-knife-fatality",
      participantCount: 1,
      requiredItemDefinitionId: "knife",
      itemAccess: "owned",
      minImmediateEliminations: 1,
      maxImmediateEliminations: 1,
    });
    const available = selectControlledFatal({
      profiles: [profile],
      tributes,
      fatalityDeficit: 1,
    });
    const ownerReserved = selectControlledFatal({
      profiles: [profile],
      tributes,
      fatalityDeficit: 1,
      remainingTributeIds: [baseTributes[1]!.id],
    });

    expect(available.selection?.definition.id).toBe("owned-knife-fatality");
    expect(ownerReserved.selection).toBeNull();
  });
});

describe("Phase 5.3 best-effort and reservation behaviour", () => {
  it("makes best-effort progress when the exact target is unreachable", () => {
    const pair = createProfile("best-effort-pair", 2, 1);
    const result = selectControlledFatal({
      profiles: [pair],
      tributeCount: 2,
      fatalityDeficit: 2,
      reservedPostTargetCount: 0,
    });

    expect(
      getBestEffortBloodbathFatalProfiles([pair]).map((profile) => profile.definition.id),
    ).toEqual(["best-effort-pair"]);
    expect(result.selection?.definition.id).toBe("best-effort-pair");
    expect(result.remainingTributes).toHaveLength(0);
  });

  it("does not spend a protected post-target reservation on best effort", () => {
    const result = selectControlledFatal({
      profiles: [createProfile("reserved-best-effort-pair", 2, 1)],
      tributeCount: 3,
      fatalityDeficit: 2,
      reservedPostTargetCount: 1,
    });

    expect(result.selection).toBeNull();
    expect(result.remainingTributes).toHaveLength(3);
  });

  it("retains a requested reservation when guaranteed profiles can still finish", () => {
    const profiles = [
      createProfile("solo-a", 1, 1),
      createProfile("solo-b", 1, 1),
      createProfile("solo-c", 1, 1),
    ];

    expect(
      getMaximumReachablePostTargetReservation({
        profiles,
        totalParticipantCount: 4,
        fatalityDeficit: 3,
        requestedReservation: 1,
      }),
    ).toBe(1);
  });

  it("releases a requested reservation when the only route needs every participant", () => {
    const profiles = [createProfile("all-participant-group", 4, 3)];

    expect(
      getMaximumReachablePostTargetReservation({
        profiles,
        totalParticipantCount: 4,
        fatalityDeficit: 3,
        requestedReservation: 1,
      }),
    ).toBe(0);
  });
});

describe("Phase 5.3 invalid fatal-plan inputs", () => {
  it("rejects malformed elimination ranges", () => {
    const malformed = {
      ...createProfile("malformed-range", 2, 1),
      minImmediateEliminations: 2,
      maxImmediateEliminations: 1,
    };

    expect(() =>
      canReachBloodbathFatalityTarget({
        profiles: [malformed],
        availableParticipantCount: 2,
        fatalityDeficit: 1,
      }),
    ).toThrow(/invalid elimination range/i);
  });

  it("rejects negative participant budgets and deficits", () => {
    const profiles = [createProfile("valid-profile", 1, 1)];

    expect(() =>
      canReachBloodbathFatalityTarget({
        profiles,
        availableParticipantCount: -1,
        fatalityDeficit: 1,
      }),
    ).toThrow(/available fatal participant count/i);

    expect(() =>
      canReachBloodbathFatalityTarget({
        profiles,
        availableParticipantCount: 1,
        fatalityDeficit: -1,
      }),
    ).toThrow(/fatality deficit/i);
  });
});

describe("Phase 5.3 deterministic controlled catalogues", () => {
  it("is reproducible per seed while allowing every participant shape", () => {
    const profiles = [
      createSelectorTestFatalProfile({
        id: "seeded-solo",
        participantCount: 1,
        minImmediateEliminations: 1,
        maxImmediateEliminations: 1,
        selectionWeightMultiplier: 1,
      }),
      createSelectorTestFatalProfile({
        id: "seeded-pair",
        participantCount: 2,
        minImmediateEliminations: 1,
        maxImmediateEliminations: 1,
        selectionWeightMultiplier: 1,
      }),
      createSelectorTestFatalProfile({
        id: "seeded-trio",
        participantCount: 3,
        minImmediateEliminations: 1,
        maxImmediateEliminations: 1,
        selectionWeightMultiplier: 1,
      }),
      createSelectorTestFatalProfile({
        id: "seeded-group",
        participantCount: 4,
        minImmediateEliminations: 1,
        maxImmediateEliminations: 1,
        selectionWeightMultiplier: 1,
      }),
    ];
    const selectedShapes = new Set<string>();

    for (const seed of createSelectorTestSeeds("phase-5-3-shapes", 32)) {
      const first = selectControlledFatal({
        profiles,
        tributeCount: 8,
        fatalityDeficit: 1,
        random: createSeededRandom(seed),
        seed,
      });
      const repeated = selectControlledFatal({
        profiles,
        tributeCount: 8,
        fatalityDeficit: 1,
        random: createSeededRandom(seed),
        seed,
      });

      expect(repeated.selection?.definition.id).toBe(first.selection?.definition.id);

      if (!first.selection) {
        throw new Error(`Expected seed "${seed}" to select a controlled fatal event.`);
      }

      selectedShapes.add(getEventParticipantShape(first.selection.definition));
    }

    expect(selectedShapes).toEqual(new Set(["solo", "pair", "trio", "group-four-plus"]));
  });
});
