// Generated by implement-phase-5-4.sh
import { describe, expect, it } from "vitest";

import {
  canCoverBloodbathFleeParticipants,
  canCoverBloodbathFleeParticipantsAfterDefinition,
} from "~/game/bloodbath/bloodbath-flee-planner";
import {
  BLOODBATH_POST_TARGET_SOLO_CEILING_WEIGHT_MULTIPLIER,
  canCoverBloodbathPostTargetParticipants,
  canCoverBloodbathPostTargetParticipantsAfterDefinition,
} from "~/game/bloodbath/bloodbath-post-target-planner";
import {
  selectFleeBloodbathEvent,
  selectPostTargetCornucopiaEvent,
  type BloodbathAcquisitionSelection,
} from "~/game/bloodbath/bloodbath-sequencer";
import {
  createFixedRandomSource,
  createSelectorTestContext,
  createSelectorTestDefinition,
  createSelectorTestSeeds,
  createSelectorTestTributes,
  withSelectorTestItem,
} from "~/game/events/authoring/testing/selector-test-fixtures";
import { createSeededRandom, type RandomSource } from "~/game/engine/random";
import { getEventParticipantShape } from "~/game/events/event-participant-shape";
import type { EventDefinition } from "~/game/events/event-schema";
import type { GameTribute, RoundReference } from "~/game/types/game-state";

const BLOODBATH_ROUND = {
  day: 1,
  period: "day",
} as const satisfies RoundReference;

interface ControlledSelectorOptions {
  definitions: readonly EventDefinition[];
  tributeCount?: number;
  tributes?: readonly GameTribute[];
  remainingTributeIds?: readonly string[];
  usedDefinitionIds?: readonly string[];
  random?: RandomSource;
  seed?: string;
}

interface PostTargetSelectorOptions extends ControlledSelectorOptions {
  selectedEventCount?: number;
  selectedSoloEventCount?: number;
}

interface ControlledSelectionResult {
  selection: BloodbathAcquisitionSelection | null;
  startingRemainingTributeIds: readonly string[];
  remainingTributes: GameTribute[];
}

function createRemainingTributes(
  livingTributes: readonly GameTribute[],
  remainingTributeIds?: readonly string[],
): GameTribute[] {
  if (!remainingTributeIds) {
    return [...livingTributes];
  }

  const allowedTributeIds = new Set(remainingTributeIds);

  return livingTributes.filter((tribute) => allowedTributeIds.has(tribute.id));
}

function selectControlledPostTarget({
  definitions,
  tributeCount = 6,
  tributes,
  remainingTributeIds,
  usedDefinitionIds = [],
  selectedEventCount = 0,
  selectedSoloEventCount = 0,
  random = createFixedRandomSource(),
  seed = "phase-5-4-post-target",
}: PostTargetSelectorOptions): ControlledSelectionResult {
  const context = createSelectorTestContext({
    tributeCount,
    ...(tributes ? { tributes } : {}),
    seed,
    round: BLOODBATH_ROUND,
  });
  const remainingTributes = createRemainingTributes(context.livingTributes, remainingTributeIds);
  const startingRemainingTributeIds = remainingTributes.map((tribute) => tribute.id);
  const selection = selectPostTargetCornucopiaEvent(
    context.state,
    BLOODBATH_ROUND,
    remainingTributes,
    new Set(usedDefinitionIds),
    selectedEventCount,
    selectedSoloEventCount,
    random,
    definitions,
  );

  return {
    selection,
    startingRemainingTributeIds,
    remainingTributes,
  };
}

function selectControlledFlee({
  definitions,
  tributeCount = 6,
  tributes,
  remainingTributeIds,
  usedDefinitionIds = [],
  random = createFixedRandomSource(),
  seed = "phase-5-4-flee",
}: ControlledSelectorOptions): ControlledSelectionResult {
  const context = createSelectorTestContext({
    tributeCount,
    ...(tributes ? { tributes } : {}),
    seed,
    round: BLOODBATH_ROUND,
  });
  const remainingTributes = createRemainingTributes(context.livingTributes, remainingTributeIds);
  const startingRemainingTributeIds = remainingTributes.map((tribute) => tribute.id);
  const selection = selectFleeBloodbathEvent(
    context.state,
    BLOODBATH_ROUND,
    remainingTributes,
    new Set(usedDefinitionIds),
    random,
    false,
    definitions,
  );

  return {
    selection,
    startingRemainingTributeIds,
    remainingTributes,
  };
}

function createShapeDefinition(
  id: string,
  participantCount: number,
  baseWeight = 1,
): EventDefinition {
  return createSelectorTestDefinition({
    id,
    participantCount,
    baseWeight,
  });
}

function selectedParticipantIds(selection: BloodbathAcquisitionSelection | null): string[] {
  return [
    ...new Set(
      Object.values(selection?.participantsByRole ?? {})
        .flat()
        .map((tribute) => tribute.id),
    ),
  ];
}

describe("Phase 5.4 exact-cover planning", () => {
  it.each([
    {
      label: "solo plus pair",
      definitions: [createShapeDefinition("cover-solo", 1), createShapeDefinition("cover-pair", 2)],
      participantCount: 3,
      expected: true,
    },
    {
      label: "pair plus trio",
      definitions: [createShapeDefinition("cover-pair", 2), createShapeDefinition("cover-trio", 3)],
      participantCount: 5,
      expected: true,
    },
    {
      label: "solo plus trio plus quartet",
      definitions: [
        createShapeDefinition("cover-solo", 1),
        createShapeDefinition("cover-trio", 3),
        createShapeDefinition("cover-quartet", 4),
      ],
      participantCount: 8,
      expected: true,
    },
    {
      label: "one pair cannot be reused",
      definitions: [createShapeDefinition("single-pair", 2)],
      participantCount: 4,
      expected: false,
    },
    {
      label: "no shape combination reaches the target",
      definitions: [
        createShapeDefinition("unreachable-pair", 2),
        createShapeDefinition("unreachable-quartet", 4),
      ],
      participantCount: 5,
      expected: false,
    },
  ])(
    "evaluates $label for both nonfatal planners",
    ({ definitions, participantCount, expected }) => {
      expect(
        canCoverBloodbathPostTargetParticipants({
          definitions,
          participantCount,
        }),
      ).toBe(expected);
      expect(
        canCoverBloodbathFleeParticipants({
          definitions,
          participantCount,
        }),
      ).toBe(expected);
    },
  );

  it("rejects an attractive shape when it would strand the remaining group", () => {
    const quartet = createShapeDefinition("stranding-quartet", 4);
    const pair = createShapeDefinition("safe-pair", 2);
    const trio = createShapeDefinition("safe-trio", 3);

    expect(
      canCoverBloodbathPostTargetParticipantsAfterDefinition({
        definition: quartet,
        remainingDefinitions: [pair, trio],
        availableParticipantCount: 5,
      }),
    ).toBe(false);
    expect(
      canCoverBloodbathFleeParticipantsAfterDefinition({
        definition: quartet,
        remainingDefinitions: [pair, trio],
        availableParticipantCount: 5,
      }),
    ).toBe(false);

    expect(
      canCoverBloodbathPostTargetParticipantsAfterDefinition({
        definition: pair,
        remainingDefinitions: [quartet, trio],
        availableParticipantCount: 5,
      }),
    ).toBe(true);
    expect(
      canCoverBloodbathFleeParticipantsAfterDefinition({
        definition: trio,
        remainingDefinitions: [quartet, pair],
        availableParticipantCount: 5,
      }),
    ).toBe(true);
  });
});

describe("Phase 5.4 post-target Cornucopia selection", () => {
  it("filters a stranding quartet before the unified weighted draw", () => {
    const result = selectControlledPostTarget({
      definitions: [
        createShapeDefinition("stranding-quartet", 4, 100),
        createShapeDefinition("safe-pair", 2),
        createShapeDefinition("safe-trio", 3),
      ],
      tributeCount: 5,
      random: createFixedRandomSource(0),
    });

    expect(result.selection?.definition.id).toBe("safe-pair");
    expect(result.remainingTributes).toHaveLength(3);
  });

  it("covers every remaining entrant across sequential unique definitions", () => {
    const definitions = [
      createShapeDefinition("stranding-quartet", 4, 100),
      createShapeDefinition("cover-pair", 2),
      createShapeDefinition("cover-trio", 3),
    ];
    const context = createSelectorTestContext({
      tributeCount: 5,
      seed: "phase-5-4-post-target-sequence",
      round: BLOODBATH_ROUND,
    });
    const remainingTributes = [...context.livingTributes];
    const usedDefinitionIds = new Set<string>();

    const first = selectPostTargetCornucopiaEvent(
      context.state,
      BLOODBATH_ROUND,
      remainingTributes,
      usedDefinitionIds,
      0,
      0,
      createFixedRandomSource(0),
      definitions,
    );
    usedDefinitionIds.add(first.definition.id);

    const second = selectPostTargetCornucopiaEvent(
      context.state,
      BLOODBATH_ROUND,
      remainingTributes,
      usedDefinitionIds,
      1,
      0,
      createFixedRandomSource(0),
      definitions,
    );
    usedDefinitionIds.add(second.definition.id);

    expect([first.definition.id, second.definition.id]).toEqual(["cover-pair", "cover-trio"]);
    expect(usedDefinitionIds.size).toBe(2);
    expect(remainingTributes).toEqual([]);
  });

  it("prefers interaction regardless of whether the pair appears before or after solos", () => {
    const soloA = createShapeDefinition("ordered-solo-a", 1);
    const soloB = createShapeDefinition("ordered-solo-b", 1);
    const pair = createShapeDefinition("ordered-pair", 2);

    const soloFirst = selectControlledPostTarget({
      definitions: [soloA, pair, soloB],
      tributeCount: 3,
      selectedEventCount: 3,
      selectedSoloEventCount: 0,
      random: createFixedRandomSource(0.5),
      seed: "phase-5-4-post-target-solo-first",
    });
    const pairFirst = selectControlledPostTarget({
      definitions: [pair, soloA, soloB],
      tributeCount: 3,
      selectedEventCount: 3,
      selectedSoloEventCount: 0,
      random: createFixedRandomSource(0.5),
      seed: "phase-5-4-post-target-pair-first",
    });

    expect(soloFirst.selection?.definition.id).toBe("ordered-pair");
    expect(pairFirst.selection?.definition.id).toBe("ordered-pair");
  });

  it("keeps the post-target solo ceiling soft rather than banning solo events", () => {
    const definitions = [
      createShapeDefinition("ceiling-solo-a", 1),
      createShapeDefinition("ceiling-pair", 2),
      createShapeDefinition("ceiling-solo-b", 1),
    ];

    const soloStillReachable = selectControlledPostTarget({
      definitions,
      tributeCount: 3,
      selectedEventCount: 0,
      selectedSoloEventCount: 0,
      random: createFixedRandomSource(0),
      seed: "phase-5-4-soft-ceiling-solo",
    });
    const pairFavoured = selectControlledPostTarget({
      definitions,
      tributeCount: 3,
      selectedEventCount: 0,
      selectedSoloEventCount: 0,
      random: createFixedRandomSource(0.1),
      seed: "phase-5-4-soft-ceiling-pair",
    });

    expect(BLOODBATH_POST_TARGET_SOLO_CEILING_WEIGHT_MULTIPLIER).toBeGreaterThan(0);
    expect(soloStillReachable.selection?.definition.id).toBe("ceiling-solo-a");
    expect(pairFavoured.selection?.definition.id).toBe("ceiling-pair");
  });

  it("uses an eligible solo fallback when no interaction can fit", () => {
    const result = selectControlledPostTarget({
      definitions: [
        createShapeDefinition("fallback-pair", 2),
        createShapeDefinition("fallback-solo", 1),
      ],
      tributeCount: 1,
    });

    expect(result.selection?.definition.id).toBe("fallback-solo");
    expect(result.remainingTributes).toEqual([]);
  });

  it("respects used-definition limits", () => {
    const result = selectControlledPostTarget({
      definitions: [createShapeDefinition("used-solo", 1), createShapeDefinition("unused-solo", 1)],
      tributeCount: 1,
      usedDefinitionIds: ["used-solo"],
    });

    expect(result.selection?.definition.id).toBe("unused-solo");
  });

  it("selects an owned-item event only while its owner remains available", () => {
    const baseTributes = createSelectorTestTributes(2);
    const armedTribute = withSelectorTestItem(baseTributes[0]!, "knife");
    const unarmedTribute = baseTributes[1]!;
    const tributes = [armedTribute, unarmedTribute];
    const itemEvent = createSelectorTestDefinition({
      id: "owned-knife-acquisition",
      participantCount: 1,
      requiredItemDefinitionId: "knife",
      itemAccess: "owned",
    });
    const unarmedFallback = createSelectorTestDefinition({
      id: "unarmed-fallback",
      roles: [
        {
          id: "participants",
          count: 1,
          isEligible: (tribute) => tribute.id === unarmedTribute.id,
        },
      ],
    });
    const context = createSelectorTestContext({
      tributes,
      seed: "phase-5-4-owned-item",
      round: BLOODBATH_ROUND,
    });
    const remainingTributes = [...context.livingTributes];
    const usedDefinitionIds = new Set<string>();

    const first = selectPostTargetCornucopiaEvent(
      context.state,
      BLOODBATH_ROUND,
      remainingTributes,
      usedDefinitionIds,
      0,
      0,
      createFixedRandomSource(0),
      [itemEvent, unarmedFallback],
    );
    usedDefinitionIds.add(first.definition.id);

    expect(first.definition.id).toBe("owned-knife-acquisition");
    expect(selectedParticipantIds(first)).toEqual([armedTribute.id]);

    const second = selectPostTargetCornucopiaEvent(
      context.state,
      BLOODBATH_ROUND,
      remainingTributes,
      usedDefinitionIds,
      1,
      1,
      createFixedRandomSource(0),
      [itemEvent, unarmedFallback],
    );

    expect(second.definition.id).toBe("unarmed-fallback");
    expect(selectedParticipantIds(second)).toEqual([unarmedTribute.id]);
    expect(remainingTributes).toEqual([]);

    expect(() =>
      selectControlledPostTarget({
        definitions: [itemEvent],
        tributes,
        remainingTributeIds: [unarmedTribute.id],
      }),
    ).toThrow(/no unused nonfatal bloodbath event/i);
  });
});

describe("Phase 5.4 fleeing selection", () => {
  it.each([
    ["solo", 1],
    ["pair", 2],
    ["trio", 3],
    ["group-four-plus", 4],
  ] as const)(
    "selects a controlled %s event when it exactly covers the fleeing group",
    (expectedShape, participantCount) => {
      const result = selectControlledFlee({
        definitions: [createShapeDefinition(`flee-${expectedShape}`, participantCount)],
        tributeCount: participantCount,
      });

      expect(result.selection).not.toBeNull();
      expect(getEventParticipantShape(result.selection!.definition)).toBe(expectedShape);
      expect(result.remainingTributes).toEqual([]);
    },
  );

  it("filters a stranding group event before selecting a safe exact cover", () => {
    const result = selectControlledFlee({
      definitions: [
        createShapeDefinition("flee-stranding-quartet", 4, 100),
        createShapeDefinition("flee-safe-pair", 2),
        createShapeDefinition("flee-safe-trio", 3),
      ],
      tributeCount: 5,
      random: createFixedRandomSource(0),
    });

    expect(result.selection?.definition.id).toBe("flee-safe-pair");
    expect(result.remainingTributes).toHaveLength(3);
  });

  it("covers the fleeing group without repeating a definition", () => {
    const definitions = [
      createShapeDefinition("flee-stranding-quartet", 4, 100),
      createShapeDefinition("flee-cover-pair", 2),
      createShapeDefinition("flee-cover-trio", 3),
    ];
    const context = createSelectorTestContext({
      tributeCount: 5,
      seed: "phase-5-4-flee-sequence",
      round: BLOODBATH_ROUND,
    });
    const remainingTributes = [...context.livingTributes];
    const usedDefinitionIds = new Set<string>();

    const first = selectFleeBloodbathEvent(
      context.state,
      BLOODBATH_ROUND,
      remainingTributes,
      usedDefinitionIds,
      createFixedRandomSource(0),
      false,
      definitions,
    );

    expect(first?.definition.id).toBe("flee-cover-pair");
    usedDefinitionIds.add(first!.definition.id);

    const second = selectFleeBloodbathEvent(
      context.state,
      BLOODBATH_ROUND,
      remainingTributes,
      usedDefinitionIds,
      createFixedRandomSource(0),
      false,
      definitions,
    );

    expect(second?.definition.id).toBe("flee-cover-trio");
    usedDefinitionIds.add(second!.definition.id);

    expect(usedDefinitionIds.size).toBe(2);
    expect(remainingTributes).toEqual([]);
  });

  it("prefers interaction regardless of catalogue order while retaining solo fallback", () => {
    const soloA = createShapeDefinition("flee-ordered-solo-a", 1);
    const soloB = createShapeDefinition("flee-ordered-solo-b", 1);
    const pair = createShapeDefinition("flee-ordered-pair", 2);

    const soloFirst = selectControlledFlee({
      definitions: [soloA, pair, soloB],
      tributeCount: 3,
      random: createFixedRandomSource(0.5),
      seed: "phase-5-4-flee-solo-first",
    });
    const pairFirst = selectControlledFlee({
      definitions: [pair, soloA, soloB],
      tributeCount: 3,
      random: createFixedRandomSource(0.5),
      seed: "phase-5-4-flee-pair-first",
    });
    const soloFallback = selectControlledFlee({
      definitions: [pair, soloA],
      tributeCount: 1,
      seed: "phase-5-4-flee-solo-fallback",
    });

    expect(soloFirst.selection?.definition.id).toBe("flee-ordered-pair");
    expect(pairFirst.selection?.definition.id).toBe("flee-ordered-pair");
    expect(soloFallback.selection?.definition.id).toBe("flee-ordered-solo-a");
  });

  it("allows an authored fatal fleeing event and still enforces definition uniqueness", () => {
    const fatalPair = createSelectorTestDefinition({
      id: "flee-fatal-pair",
      participantCount: 2,
      category: "fatal",
      tags: ["fatal"],
      eliminationCount: 1,
    });
    const first = selectControlledFlee({
      definitions: [fatalPair],
      tributeCount: 2,
    });
    const repeated = selectControlledFlee({
      definitions: [fatalPair],
      tributeCount: 2,
      usedDefinitionIds: [fatalPair.id],
    });

    expect(first.selection?.definition.id).toBe("flee-fatal-pair");
    expect(first.remainingTributes).toEqual([]);
    expect(repeated.selection).toBeNull();
    expect(repeated.remainingTributes.map((tribute) => tribute.id)).toEqual(
      repeated.startingRemainingTributeIds,
    );
  });
});

describe("Phase 5.4 deterministic shape reachability", () => {
  it("reproduces seeded choices and reaches every shape in both unified selectors", () => {
    /*
     * Neutralize the intended shape multipliers so this test proves structural
     * reachability rather than retesting balance ratios:
     *
     * solo 5 x 0.2 = 1
     * pair/trio/group 1 x 1 = 1
     */
    const definitions = [
      createShapeDefinition("seeded-solo", 1, 5),
      createShapeDefinition("seeded-pair", 2),
      createShapeDefinition("seeded-trio", 3),
      createShapeDefinition("seeded-group", 4),
    ];
    const postTargetShapes = new Set<string>();
    const fleeShapes = new Set<string>();

    for (const seed of createSelectorTestSeeds("phase-5-4-shapes", 32)) {
      const firstPostTarget = selectControlledPostTarget({
        definitions,
        tributeCount: 10,
        selectedEventCount: 3,
        selectedSoloEventCount: 0,
        random: createSeededRandom(seed),
        seed,
      });
      const repeatedPostTarget = selectControlledPostTarget({
        definitions,
        tributeCount: 10,
        selectedEventCount: 3,
        selectedSoloEventCount: 0,
        random: createSeededRandom(seed),
        seed,
      });
      const firstFlee = selectControlledFlee({
        definitions,
        tributeCount: 10,
        random: createSeededRandom(seed),
        seed,
      });
      const repeatedFlee = selectControlledFlee({
        definitions,
        tributeCount: 10,
        random: createSeededRandom(seed),
        seed,
      });

      expect(repeatedPostTarget.selection?.definition.id).toBe(
        firstPostTarget.selection?.definition.id,
      );
      expect(repeatedFlee.selection?.definition.id).toBe(firstFlee.selection?.definition.id);

      postTargetShapes.add(getEventParticipantShape(firstPostTarget.selection!.definition));
      fleeShapes.add(getEventParticipantShape(firstFlee.selection!.definition));
    }

    const everyShape = new Set(["solo", "pair", "trio", "group-four-plus"]);

    expect(postTargetShapes).toEqual(everyShape);
    expect(fleeShapes).toEqual(everyShape);
  });
});
