// Generated by implement-phase-5-1.sh
import { describe, expect, it } from "vitest";

import {
  selectAuthoredFatalBloodbathEvent,
  selectFleeBloodbathEvent,
  selectPostTargetCornucopiaEvent,
} from "~/game/bloodbath/bloodbath-sequencer";
import {
  createFixedRandomSource,
  createSelectorTestContext,
  createSelectorTestDefinition,
  createSelectorTestFatalProfile,
} from "~/game/events/authoring/testing/selector-test-fixtures";

describe("controlled Bloodbath selector seams", () => {
  it("runs the production fatal selector against injected profiles", () => {
    const context = createSelectorTestContext({
      tributeCount: 2,
      seed: "controlled-fatal-selector",
      round: {
        day: 1,
        period: "day",
      },
    });
    const remainingTributes = [...context.livingTributes];
    const profile = createSelectorTestFatalProfile({
      id: "controlled-fatal-pair",
      participantCount: 2,
      minImmediateEliminations: 1,
      maxImmediateEliminations: 1,
    });

    const selection = selectAuthoredFatalBloodbathEvent(
      context.state,
      context.round,
      remainingTributes,
      1,
      0,
      new Set<string>(),
      createFixedRandomSource(),
      [profile],
    );

    expect(selection?.definition.id).toBe("controlled-fatal-pair");
    expect(Object.values(selection?.participantsByRole ?? {}).flat()).toHaveLength(2);
    expect(remainingTributes).toEqual([]);
  });

  it("runs the production post-target selector against injected definitions", () => {
    const context = createSelectorTestContext({
      tributeCount: 2,
      seed: "controlled-post-target-selector",
      round: {
        day: 1,
        period: "day",
      },
    });
    const remainingTributes = [...context.livingTributes];
    const definition = createSelectorTestDefinition({
      id: "controlled-post-target-pair",
      participantCount: 2,
    });

    const selection = selectPostTargetCornucopiaEvent(
      context.state,
      context.round,
      remainingTributes,
      new Set<string>(),
      0,
      0,
      createFixedRandomSource(),
      [definition],
    );

    expect(selection.definition.id).toBe("controlled-post-target-pair");
    expect(remainingTributes).toEqual([]);
  });

  it("runs the production flee selector against injected definitions", () => {
    const context = createSelectorTestContext({
      tributeCount: 2,
      seed: "controlled-flee-selector",
      round: {
        day: 1,
        period: "day",
      },
    });
    const remainingTributes = [...context.livingTributes];
    const definition = createSelectorTestDefinition({
      id: "controlled-flee-pair",
      participantCount: 2,
    });

    const selection = selectFleeBloodbathEvent(
      context.state,
      context.round,
      remainingTributes,
      new Set<string>(),
      createFixedRandomSource(),
      false,
      [definition],
    );

    expect(selection?.definition.id).toBe("controlled-flee-pair");
    expect(remainingTributes).toEqual([]);
  });
});
