import { CORNUCOPIA_ACQUISITION_EVENTS } from "./cornucopia-acquisition-events";
import {
  CORNUCOPIA_CONFLICT_EVENTS,
  CORNUCOPIA_GROUP_CONFLICT_EVENTS,
  CORNUCOPIA_PAIR_CONFLICT_EVENTS,
} from "./cornucopia-conflict-events";
import { CORNUCOPIA_FLAVOUR_ACQUISITION_EVENTS as BASE_CORNUCOPIA_FLAVOUR_ACQUISITION_EVENTS } from "./cornucopia-flavour-acquisition-events";
import {
  CORNUCOPIA_NONFATAL_PAIR_EVENTS as BASE_CORNUCOPIA_NONFATAL_PAIR_EVENTS,
  CORNUCOPIA_NONFATAL_QUARTET_EVENTS,
  CORNUCOPIA_NONFATAL_TRIO_EVENTS,
} from "./cornucopia-nonfatal-interaction-events";
import {
  CORNUCOPIA_FATAL_DELAYED_EVENTS,
  CORNUCOPIA_FATAL_TARGET_PROFILES as BASE_CORNUCOPIA_FATAL_TARGET_PROFILES,
} from "./cornucopia-fatal-events";
import { FLEE_EVENTS as BASE_FLEE_EVENTS } from "./flee-events";
import {
  STAT_GATED_BLOODBATH_EVENTS,
  STAT_GATED_CORNUCOPIA_FATAL_TARGET_PROFILES,
  STAT_GATED_CORNUCOPIA_FLAVOUR_EVENTS,
  STAT_GATED_CORNUCOPIA_NONFATAL_PAIR_EVENTS,
  STAT_GATED_FLEE_EVENTS,
} from "./stat-gated-events";

export const CORNUCOPIA_FLAVOUR_ACQUISITION_EVENTS = [
  ...BASE_CORNUCOPIA_FLAVOUR_ACQUISITION_EVENTS,
  ...STAT_GATED_CORNUCOPIA_FLAVOUR_EVENTS,
] as const;

export const CORNUCOPIA_FATAL_TARGET_PROFILES = [
  ...BASE_CORNUCOPIA_FATAL_TARGET_PROFILES,
  ...STAT_GATED_CORNUCOPIA_FATAL_TARGET_PROFILES,
] as const;

export const CORNUCOPIA_FATAL_BLOODBATH_EVENTS = [
  ...CORNUCOPIA_FATAL_TARGET_PROFILES.map(({ definition }) => definition),
  ...CORNUCOPIA_FATAL_DELAYED_EVENTS,
] as const;

export const CORNUCOPIA_NONFATAL_PAIR_EVENTS = [
  ...BASE_CORNUCOPIA_NONFATAL_PAIR_EVENTS,
  ...STAT_GATED_CORNUCOPIA_NONFATAL_PAIR_EVENTS,
] as const;

export const CORNUCOPIA_NONFATAL_INTERACTION_EVENTS = [
  ...CORNUCOPIA_NONFATAL_PAIR_EVENTS,
  ...CORNUCOPIA_NONFATAL_TRIO_EVENTS,
  ...CORNUCOPIA_NONFATAL_QUARTET_EVENTS,
] as const;

export const FLEE_EVENTS = [...BASE_FLEE_EVENTS, ...STAT_GATED_FLEE_EVENTS] as const;

export {
  CORNUCOPIA_ACQUISITION_EVENTS,
  CORNUCOPIA_CONFLICT_EVENTS,
  CORNUCOPIA_FATAL_DELAYED_EVENTS,
  CORNUCOPIA_GROUP_CONFLICT_EVENTS,
  CORNUCOPIA_NONFATAL_QUARTET_EVENTS,
  CORNUCOPIA_NONFATAL_TRIO_EVENTS,
  CORNUCOPIA_PAIR_CONFLICT_EVENTS,
  STAT_GATED_BLOODBATH_EVENTS,
  STAT_GATED_CORNUCOPIA_FATAL_TARGET_PROFILES,
  STAT_GATED_CORNUCOPIA_FLAVOUR_EVENTS,
  STAT_GATED_CORNUCOPIA_NONFATAL_PAIR_EVENTS,
  STAT_GATED_FLEE_EVENTS,
};

export const CORNUCOPIA_EVENTS = [
  ...CORNUCOPIA_ACQUISITION_EVENTS,
  ...CORNUCOPIA_FLAVOUR_ACQUISITION_EVENTS,
  ...CORNUCOPIA_FATAL_BLOODBATH_EVENTS,
  ...CORNUCOPIA_CONFLICT_EVENTS,
  ...CORNUCOPIA_NONFATAL_INTERACTION_EVENTS,
] as const;

export const BLOODBATH_EVENT_CATALOGUE = [...CORNUCOPIA_EVENTS, ...FLEE_EVENTS] as const;
