// Generated by implement-phase-7.sh
import { mkdir, writeFile } from "node:fs/promises";
import { performance } from "node:perf_hooks";
import { resolve } from "node:path";

import { assertGameStateInvariants } from "~/game/engine/game-invariants";
import { PHASE_1_EVENT_DISTRIBUTION_BASELINE } from "~/game/simulation/phase-1-event-distribution-baseline";
import { evaluateBalanceGuardrails } from "~/game/simulation/balance-guardrails";
import { collectBalanceMetrics } from "~/game/simulation/balance-metrics";
import {
  collectDistributionExperienceMetrics,
  evaluateDistributionRegressionGuardrails,
  formatDistributionGuardrailFailures,
} from "~/game/simulation/distribution-regression";
import { PHASE_6_DISTRIBUTION_BASELINE } from "~/game/simulation/distribution-regression-baseline";
import {
  collectEventDistributionMetrics,
  type EventDistributionGameSizeId,
  type EventDistributionMetrics,
} from "~/game/simulation/event-distribution-metrics";
import {
  simulateGameBatch,
  type SimulationBatchDefinition,
  type SimulationRun,
} from "~/game/simulation/simulation-runner";
import type { ResolvedEvent, RoundReference } from "~/game/types/game-state";

const REPORT_DIRECTORY = resolve(process.cwd(), "reports");
const MARKDOWN_PATH = resolve(REPORT_DIRECTORY, "phase-7-validation-report.md");
const JSON_PATH = resolve(REPORT_DIRECTORY, "phase-7-validation-report.json");

const MAXIMUM_AVERAGE_GAME_MS = 500;
const MAXIMUM_SEED_GROUP_PERFORMANCE_RATIO = 2.25;
const MINIMUM_AVERAGE_CONCENTRATION_IMPROVEMENT = 0.05;
const MINIMUM_LATER_DAY_IMPROVEMENT = 0.03;
const MAXIMUM_LATER_DAY_IMPROVEMENT = 0.25;

const SEED_GROUPS = [
  {
    id: "alpha",
    halfGames: 60,
    fullGames: 30,
  },
  {
    id: "beta",
    halfGames: 60,
    fullGames: 30,
  },
  {
    id: "gamma",
    halfGames: 60,
    fullGames: 30,
  },
] as const;

interface ValidationFailure {
  id: string;
  message: string;
  seed?: string;
}

interface SeedGroupResult {
  id: string;
  elapsedMs: number;
  averageGameMs: number;
  runs: readonly SimulationRun[];
  metrics: EventDistributionMetrics;
  invariantFailures: readonly ValidationFailure[];
}

interface HistoricalComparison {
  gameSize: EventDistributionGameSizeId;
  cornucopiaNonSolo: {
    phase1: number;
    current: number;
    delta: number;
  };
  fleeingNonSolo: {
    phase1: number;
    current: number;
    delta: number;
  };
  laterDayNonSolo: {
    phase1: number;
    current: number;
    delta: number;
  };
  cornucopiaTopFive: {
    phase1: number;
    current: number;
    delta: number;
  };
  cornucopiaTopTen: {
    phase1: number;
    current: number;
    delta: number;
  };
  cornucopiaMedianOverlap: {
    phase1: number;
    current: number;
    delta: number;
  };
}

function createBatchDefinitions(
  groupId: string,
  halfGames: number,
  fullGames: number,
): readonly SimulationBatchDefinition[] {
  return [
    {
      seedPrefix: `phase-7-${groupId}-half`,
      count: halfGames,
      districtCount: 6,
      captureSelectionDiagnostics: true,
    },
    {
      seedPrefix: `phase-7-${groupId}-full`,
      count: fullGames,
      districtCount: 12,
      captureSelectionDiagnostics: true,
    },
  ];
}

function getRoundKey(round: RoundReference): string {
  return `${round.day}:${round.period}`;
}

function isDayOneDaytime(round: RoundReference): boolean {
  return round.day === 1 && round.period === "day";
}

function isForcedLifecycleEvent(event: ResolvedEvent): boolean {
  return event.definitionId.startsWith("amicable-truce-separation-");
}

function getEliminations(event: ResolvedEvent) {
  return event.changes.filter(
    (change): change is Extract<ResolvedEvent["changes"][number], { type: "eliminate-tribute" }> =>
      change.type === "eliminate-tribute",
  );
}

function addFailure(
  failures: ValidationFailure[],
  id: string,
  message: string,
  seed?: string,
): void {
  failures.push({
    id,
    message,
    ...(seed ? { seed } : {}),
  });
}

function validateInventoryTransactions(run: SimulationRun, failures: ValidationFailure[]): void {
  const ownerByItemInstanceId = new Map<string, string>();
  const definitionByItemInstanceId = new Map<string, string>();

  for (const transaction of run.state.itemTransactions) {
    switch (transaction.type) {
      case "acquired": {
        if (ownerByItemInstanceId.has(transaction.itemInstanceId)) {
          addFailure(
            failures,
            "inventory:duplicate-acquisition",
            `Item ${transaction.itemInstanceId} was acquired more than once.`,
            run.seed,
          );
          break;
        }

        ownerByItemInstanceId.set(transaction.itemInstanceId, transaction.tributeId);
        definitionByItemInstanceId.set(transaction.itemInstanceId, transaction.definitionId);
        break;
      }

      case "consumed": {
        const owner = ownerByItemInstanceId.get(transaction.itemInstanceId);

        if (owner !== transaction.tributeId) {
          addFailure(
            failures,
            "inventory:invalid-consumption-owner",
            `Item ${transaction.itemInstanceId} was consumed by ` +
              `${transaction.tributeId}, but the tracked owner was ${owner ?? "missing"}.`,
            run.seed,
          );
        }
        break;
      }

      case "transferred": {
        const owner = ownerByItemInstanceId.get(transaction.itemInstanceId);

        if (owner !== transaction.fromTributeId) {
          addFailure(
            failures,
            "inventory:invalid-transfer-owner",
            `Item ${transaction.itemInstanceId} transferred from ` +
              `${transaction.fromTributeId}, but the tracked owner was ${owner ?? "missing"}.`,
            run.seed,
          );
        }

        if (transaction.fromTributeId === transaction.toTributeId) {
          addFailure(
            failures,
            "inventory:self-transfer",
            `Item ${transaction.itemInstanceId} transferred to the same tribute.`,
            run.seed,
          );
        }

        ownerByItemInstanceId.set(transaction.itemInstanceId, transaction.toTributeId);
        break;
      }
    }
  }

  for (const tribute of run.state.tributes) {
    for (const item of tribute.inventory) {
      const trackedOwner = ownerByItemInstanceId.get(item.id);
      const trackedDefinition = definitionByItemInstanceId.get(item.id);

      if (trackedOwner !== tribute.id) {
        addFailure(
          failures,
          "inventory:final-owner-mismatch",
          `Final inventory item ${item.id} belongs to ${tribute.id}, ` +
            `but its transaction owner is ${trackedOwner ?? "missing"}.`,
          run.seed,
        );
      }

      if (trackedDefinition !== item.definitionId) {
        addFailure(
          failures,
          "inventory:definition-mismatch",
          `Final inventory item ${item.id} has definition ${item.definitionId}, ` +
            `but its acquisition used ${trackedDefinition ?? "missing"}.`,
          run.seed,
        );
      }
    }
  }
}

function validateBloodbathParticipation(
  run: SimulationRun,
  openingEvents: readonly ResolvedEvent[],
  failures: ValidationFailure[],
): void {
  let fleeingHasBegun = false;
  const appearanceCountByTributeId = new Map<string, number>();

  for (const event of openingEvents) {
    if (event.feedGroup === "bloodbath-flee") {
      fleeingHasBegun = true;
    }

    if (event.feedGroup === "bloodbath-cornucopia" && fleeingHasBegun) {
      addFailure(
        failures,
        "bloodbath:ordering",
        `Cornucopia event ${event.definitionId} appeared after fleeing began.`,
        run.seed,
      );
    }

    if (event.feedGroup !== "bloodbath-cornucopia" && event.feedGroup !== "bloodbath-flee") {
      addFailure(
        failures,
        "bloodbath:missing-feed-group",
        `Opening event ${event.definitionId} has no valid Bloodbath feed group.`,
        run.seed,
      );
    }

    const uniqueParticipants = [...new Set(event.participantTributeIds)];
    const repeatedParticipants = uniqueParticipants.filter(
      (tributeId) => (appearanceCountByTributeId.get(tributeId) ?? 0) > 0,
    );

    if (repeatedParticipants.length > 0) {
      const isSafeSupplementalEvent =
        event.feedGroup === "bloodbath-cornucopia" &&
        uniqueParticipants.length === 2 &&
        repeatedParticipants.length === 2 &&
        getEliminations(event).length === 1 &&
        event.changes.every(
          (change) => change.type === "eliminate-tribute" || change.type === "increment-statistic",
        );

      if (!isSafeSupplementalEvent) {
        addFailure(
          failures,
          "bloodbath:invalid-repeat-participation",
          `Repeated participants in ${event.definitionId} do not match ` +
            `the safe supplemental pair-fatality contract.`,
          run.seed,
        );
      }
    }

    for (const tributeId of uniqueParticipants) {
      const nextCount = (appearanceCountByTributeId.get(tributeId) ?? 0) + 1;

      if (nextCount > 2) {
        addFailure(
          failures,
          "bloodbath:appearance-cap",
          `${tributeId} appeared ${nextCount} times in the Bloodbath.`,
          run.seed,
        );
      }

      appearanceCountByTributeId.set(tributeId, nextCount);
    }
  }

  const expectedTributeIds = new Set(run.state.tributes.map((tribute) => tribute.id));
  const actualTributeIds = new Set(appearanceCountByTributeId.keys());

  for (const tributeId of expectedTributeIds) {
    if (!actualTributeIds.has(tributeId)) {
      addFailure(
        failures,
        "bloodbath:missing-tribute",
        `${tributeId} never appeared in a Bloodbath event.`,
        run.seed,
      );
    }
  }

  for (const event of openingEvents.filter(
    (candidate) => candidate.feedGroup === "bloodbath-flee",
  )) {
    for (const tributeId of new Set(event.participantTributeIds)) {
      if (appearanceCountByTributeId.get(tributeId) !== 1) {
        addFailure(
          failures,
          "bloodbath:flee-repeat",
          `Fleeing tribute ${tributeId} appeared more than once.`,
          run.seed,
        );
      }
    }
  }
}

function validateRun(run: SimulationRun): ValidationFailure[] {
  const failures: ValidationFailure[] = [];

  try {
    assertGameStateInvariants(run.state);
  } catch (error) {
    addFailure(
      failures,
      "game-state:invariant",
      error instanceof Error ? error.message : String(error),
      run.seed,
    );
  }

  if (run.state.phase !== "victory" || run.state.victoryOutcome === null) {
    addFailure(failures, "game:victory", "Game did not reach a victory outcome.", run.seed);
  }

  const tributeIds = new Set(run.state.tributes.map((tribute) => tribute.id));
  const aliveTributeIds = new Set(tributeIds);
  const eventIds = new Set<string>();
  const definitionIdsByRound = new Map<string, Set<string>>();
  const participantIdsByRound = new Map<string, Set<string>>();

  const openingEvents = run.state.eventHistory.filter(
    (event) => event.kind === "primary" && isDayOneDaytime(event.round),
  );

  validateBloodbathParticipation(run, openingEvents, failures);

  for (const event of run.state.eventHistory) {
    if (eventIds.has(event.id)) {
      addFailure(
        failures,
        "event-history:duplicate-event-id",
        `Resolved event ID ${event.id} appears more than once.`,
        run.seed,
      );
    }

    eventIds.add(event.id);

    const uniqueParticipantIds = [...new Set(event.participantTributeIds)];

    for (const tributeId of uniqueParticipantIds) {
      if (!tributeIds.has(tributeId)) {
        addFailure(
          failures,
          "event-history:unknown-participant",
          `${event.definitionId} references unknown tribute ${tributeId}.`,
          run.seed,
        );
      }

      if (
        (event.kind === "primary" || event.kind === "preparation") &&
        !aliveTributeIds.has(tributeId)
      ) {
        addFailure(
          failures,
          "event-history:dead-participant",
          `${event.definitionId} includes already-dead tribute ${tributeId}.`,
          run.seed,
        );
      }
    }

    if (event.kind === "primary" && !isForcedLifecycleEvent(event)) {
      const roundKey = getRoundKey(event.round);
      const roundDefinitions = definitionIdsByRound.get(roundKey) ?? new Set<string>();

      if (roundDefinitions.has(event.definitionId)) {
        addFailure(
          failures,
          "event-history:definition-repeat",
          `${event.definitionId} repeats within ${roundKey}.`,
          run.seed,
        );
      }

      roundDefinitions.add(event.definitionId);
      definitionIdsByRound.set(roundKey, roundDefinitions);

      if (!isDayOneDaytime(event.round)) {
        const roundParticipants = participantIdsByRound.get(roundKey) ?? new Set<string>();

        for (const tributeId of uniqueParticipantIds) {
          if (roundParticipants.has(tributeId)) {
            addFailure(
              failures,
              "event-history:ordinary-participant-repeat",
              `${tributeId} participates twice in ordinary primary events during ${roundKey}.`,
              run.seed,
            );
          }

          roundParticipants.add(tributeId);
        }

        participantIdsByRound.set(roundKey, roundParticipants);
      }
    }

    const eventParticipantIds = new Set(event.participantTributeIds);
    const eliminations = getEliminations(event);

    for (const elimination of eliminations) {
      if (!tributeIds.has(elimination.tributeId)) {
        addFailure(
          failures,
          "elimination:unknown-victim",
          `${event.definitionId} eliminates unknown tribute ${elimination.tributeId}.`,
          run.seed,
        );
      }

      if (!aliveTributeIds.has(elimination.tributeId)) {
        addFailure(
          failures,
          "elimination:duplicate-death",
          `${elimination.tributeId} was eliminated after already dying.`,
          run.seed,
        );
      }

      if (!eventParticipantIds.has(elimination.tributeId)) {
        addFailure(
          failures,
          "elimination:victim-not-participant",
          `${elimination.tributeId} dies in ${event.definitionId} without appearing as a participant.`,
          run.seed,
        );
      }

      if (new Set(elimination.killerTributeIds).size !== elimination.killerTributeIds.length) {
        addFailure(
          failures,
          "elimination:duplicate-killer",
          `${event.definitionId} repeats a killer attribution.`,
          run.seed,
        );
      }

      for (const killerTributeId of elimination.killerTributeIds) {
        if (!tributeIds.has(killerTributeId)) {
          addFailure(
            failures,
            "elimination:unknown-killer",
            `${event.definitionId} attributes a kill to unknown tribute ${killerTributeId}.`,
            run.seed,
          );
        }

        if (killerTributeId === elimination.tributeId) {
          addFailure(
            failures,
            "elimination:self-kill-attribution",
            `${event.definitionId} attributes a tribute's death to themself.`,
            run.seed,
          );
        }
      }
    }

    for (const elimination of eliminations) {
      aliveTributeIds.delete(elimination.tributeId);
    }
  }

  for (const tribute of run.state.tributes) {
    if (!tribute.death) {
      continue;
    }

    const deathEvent = run.state.eventHistory.find(
      (event) => event.id === tribute.death?.resolvedEventId,
    );
    const matchingElimination = deathEvent?.changes
      .filter(
        (
          change,
        ): change is Extract<ResolvedEvent["changes"][number], { type: "eliminate-tribute" }> =>
          change.type === "eliminate-tribute",
      )
      .find((change) => change.tributeId === tribute.id);

    if (!deathEvent || !matchingElimination) {
      addFailure(
        failures,
        "event-history:death-link",
        `${tribute.id}'s death does not link to a matching resolved event.`,
        run.seed,
      );
    }
  }

  validateInventoryTransactions(run, failures);

  return failures;
}

function getOpeningEliminationRate(run: SimulationRun): number {
  const eliminatedIds = new Set(
    run.state.eventHistory
      .filter((event) => isDayOneDaytime(event.round))
      .flatMap((event) => getEliminations(event).map((elimination) => elimination.tributeId)),
  );

  return eliminatedIds.size / run.state.tributes.length;
}

function average(values: readonly number[]): number {
  return values.length === 0
    ? 0
    : values.reduce((total, value) => total + value, 0) / values.length;
}

function formatRate(value: number): string {
  return `${(value * 100).toFixed(1)}%`;
}

function formatSignedRate(value: number): string {
  const percentage = value * 100;
  const sign = percentage >= 0 ? "+" : "";

  return `${sign}${percentage.toFixed(1)} pp`;
}

function createHistoricalComparison(
  metrics: EventDistributionMetrics,
  gameSize: EventDistributionGameSizeId,
): HistoricalComparison {
  const currentPools = metrics.gameSizes[gameSize].pools;
  const historical = PHASE_1_EVENT_DISTRIBUTION_BASELINE[gameSize];

  const createDelta = (phase1: number, current: number) => ({
    phase1,
    current,
    delta: current - phase1,
  });

  return {
    gameSize,
    cornucopiaNonSolo: createDelta(
      historical.cornucopiaNonSoloShare,
      currentPools["bloodbath-cornucopia"].nonSoloShare,
    ),
    fleeingNonSolo: createDelta(
      historical.fleeingNonSoloShare,
      currentPools["bloodbath-flee"].nonSoloShare,
    ),
    laterDayNonSolo: createDelta(
      historical.laterDayNonSoloShare,
      currentPools["later-day"].nonSoloShare,
    ),
    cornucopiaTopFive: createDelta(
      historical.cornucopiaTopFiveSelectionShare,
      currentPools["bloodbath-cornucopia"].concentration.topFiveSelectionShare,
    ),
    cornucopiaTopTen: createDelta(
      historical.cornucopiaTopTenSelectionShare,
      currentPools["bloodbath-cornucopia"].concentration.topTenSelectionShare,
    ),
    cornucopiaMedianOverlap: createDelta(
      historical.cornucopiaMedianConsecutiveOverlap,
      currentPools["bloodbath-cornucopia"].consecutiveGameOverlap.median,
    ),
  };
}

function getHistoricalComparisonFailures(
  comparisons: readonly HistoricalComparison[],
): ValidationFailure[] {
  const failures: ValidationFailure[] = [];

  for (const comparison of comparisons) {
    if (comparison.cornucopiaNonSolo.delta < 0) {
      addFailure(
        failures,
        "phase1:cornucopia-non-solo",
        `${comparison.gameSize} Cornucopia non-solo share regressed by ` +
          `${formatSignedRate(comparison.cornucopiaNonSolo.delta)}.`,
      );
    }

    if (comparison.fleeingNonSolo.delta < 0) {
      addFailure(
        failures,
        "phase1:fleeing-non-solo",
        `${comparison.gameSize} fleeing non-solo share regressed by ` +
          `${formatSignedRate(comparison.fleeingNonSolo.delta)}.`,
      );
    }

    if (
      comparison.laterDayNonSolo.delta < MINIMUM_LATER_DAY_IMPROVEMENT ||
      comparison.laterDayNonSolo.delta > MAXIMUM_LATER_DAY_IMPROVEMENT
    ) {
      addFailure(
        failures,
        "phase1:later-day-moderate-increase",
        `${comparison.gameSize} Later-Day non-solo change was ` +
          `${formatSignedRate(comparison.laterDayNonSolo.delta)}; expected ` +
          `${formatSignedRate(MINIMUM_LATER_DAY_IMPROVEMENT)} to ` +
          `${formatSignedRate(MAXIMUM_LATER_DAY_IMPROVEMENT)}.`,
      );
    }
  }

  const historicalAverageTopFive = average(
    comparisons.map((comparison) => comparison.cornucopiaTopFive.phase1),
  );
  const currentAverageTopFive = average(
    comparisons.map((comparison) => comparison.cornucopiaTopFive.current),
  );
  const concentrationImprovement = historicalAverageTopFive - currentAverageTopFive;

  if (concentrationImprovement < MINIMUM_AVERAGE_CONCENTRATION_IMPROVEMENT) {
    addFailure(
      failures,
      "phase1:cornucopia-concentration",
      `Average Cornucopia top-five concentration improved by only ` +
        `${formatSignedRate(concentrationImprovement)}; expected at least ` +
        `${formatSignedRate(MINIMUM_AVERAGE_CONCENTRATION_IMPROVEMENT)}.`,
    );
  }

  return failures;
}

function summarizeComparison(comparison: HistoricalComparison): string[] {
  const row = (
    label: string,
    metric: { phase1: number; current: number; delta: number },
    formatter: (value: number) => string = formatRate,
  ) =>
    `| ${label} | ${formatter(metric.phase1)} | ` +
    `${formatter(metric.current)} | ${formatSignedRate(metric.delta)} |`;

  return [
    `### ${comparison.gameSize}`,
    "",
    "| Metric | Phase 1 | Phase 7 | Change |",
    "|---|---:|---:|---:|",
    row("Cornucopia non-solo", comparison.cornucopiaNonSolo),
    row("Fleeing non-solo", comparison.fleeingNonSolo),
    row("Day 2+ non-solo", comparison.laterDayNonSolo),
    row("Cornucopia top five", comparison.cornucopiaTopFive),
    row("Cornucopia top ten", comparison.cornucopiaTopTen),
    row("Cornucopia median overlap", comparison.cornucopiaMedianOverlap, (value) =>
      value.toFixed(2),
    ),
    "",
  ];
}

async function runSeedGroup(
  id: string,
  halfGames: number,
  fullGames: number,
): Promise<SeedGroupResult> {
  const startedAt = performance.now();
  const runs = simulateGameBatch(createBatchDefinitions(id, halfGames, fullGames));
  const elapsedMs = performance.now() - startedAt;
  const invariantFailures = runs.flatMap(validateRun);

  return {
    id,
    elapsedMs,
    averageGameMs: elapsedMs / runs.length,
    runs,
    metrics: collectEventDistributionMetrics(runs),
    invariantFailures,
  };
}

const groupResults: SeedGroupResult[] = [];

for (const group of SEED_GROUPS) {
  console.log(
    `Simulating Phase 7 seed group ${group.id} ` +
      `(${group.halfGames} Half / ${group.fullGames} Full)...`,
  );

  groupResults.push(await runSeedGroup(group.id, group.halfGames, group.fullGames));
}

const allRuns = groupResults.flatMap((group) => group.runs);
const aggregateMetrics = collectEventDistributionMetrics(allRuns);
const aggregateExperience = collectDistributionExperienceMetrics(allRuns);
const aggregateBalanceMetrics = collectBalanceMetrics(allRuns);
const aggregateBalanceGuardrails = evaluateBalanceGuardrails(aggregateBalanceMetrics);
const distributionGuardrails = evaluateDistributionRegressionGuardrails({
  metrics: aggregateMetrics,
  experience: aggregateExperience,
  baseline: PHASE_6_DISTRIBUTION_BASELINE,
});

const comparisons = (["half-game", "full-game"] as const).map((gameSize) =>
  createHistoricalComparison(aggregateMetrics, gameSize),
);

const failures: ValidationFailure[] = [
  ...groupResults.flatMap((group) => group.invariantFailures),
  ...getHistoricalComparisonFailures(comparisons),
];

for (const guardrail of aggregateBalanceGuardrails) {
  if (!guardrail.passed) {
    addFailure(
      failures,
      `balance:${guardrail.id}`,
      `${guardrail.label}: actual ${guardrail.actual}; ` + `expected ${guardrail.expected}.`,
    );
  }
}

for (const guardrail of distributionGuardrails) {
  if (!guardrail.passed) {
    addFailure(
      failures,
      `distribution:${guardrail.id}`,
      formatDistributionGuardrailFailures([guardrail]),
    );
  }
}

const openingEliminationRates = allRuns.map(getOpeningEliminationRate);
const averageOpeningEliminationRate = average(openingEliminationRates);

if (averageOpeningEliminationRate < 0.4 || averageOpeningEliminationRate > 0.6) {
  addFailure(
    failures,
    "fatality:opening-average",
    `Average opening elimination rate was ` +
      `${formatRate(averageOpeningEliminationRate)}; expected 40.0%–60.0%.`,
  );
}

if (openingEliminationRates.some((rate) => rate <= 0 || rate >= 0.7)) {
  addFailure(
    failures,
    "fatality:opening-per-game",
    "At least one game had no opening death or eliminated 70%+ of the field.",
  );
}

for (const group of groupResults) {
  if (group.averageGameMs > MAXIMUM_AVERAGE_GAME_MS) {
    addFailure(
      failures,
      "performance:absolute",
      `Seed group ${group.id} averaged ` +
        `${group.averageGameMs.toFixed(1)} ms/game; expected no more than ` +
        `${MAXIMUM_AVERAGE_GAME_MS.toFixed(1)} ms/game.`,
    );
  }
}

const groupAverageTimes = groupResults.map((group) => group.averageGameMs);
const fastestGroupMs = Math.min(...groupAverageTimes);
const slowestGroupMs = Math.max(...groupAverageTimes);
const performanceRatio = fastestGroupMs === 0 ? 1 : slowestGroupMs / fastestGroupMs;

if (performanceRatio > MAXIMUM_SEED_GROUP_PERFORMANCE_RATIO) {
  addFailure(
    failures,
    "performance:seed-group-spread",
    `Slowest seed group was ${performanceRatio.toFixed(2)}× the fastest; ` +
      `expected no more than ${MAXIMUM_SEED_GROUP_PERFORMANCE_RATIO.toFixed(2)}×.`,
  );
}

const groupSummaries = groupResults.map((group) => ({
  id: group.id,
  games: group.runs.length,
  elapsedMs: group.elapsedMs,
  averageGameMs: group.averageGameMs,
  halfGame: {
    cornucopiaNonSolo:
      group.metrics.gameSizes["half-game"].pools["bloodbath-cornucopia"].nonSoloShare,
    fleeingNonSolo: group.metrics.gameSizes["half-game"].pools["bloodbath-flee"].nonSoloShare,
    laterDayNonSolo: group.metrics.gameSizes["half-game"].pools["later-day"].nonSoloShare,
  },
  fullGame: {
    cornucopiaNonSolo:
      group.metrics.gameSizes["full-game"].pools["bloodbath-cornucopia"].nonSoloShare,
    fleeingNonSolo: group.metrics.gameSizes["full-game"].pools["bloodbath-flee"].nonSoloShare,
    laterDayNonSolo: group.metrics.gameSizes["full-game"].pools["later-day"].nonSoloShare,
  },
  invariantFailures: group.invariantFailures.length,
}));

const markdown = [
  "# Phase 7 — Full Stress and Invariant Validation",
  "",
  `Generated from ${allRuns.length} deterministic games across ` +
    `${groupResults.length} seed groups.`,
  "",
  `**Result:** ${failures.length === 0 ? "PASS" : "FAIL"}`,
  "",
  "## Seed groups and performance",
  "",
  "| Group | Games | Total time | Average per game | Invariant failures |",
  "|---|---:|---:|---:|---:|",
  ...groupResults.map(
    (group) =>
      `| ${group.id} | ${group.runs.length} | ` +
      `${(group.elapsedMs / 1000).toFixed(2)} s | ` +
      `${group.averageGameMs.toFixed(1)} ms | ` +
      `${group.invariantFailures.length} |`,
  ),
  "",
  `Slowest/fastest ratio: **${performanceRatio.toFixed(2)}×**.`,
  "",
  "## Phase 1 comparison",
  "",
  ...comparisons.flatMap(summarizeComparison),
  "## Fatality and completion",
  "",
  `- Games reaching victory: ${
    allRuns.filter((run) => run.state.phase === "victory" && run.state.victoryOutcome !== null)
      .length
  }/${allRuns.length}`,
  `- Average opening elimination rate: ${formatRate(averageOpeningEliminationRate)}`,
  `- Minimum opening elimination rate: ${formatRate(Math.min(...openingEliminationRates))}`,
  `- Maximum opening elimination rate: ${formatRate(Math.max(...openingEliminationRates))}`,
  `- Sole victories: ${aggregateBalanceMetrics.victories.sole}`,
  `- Joint victories: ${aggregateBalanceMetrics.victories.joint}`,
  "",
  "## Guardrails",
  "",
  `- Balance guardrails: ${
    aggregateBalanceGuardrails.filter((guardrail) => guardrail.passed).length
  }/${aggregateBalanceGuardrails.length} passed`,
  `- Distribution guardrails: ${
    distributionGuardrails.filter((guardrail) => guardrail.passed).length
  }/${distributionGuardrails.length} passed`,
  "",
  "## Validated invariants",
  "",
  "- Every simulation passes game-state invariants after every round.",
  "- Every primary and preparation participant exists and is alive when the event begins.",
  "- Primary definitions do not repeat within a prohibited round scope.",
  "- Ordinary round participants are not reused across primary events.",
  "- Bloodbath repeats obey the supplemental pair-fatality contract.",
  "- Killer IDs exist, are unique, and are not self-attributed.",
  "- Tribute deaths link to matching resolved-event eliminations.",
  "- Inventory acquisitions, consumption, ownership, and transfers form a valid chain.",
  "- Aftermath and status-resolution histories may reference dead tributes for narrative and attribution, but every referenced tribute exists.",
  "- Final status, inventory, relationship, vendetta, and truce state passes game invariants.",
  "",
  "## Failures",
  "",
  ...(failures.length === 0
    ? ["None.", ""]
    : failures.flatMap((failure) => [
        `- **${failure.id}**${
          failure.seed ? ` (${failure.seed})` : ""
        }: ${failure.message.replaceAll("\n", " ")}`,
      ])),
].join("\n");

await mkdir(REPORT_DIRECTORY, {
  recursive: true,
});

await Promise.all([
  writeFile(MARKDOWN_PATH, `${markdown}\n`, "utf8"),
  writeFile(
    JSON_PATH,
    `${JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        configuration: {
          seedGroups: SEED_GROUPS,
          maximumAverageGameMs: MAXIMUM_AVERAGE_GAME_MS,
          maximumSeedGroupPerformanceRatio: MAXIMUM_SEED_GROUP_PERFORMANCE_RATIO,
          minimumAverageConcentrationImprovement: MINIMUM_AVERAGE_CONCENTRATION_IMPROVEMENT,
          minimumLaterDayImprovement: MINIMUM_LATER_DAY_IMPROVEMENT,
          maximumLaterDayImprovement: MAXIMUM_LATER_DAY_IMPROVEMENT,
        },
        groupSummaries,
        aggregate: {
          games: allRuns.length,
          averageOpeningEliminationRate,
          minimumOpeningEliminationRate: Math.min(...openingEliminationRates),
          maximumOpeningEliminationRate: Math.max(...openingEliminationRates),
          performanceRatio,
          comparisons,
          balanceGuardrails: aggregateBalanceGuardrails,
          distributionGuardrails,
        },
        failures,
      },
      null,
      2,
    )}\n`,
    "utf8",
  ),
]);

console.log(`Phase 7 Markdown written to ${MARKDOWN_PATH}`);
console.log(`Phase 7 JSON written to ${JSON_PATH}`);
const seedsWithInvariantFailures = new Set(
  failures.flatMap((failure) => (failure.seed ? [failure.seed] : [])),
);

console.log(
  `${allRuns.length - seedsWithInvariantFailures.size}/` +
    `${allRuns.length} games completed without seed-specific invariant failures.`,
);
console.log(
  `${aggregateBalanceGuardrails.filter((guardrail) => guardrail.passed).length}/` +
    `${aggregateBalanceGuardrails.length} balance guardrails passed.`,
);
console.log(
  `${distributionGuardrails.filter((guardrail) => guardrail.passed).length}/` +
    `${distributionGuardrails.length} distribution guardrails passed.`,
);

if (failures.length > 0) {
  console.error(`Phase 7 failed with ${failures.length} issue(s).`);

  for (const failure of failures) {
    console.error(
      `FAIL ${failure.id}${failure.seed ? ` [${failure.seed}]` : ""}: ` + failure.message,
    );
  }

  process.exitCode = 1;
} else {
  console.log("Phase 7 validation passed.");
}
