// Generated by implement-phase-6.sh
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { collectEventDistributionMetrics } from "~/game/simulation/event-distribution-metrics";
import {
  collectDistributionExperienceMetrics,
  createDistributionRegressionBaseline,
  PHASE_6_DISTRIBUTION_BATCH,
} from "~/game/simulation/distribution-regression";
import { simulateGameBatch } from "~/game/simulation/simulation-runner";

const outputPath = resolve(
  process.cwd(),
  "app/game/simulation/distribution-regression-baseline.ts",
);

const runs = simulateGameBatch(PHASE_6_DISTRIBUTION_BATCH);
const metrics = collectEventDistributionMetrics(runs);
const experience = collectDistributionExperienceMetrics(runs);
const baseline = createDistributionRegressionBaseline(metrics, experience);

const content = `// Generated by update-distribution-regression-baseline.ts
import type { DistributionRegressionBaseline } from "./distribution-regression";

export const PHASE_6_DISTRIBUTION_BASELINE = ${JSON.stringify(
  baseline,
  null,
  2,
)} as const satisfies DistributionRegressionBaseline;
`;

writeFileSync(outputPath, content, "utf8");

console.log(
  `Updated ${outputPath} from ${baseline.sample.halfGames} Half Games and ` +
    `${baseline.sample.fullGames} Full Games.`,
);
