#!/usr/bin/env bash
# Generated by implement-phase-7.sh
set -euo pipefail

REPORT_DIRECTORY="reports"
TIMING_FILE="$REPORT_DIRECTORY/phase-7-command-timings.tsv"

mkdir -p "$REPORT_DIRECTORY"
printf "step\tseconds\n" > "$TIMING_FILE"

run_step() {
  local label="$1"
  shift

  local started_at
  local finished_at
  local elapsed

  started_at="$(date +%s)"
  echo
  echo "==> $label"
  "$@"
  finished_at="$(date +%s)"
  elapsed="$((finished_at - started_at))"

  printf "%s\t%s\n" "$label" "$elapsed" >> "$TIMING_FILE"
  echo "<== $label completed in ${elapsed}s"
}

run_step "Formatting" npm run format
run_step "Typechecking" npm run typecheck
run_step "Linting" npm run lint
run_step "Complete unit suite" npm run test
run_step \
  "Bloodbath tests" \
  npm run test -- app/game/bloodbath app/game/events/catalogue/bloodbath
run_step \
  "Catalogue tests" \
  npm run test -- app/game/events/catalogue
run_step \
  "Simulation stress tests" \
  npm run test -- app/game/engine/simulation-stress.test.ts
run_step "Balance report" npm run balance:report
run_step \
  "Distribution report" \
  npm run event-distribution -- \
    --half-games 200 \
    --full-games 100 \
    --seed-prefix phase-7-report \
    --output-directory reports/phase-7-event-distribution
run_step "Phase 7 multi-seed validation" npm run phase7:validate

echo
echo "Phase 7 full validation completed successfully."
echo "Command timings written to $TIMING_FILE"
echo "Validation report written to reports/phase-7-validation-report.md"
echo "Validation data written to reports/phase-7-validation-report.json"
