import type { TributeDefinition, TributeStatValue } from "~/game/types/tribute";
import { DEFAULT_PRONOUN_SET_ID, type PronounSetId } from "~/game/tributes/pronouns";

function createTributeDefinition(
  id: string,
  name: string,
  pronouns: PronounSetId = DEFAULT_PRONOUN_SET_ID,
  brains: TributeStatValue,
  brawn: TributeStatValue,
  luck: TributeStatValue,
): TributeDefinition {
  return {
    id,
    name,
    pronouns,
    portraitUrl: null,
    stats: {
      brains,
      brawn,
      luck,
    },
  };
}

export const DEFAULT_TRIBUTES = [
  createTributeDefinition("winnie-the-pooh", "Winnie the Pooh", "he", 2, 1, 3),
  createTributeDefinition("paddington-bear", "Paddington Bear", "he", 3, 2, 5),
  createTributeDefinition("kermit-the-frog", "Kermit the Frog", "he", 4, 1, 3),
  createTributeDefinition("miss-piggy", "Miss Piggy", "she", 3, 4, 2),
  createTributeDefinition("spongebob-squarepants", "SpongeBob SquarePants", "he", 2, 3, 5),
  createTributeDefinition("scooby-doo", "Scooby-Doo", "he", 1, 2, 5),
  createTributeDefinition("shaggy", "Shaggy", "he", 2, 1, 5),
  createTributeDefinition("kirby", "Kirby", "they", 1, 5, 5),
  createTributeDefinition("harry-potter", "Harry Potter", "he", 2, 3, 5),
  createTributeDefinition("hermione-granger", "Hermione Granger", "she", 5, 1, 3),
  createTributeDefinition("gandalf", "Gandalf", "he", 5, 3, 2),
  createTributeDefinition("gollum", "Gollum", "he", 4, 1, 1),
  createTributeDefinition("shrek", "Shrek", "he", 3, 5, 2),
  createTributeDefinition("link", "Link", "he", 2, 5, 4),
  createTributeDefinition("lara-croft", "Lara Croft", "she", 4, 4, 2),
  createTributeDefinition("indiana-jones", "Indiana Jones", "he", 3, 3, 2),
  createTributeDefinition("batman", "Batman", "he", 5, 4, 1),
  createTributeDefinition("harley-quinn", "Harley Quinn", "she", 2, 4, 4),
  createTributeDefinition("spider-man", "Spider-Man", "he", 4, 4, 4),
  createTributeDefinition("deadpool", "Deadpool", "he", 2, 4, 3),
  createTributeDefinition("loki", "Loki", "he", 5, 2, 3),
  createTributeDefinition("wonder-woman", "Wonder Woman", "she", 2, 5, 2),
  createTributeDefinition("poison-ivy", "Poison Ivy", "she", 5, 2, 3),
  createTributeDefinition("mario", "Mario", "he", 2, 4, 5),
  createTributeDefinition("luigi", "Luigi", "he", 3, 3, 5),
  createTributeDefinition("princess-peach", "Princess Peach", "she", 2, 1, 4),
  createTributeDefinition("bowser", "Bowser", "he", 2, 5, 3),
  createTributeDefinition("sonic-the-hedgehog", "Sonic the Hedgehog", "he", 2, 4, 4),
  createTributeDefinition("kratos", "Kratos", "he", 3, 5, 1),
  createTributeDefinition("michael-myers", "Michael Myers", "he", 2, 5, 4),
  createTributeDefinition("ghostface", "Ghostface", "they", 3, 3, 4),
  createTributeDefinition("chucky", "Chucky", "he", 3, 3, 5),
  createTributeDefinition("megan", "M3GAN", "she", 5, 4, 1),
  createTributeDefinition("pennywise", "Pennywise", "it", 4, 4, 1),
  createTributeDefinition("wednesday-addams", "Wednesday Addams", "she", 5, 1, 3),
  createTributeDefinition("hannibal-lecter", "Hannibal Lecter", "he", 5, 2, 2),
  createTributeDefinition("pearl", "Pearl", "she", 2, 3, 4),
  createTributeDefinition("elle-woods", "Elle Woods", "she", 5, 2, 3),
  createTributeDefinition("regina-george", "Regina George", "she", 4, 2, 4),
  createTributeDefinition("barbie", "Barbie", "she", 3, 2, 4),
  createTributeDefinition("moira-rose", "Moira Rose", "she", 3, 1, 3),
  createTributeDefinition("ron-swanson", "Ron Swanson", "he", 4, 4, 2),
  createTributeDefinition("darth-vader", "Darth Vader", "he", 4, 3, 1),
  createTributeDefinition("captain-jack-sparrow", "Captain Jack Sparrow", "he", 4, 3, 5),
  createTributeDefinition("bear-obsession", "Bear from Obsession", "he", 3, 2, 1),
  createTributeDefinition("bluey", "Bluey", "he", 4, 1, 5),
  createTributeDefinition("totoro", "Totoro", "they", 3, 4, 5),
  createTributeDefinition("wall-e", "WALL-E", "he", 2, 2, 2),
  createTributeDefinition("pikachu", "Pikachu", "they", 2, 4, 2),
  createTributeDefinition("legolas", "Legolas", "he", 4, 4, 3),
  createTributeDefinition("princess-fiona", "Princess Fiona", "she", 3, 4, 3),
  createTributeDefinition("princess-zelda", "Princess Zelda", "she", 5, 2, 4),
  createTributeDefinition("percy-jackson", "Percy Jackson", "he", 2, 4, 5),
  createTributeDefinition("frodo-baggins", "Frodo Baggins", "he", 3, 2, 5),
  createTributeDefinition("yoda", "Yoda", "he", 5, 3, 2),
  createTributeDefinition("severus-snape", "Severus Snape", "he", 3, 2, 1),
  createTributeDefinition("daenerys-targaryen", "Daenerys Targaryen", "she", 4, 3, 3),
  createTributeDefinition("tyrion-lannister", "Tyrion Lannister", "he", 5, 2, 4),
  createTributeDefinition("elphaba", "Elphaba", "she", 5, 4, 1),
  createTributeDefinition("glinda", "Glinda", "she", 3, 2, 5),
  createTributeDefinition("superman", "Superman", "he", 2, 5, 2),
  createTributeDefinition("the-joker", "The Joker", "he", 4, 1, 5),
  createTributeDefinition("magneto", "Magneto", "he", 4, 3, 2),
  createTributeDefinition("catwoman", "Catwoman", "she", 4, 4, 3),
  createTributeDefinition("wario", "Wario", "he", 1, 5, 4),
  createTributeDefinition("shadow-the-hedgehog", "Shadow the Hedgehog", "he", 3, 5, 3),
  createTributeDefinition("pac-man", "Pac-Man", "he", 1, 2, 3),
  createTributeDefinition("freddy-krueger", "Freddy Krueger", "he", 3, 3, 3),
  createTributeDefinition("jason-voorhees", "Jason Voorhees", "he", 1, 5, 4),
  createTributeDefinition("carrie-white", "Carrie White", "she", 4, 4, 1),
  createTributeDefinition("beetlejuice", "Beetlejuice", "he", 4, 2, 3),
  createTributeDefinition("jack-skellington", "Jack Skellington", "he", 4, 3, 4),
  createTributeDefinition("buffy-summers", "Buffy Summers", "she", 4, 5, 2),
  createTributeDefinition("velma-dinkley", "Velma Dinkley", "she", 5, 1, 3),
  createTributeDefinition("dwight-schrute", "Dwight Schrute", "he", 4, 2, 3),
  createTributeDefinition("leslie-knope", "Leslie Knope", "she", 5, 2, 4),
  createTributeDefinition("michael-scott", "Michael Scott", "he", 1, 2, 5),
  createTributeDefinition("walter-white", "Walter White", "he", 5, 2, 1),
  createTributeDefinition("ken", "Ken", "he", 1, 3, 5),
  createTributeDefinition("mr-bean", "Mr. Bean", "he", 1, 2, 5),
  createTributeDefinition("austin-powers", "Austin Powers", "he", 1, 2, 5),
  createTributeDefinition("dr-evil", "Dr. Evil", "he", 2, 1, 5),
  createTributeDefinition("furiosa", "Furiosa", "she", 4, 4, 2),
  createTributeDefinition("katniss-everdeen", "Katniss Everdeen", "she", 4, 3, 5),
  createTributeDefinition("peeta-mellark", "Peeta Mellark", "he", 3, 4, 5),
  createTributeDefinition("edward-cullen", "Edward Cullen", "he", 3, 5, 2),
  createTributeDefinition("bella-swan", "Bella Swan", "she", 3, 1, 5),
  createTributeDefinition("nikki-obsession", "Nikki from Obsession", "she", 3, 2, 1),
  createTributeDefinition("mothman", "Mothman", "he", 3, 2, 5),
  createTributeDefinition("the-grinch", "The Grinch", "he", 4, 3, 3),
  createTributeDefinition("stitch", "Stitch", "he", 3, 5, 5),
  createTributeDefinition("bugs-bunny", "Bugs Bunny", "he", 4, 3, 5),
  createTributeDefinition("daffy-duck", "Daffy Duck", "he", 3, 3, 4),
  createTributeDefinition("johnny-bravo", "Johnny Bravo", "he", 1, 4, 3),
  createTributeDefinition("dexter", "Dexter", "he", 5, 2, 3),
  createTributeDefinition("perry-the-platypus", "Perry the Platypus", "he", 4, 4, 3),
  createTributeDefinition("dr-doofenshmirtz", "Dr. Doofenshmirtz", "he", 5, 1, 2),
  createTributeDefinition("kim-possible", "Kim Possible", "she", 4, 4, 3),
  createTributeDefinition("ron-stoppable", "Ron Stoppable", "he", 3, 1, 5),
  createTributeDefinition("shego", "Shego", "she", 4, 5, 3),
  createTributeDefinition("puss-in-boots", "Puss in Boots", "he", 3, 3, 2),
  createTributeDefinition("donkey", "Donkey", "he", 2, 3, 2),
  createTributeDefinition("aragorn", "Aragorn", "he", 4, 5, 3),
  createTributeDefinition("samwise-gamgee", "Samwise Gamgee", "he", 4, 3, 5),
  createTributeDefinition("eowyn", "Éowyn", "she", 4, 5, 2),
  createTributeDefinition("geralt-of-rivia", "Geralt of Rivia", "he", 4, 5, 2),
  createTributeDefinition("luke-skywalker", "Luke Skywalker", "he", 4, 4, 2),
  createTributeDefinition("princess-leia", "Princess Leia", "she", 5, 2, 4),
  createTributeDefinition("han-solo", "Han Solo", "he", 4, 3, 5),
  createTributeDefinition("chewbacca", "Chewbacca", "he", 3, 5, 4),
  createTributeDefinition("obi-wan-kenobi", "Obi-Wan Kenobi", "he", 5, 4, 3),
  createTributeDefinition("grogu", "Grogu", "he", 4, 1, 5),
  createTributeDefinition("the-mandalorian", "The Mandalorian", "he", 3, 4, 2),
  createTributeDefinition("wolverine", "Wolverine", "he", 3, 5, 4),
  createTributeDefinition("storm", "Storm", "she", 5, 4, 2),
  createTributeDefinition("donkey-kong", "Donkey Kong", "he", 1, 5, 4),
  createTributeDefinition("yoshi", "Yoshi", "he", 2, 3, 3),
  createTributeDefinition("toad", "Toad", "they", 3, 1, 1),
  createTributeDefinition("princess-daisy", "Princess Daisy", "she", 4, 2, 3),
  createTributeDefinition("cloud-strife", "Cloud Strife", "he", 2, 5, 3),
  createTributeDefinition("sephiroth", "Sephiroth", "he", 4, 4, 1),
  createTributeDefinition("aerith-gainsborough", "Aerith Gainsborough", "she", 5, 1, 1),
  createTributeDefinition("master-chief", "Master Chief", "he", 4, 5, 2),
  createTributeDefinition("aloy", "Aloy", "she", 5, 5, 4),
  createTributeDefinition("joel-miller", "Joel Miller", "he", 4, 4, 1),
  createTributeDefinition("ellie-williams", "Ellie Williams", "she", 4, 2, 4),
  createTributeDefinition("the-babadook", "The Babadook", "it", 4, 2, 4),
  createTributeDefinition("jigsaw", "Jigsaw", "he", 5, 1, 2),
  createTributeDefinition("leatherface", "Leatherface", "he", 1, 4, 3),
  createTributeDefinition("norman-bates", "Norman Bates", "he", 4, 1, 2),
  createTributeDefinition("xenomorph", "Xenomorph", "it", 3, 5, 3),
  createTributeDefinition("predator", "Predator", "it", 4, 5, 3),
  createTributeDefinition("ted-lasso", "Ted Lasso", "he", 4, 2, 3),
  createTributeDefinition("fleabag", "Fleabag", "she", 4, 1, 4),
  createTributeDefinition("villanelle", "Villanelle", "she", 4, 5, 2),
  createTributeDefinition("david-rose", "David Rose", "he", 4, 1, 3),
  createTributeDefinition("alexis-rose", "Alexis Rose", "she", 4, 2, 3),
  createTributeDefinition("lucille-bluth", "Lucille Bluth", "she", 5, 1, 2),
  createTributeDefinition("jake-peralta", "Jake Peralta", "he", 4, 2, 3),
  createTributeDefinition("captain-holt", "Captain Holt", "he", 5, 2, 3),
  createTributeDefinition("eleanor-shellstrop", "Eleanor Shellstrop", "she", 3, 2, 3),
  createTributeDefinition("april-ludgate", "April Ludgate", "she", 3, 1, 3),
  createTributeDefinition("rumi-kpop", "Rumi", "she", 4, 4, 2),
  createTributeDefinition("jinx-arcane", "Jinx", "she", 4, 4, 2),
  createTributeDefinition("vi-arcane", "Vi", "she", 3, 5, 2),
  createTributeDefinition("satoru-gojo", "Satoru Gojo", "he", 4, 5, 2),
  createTributeDefinition("avatar-aang", "Aang", "he", 3, 3, 5),
  createTributeDefinition("zuko", "Zuko", "he", 4, 4, 3),
  createTributeDefinition("katara", "Katara", "she", 4, 3, 4),
  createTributeDefinition("bigfoot", "Bigfoot", "it", 1, 5, 5),
  createTributeDefinition("kool-aid-man", "Kool-Aid Man", "it", 1, 5, 3),
  createTributeDefinition("clippy", "Clippy", "it", 4, 1, 5),
  createTributeDefinition("bob-belcher", "Bob Belcher", "he", 4, 2, 2),
  createTributeDefinition("louise-belcher", "Louise Belcher", "she", 5, 1, 5),
  createTributeDefinition("rick-sanchez", "Rick Sanchez", "he", 5, 3, 1),
  createTributeDefinition("morty-smith", "Morty Smith", "he", 3, 1, 5),
  createTributeDefinition("homer-simpson", "Homer Simpson", "he", 1, 1, 5),
] satisfies readonly TributeDefinition[];
